/* Auto-generated by CMIS2C - CMIS Page 11h Register Map */
#ifndef __CMIS_PAGE_11H_H
#define __CMIS_PAGE_11H_H

#include <stdint.h>

typedef enum {
    Enums_DPStateHostLane_Reserved = 0,  /**< Reserved **/
    Enums_DPStateHostLane_DPDeactivated_orUnusedLane = 1,  /**< DPDeactivated (or unused lane) **/
    Enums_DPStateHostLane_DPInit = 2,  /**< DPInit **/
    Enums_DPStateHostLane_DPDeinit = 3,  /**< DPDeinit **/
    Enums_DPStateHostLane_DPActivated = 4,  /**< DPActivated **/
    Enums_DPStateHostLane_DPTxTurnOn = 5,  /**< DPTxTurnOn **/
    Enums_DPStateHostLane_DPTxTurnOff = 6,  /**< DPTxTurnOff **/
    Enums_DPStateHostLane_DPInitialized = 7,  /**< DPInitialized **/
} Enums_DPStateHostLane;

typedef enum {
    Enums_ConfigStatusLane_ConfigUndefined = 0,  /**< ConfigUndefined **/
    Enums_ConfigStatusLane_ConfigSuccess = 1,  /**< ConfigSuccess **/
    Enums_ConfigStatusLane_ConfigRejected = 2,  /**< ConfigRejected **/
    Enums_ConfigStatusLane_ConfigRejectedInvalidAppSel = 3,  /**< ConfigRejectedInvalidAppSel **/
    Enums_ConfigStatusLane_ConfigRejectedInvalidDataPath = 4,  /**< ConfigRejectedInvalidDataPath **/
    Enums_ConfigStatusLane_ConfigRejectedInvalidSI = 5,  /**< ConfigRejectedInvalidSI **/
    Enums_ConfigStatusLane_ConfigRejectedLanesInUse = 6,  /**< ConfigRejectedLanesInUse **/
    Enums_ConfigStatusLane_ConfigRejectedPartialDataPath = 7,  /**< ConfigRejectedPartialDataPath **/
    Enums_ConfigStatusLane_Reserved_8 = 8,  /**< - **/
    Enums_ConfigStatusLane_Reserved_9 = 9,  /**< - **/
    Enums_ConfigStatusLane_Reserved_10 = 10,  /**< - **/
    Enums_ConfigStatusLane_ConfigInProgress = 12,  /**< ConfigInProgress **/
    Enums_ConfigStatusLane_Reserved_13 = 13,  /**< - **/
    Enums_ConfigStatusLane_Reserved_14 = 14,  /**< - **/
    Enums_ConfigStatusLane_Reserved_15 = 15,  /**< - **/
} Enums_ConfigStatusLane;

/** @brief CMIS Page 11h Register Map (Bytes 128-255) */
typedef struct __attribute__((packed)) {

    /** @brief DPStateHostLane (uint32_t, 4 bytes) */
    union {
        struct __attribute__((packed)) {
        /**
         * @brief DPStateHostLane1
         * @details Data Path State of host lane 1 (see Table 8-84)
         */
        uint32_t DPStateHostLane1 : 4;  /* bits 3:0 */
        /**
         * @brief DPStateHostLane2
         * @details Data Path State of host lane 2 (see Table 8-84)
         * @access RO Rqd.
         */
        uint32_t DPStateHostLane2 : 4;  /* bits 7:4 */
        /**
         * @brief DPStateHostLane3
         * @details Data Path State of host lane 3 (see Table 8-84)
         */
        uint32_t DPStateHostLane3 : 4;  /* bits 11:8 */
        /**
         * @brief DPStateHostLane4
         * @details Data Path State of host lane 4 (see Table 8-84)
         * @access RO Rqd.
         */
        uint32_t DPStateHostLane4 : 4;  /* bits 15:12 */
        /**
         * @brief DPStateHostLane5
         * @details Data Path State of host lane 5 (see Table 8-84)
         */
        uint32_t DPStateHostLane5 : 4;  /* bits 19:16 */
        /**
         * @brief DPStateHostLane6
         * @details Data Path State of host lane 6 (see Table 8-84)
         * @access RO Rqd.
         */
        uint32_t DPStateHostLane6 : 4;  /* bits 23:20 */
        /**
         * @brief DPStateHostLane7
         * @details Data Path State of host lane 7 (see Table 8-84)
         */
        uint32_t DPStateHostLane7 : 4;  /* bits 27:24 */
        /**
         * @brief DPStateHostLane8
         * @details Data Path State of host lane 8 (see Table 8-84)
         * @access RO Rqd.
         */
        uint32_t DPStateHostLane8 : 4;  /* bits 31:28 */
        };
        uint32_t DPStateHostLane;
    };
        /**
         * @brief OutputStatusRx1
         */
        /**
         * @brief OutputStatusRx2
         */
        /**
         * @brief OutputStatusRx3
         */
        /**
         * @brief OutputStatusRx4
         */
        /**
         * @brief OutputStatusRx5
         */
        /**
         * @brief OutputStatusRx6
         */
        /**
         * @brief OutputStatusRx7
         */
        /**
         * @brief OutputStatusRx8
         * @details OutputStatusRx<i> 0b: Rx<i> output signal invalid or muted 1b: Rx<i> output signal valid
         * @access RO Rqd.
         */
    union {
        struct {
            uint8_t OutputStatusRx1 : 1;  /* r132.0 */
            uint8_t OutputStatusRx2 : 1;  /* r132.1 */
            uint8_t OutputStatusRx3 : 1;  /* r132.2 */
            uint8_t OutputStatusRx4 : 1;  /* r132.3 */
            uint8_t OutputStatusRx5 : 1;  /* r132.4 */
            uint8_t OutputStatusRx6 : 1;  /* r132.5 */
            uint8_t OutputStatusRx7 : 1;  /* r132.6 */
            uint8_t OutputStatusRx8 : 1;  /* r132.7 */
        };
        uint8_t OutputStatusRx;
    };
        /**
         * @brief OutputStatusTx1
         */
        /**
         * @brief OutputStatusTx2
         */
        /**
         * @brief OutputStatusTx3
         */
        /**
         * @brief OutputStatusTx4
         */
        /**
         * @brief OutputStatusTx5
         */
        /**
         * @brief OutputStatusTx6
         */
        /**
         * @brief OutputStatusTx7
         */
        /**
         * @brief OutputStatusTx8
         * @details OutputStatusTx<i> 0b: Tx<i> output signal muted or invalid 1b: Tx<i> output signal valid
         * @access RO Rqd.
         */
    union {
        struct {
            uint8_t OutputStatusTx1 : 1;  /* r133.0 */
            uint8_t OutputStatusTx2 : 1;  /* r133.1 */
            uint8_t OutputStatusTx3 : 1;  /* r133.2 */
            uint8_t OutputStatusTx4 : 1;  /* r133.3 */
            uint8_t OutputStatusTx5 : 1;  /* r133.4 */
            uint8_t OutputStatusTx6 : 1;  /* r133.5 */
            uint8_t OutputStatusTx7 : 1;  /* r133.6 */
            uint8_t OutputStatusTx8 : 1;  /* r133.7 */
        };
        uint8_t OutputStatusTx;
    };
        /**
         * @brief DPStateChangedFlag1
         */
        /**
         * @brief DPStateChangedFlag2
         */
        /**
         * @brief DPStateChangedFlag3
         */
        /**
         * @brief DPStateChangedFlag4
         */
        /**
         * @brief DPStateChangedFlag5
         */
        /**
         * @brief DPStateChangedFlag6
         */
        /**
         * @brief DPStateChangedFlag7
         */
        /**
         * @brief DPStateChangedFlag8
         * @details DPStateChangedFlag<i> Latched Data Path State Changed Flag, host lane <i>
         * @access RO/COR Rqd.
         */
    union {
        struct {
            uint8_t DPStateChangedFlag1 : 1;  /* r134.0 */
            uint8_t DPStateChangedFlag2 : 1;  /* r134.1 */
            uint8_t DPStateChangedFlag3 : 1;  /* r134.2 */
            uint8_t DPStateChangedFlag4 : 1;  /* r134.3 */
            uint8_t DPStateChangedFlag5 : 1;  /* r134.4 */
            uint8_t DPStateChangedFlag6 : 1;  /* r134.5 */
            uint8_t DPStateChangedFlag7 : 1;  /* r134.6 */
            uint8_t DPStateChangedFlag8 : 1;  /* r134.7 */
        };
        uint8_t DPStateChangedFlag;
    };
        /**
         * @brief FailureFlagTx1
         */
        /**
         * @brief FailureFlagTx2
         */
        /**
         * @brief FailureFlagTx3
         */
        /**
         * @brief FailureFlagTx4
         */
        /**
         * @brief FailureFlagTx5
         */
        /**
         * @brief FailureFlagTx6
         */
        /**
         * @brief FailureFlagTx7
         */
        /**
         * @brief FailureFlagTx8
         * @details FailureFlagTx<i> Latched Tx Failure Flag, affecting media lane <i> This Flag indicates an internal 
         * failurethat causes an unspecified malfunction in the Tx facility used by media lane <i>. Note: This Flag was 
         * formerlynamed Tx Fault. See glossary for definitions of Fault and Failure. Advertisement: 01h:157.0
         * @access RO/COR Adv.
         */
    union {
        struct {
            uint8_t FailureFlagTx1 : 1;  /* r135.0 */
            uint8_t FailureFlagTx2 : 1;  /* r135.1 */
            uint8_t FailureFlagTx3 : 1;  /* r135.2 */
            uint8_t FailureFlagTx4 : 1;  /* r135.3 */
            uint8_t FailureFlagTx5 : 1;  /* r135.4 */
            uint8_t FailureFlagTx6 : 1;  /* r135.5 */
            uint8_t FailureFlagTx7 : 1;  /* r135.6 */
            uint8_t FailureFlagTx8 : 1;  /* r135.7 */
        };
        uint8_t FailureFlagTx;
    };
        /**
         * @brief LOSFlagTx1
         */
        /**
         * @brief LOSFlagTx2
         */
        /**
         * @brief LOSFlagTx3
         */
        /**
         * @brief LOSFlagTx4
         */
        /**
         * @brief LOSFlagTx5
         */
        /**
         * @brief LOSFlagTx6
         */
        /**
         * @brief LOSFlagTx7
         */
        /**
         * @brief LOSFlagTx8
         * @details LOSFlagTx<i> Latched Tx LOS Flag, host lane <i> Advertisement: 01h:157.1
         * @access RO/COR Adv.
         */
    union {
        struct {
            uint8_t LOSFlagTx1 : 1;  /* r136.0 */
            uint8_t LOSFlagTx2 : 1;  /* r136.1 */
            uint8_t LOSFlagTx3 : 1;  /* r136.2 */
            uint8_t LOSFlagTx4 : 1;  /* r136.3 */
            uint8_t LOSFlagTx5 : 1;  /* r136.4 */
            uint8_t LOSFlagTx6 : 1;  /* r136.5 */
            uint8_t LOSFlagTx7 : 1;  /* r136.6 */
            uint8_t LOSFlagTx8 : 1;  /* r136.7 */
        };
        uint8_t LOSFlagTx;
    };
        /**
         * @brief CDRLOLFlagTx1
         */
        /**
         * @brief CDRLOLFlagTx2
         */
        /**
         * @brief CDRLOLFlagTx3
         */
        /**
         * @brief CDRLOLFlagTx4
         */
        /**
         * @brief CDRLOLFlagTx5
         */
        /**
         * @brief CDRLOLFlagTx6
         */
        /**
         * @brief CDRLOLFlagTx7
         */
        /**
         * @brief CDRLOLFlagTx8
         * @details CDRLOLFlagTx<i> Latched Tx CDR LOL Flag, host lane <i> Advertisement: 01h:157.2
         * @access RO/COR Adv.
         */
    union {
        struct {
            uint8_t CDRLOLFlagTx1 : 1;  /* r137.0 */
            uint8_t CDRLOLFlagTx2 : 1;  /* r137.1 */
            uint8_t CDRLOLFlagTx3 : 1;  /* r137.2 */
            uint8_t CDRLOLFlagTx4 : 1;  /* r137.3 */
            uint8_t CDRLOLFlagTx5 : 1;  /* r137.4 */
            uint8_t CDRLOLFlagTx6 : 1;  /* r137.5 */
            uint8_t CDRLOLFlagTx7 : 1;  /* r137.6 */
            uint8_t CDRLOLFlagTx8 : 1;  /* r137.7 */
        };
        uint8_t CDRLOLFlagTx;
    };
        /**
         * @brief AdaptiveInputEqFailFlagTx1
         */
        /**
         * @brief AdaptiveInputEqFailFlagTx2
         */
        /**
         * @brief AdaptiveInputEqFailFlagTx3
         */
        /**
         * @brief AdaptiveInputEqFailFlagTx4
         */
        /**
         * @brief AdaptiveInputEqFailFlagTx5
         */
        /**
         * @brief AdaptiveInputEqFailFlagTx6
         */
        /**
         * @brief AdaptiveInputEqFailFlagTx7
         */
        /**
         * @brief AdaptiveInputEqFailFlagTx8
         * @details AdaptiveInputEqFailFlagTx<i> Latched Tx Adaptive Input Eq Fail, host lane <i> Advertisement: 
         * 01h:157.3
         * @access RO/COR Adv.
         */
    union {
        struct {
            uint8_t AdaptiveInputEqFailFlagTx1 : 1;  /* r138.0 */
            uint8_t AdaptiveInputEqFailFlagTx2 : 1;  /* r138.1 */
            uint8_t AdaptiveInputEqFailFlagTx3 : 1;  /* r138.2 */
            uint8_t AdaptiveInputEqFailFlagTx4 : 1;  /* r138.3 */
            uint8_t AdaptiveInputEqFailFlagTx5 : 1;  /* r138.4 */
            uint8_t AdaptiveInputEqFailFlagTx6 : 1;  /* r138.5 */
            uint8_t AdaptiveInputEqFailFlagTx7 : 1;  /* r138.6 */
            uint8_t AdaptiveInputEqFailFlagTx8 : 1;  /* r138.7 */
        };
        uint8_t AdaptiveInputEqFailFlagTx;
    };
        /**
         * @brief OpticalPowerHighAlarmFlagTx1
         */
        /**
         * @brief OpticalPowerHighAlarmFlagTx2
         */
        /**
         * @brief OpticalPowerHighAlarmFlagTx3
         */
        /**
         * @brief OpticalPowerHighAlarmFlagTx4
         */
        /**
         * @brief OpticalPowerHighAlarmFlagTx5
         */
        /**
         * @brief OpticalPowerHighAlarmFlagTx6
         */
        /**
         * @brief OpticalPowerHighAlarmFlagTx7
         */
        /**
         * @brief OpticalPowerHighAlarmFlagTx8
         * @details OpticalPowerHighAlarmFlagTx<i> Latched Tx output power High Alarm, media lane <i> Advertisement: 
         * 01h:160.1
         * @access RO/COR Adv.
         */
    union {
        struct {
            uint8_t OpticalPowerHighAlarmFlagTx1 : 1;  /* r139.0 */
            uint8_t OpticalPowerHighAlarmFlagTx2 : 1;  /* r139.1 */
            uint8_t OpticalPowerHighAlarmFlagTx3 : 1;  /* r139.2 */
            uint8_t OpticalPowerHighAlarmFlagTx4 : 1;  /* r139.3 */
            uint8_t OpticalPowerHighAlarmFlagTx5 : 1;  /* r139.4 */
            uint8_t OpticalPowerHighAlarmFlagTx6 : 1;  /* r139.5 */
            uint8_t OpticalPowerHighAlarmFlagTx7 : 1;  /* r139.6 */
            uint8_t OpticalPowerHighAlarmFlagTx8 : 1;  /* r139.7 */
        };
        uint8_t OpticalPowerHighAlarmFlagTx;
    };
        /**
         * @brief OpticalPowerLowAlarmFlagTx1
         */
        /**
         * @brief OpticalPowerLowAlarmFlagTx2
         */
        /**
         * @brief OpticalPowerLowAlarmFlagTx3
         */
        /**
         * @brief OpticalPowerLowAlarmFlagTx4
         * @details Advertisement: 01h:160.1
         */
        /**
         * @brief OpticalPowerLowAlarmFlagTx5
         */
        /**
         * @brief OpticalPowerLowAlarmFlagTx6
         */
        /**
         * @brief OpticalPowerLowAlarmFlagTx7
         */
        /**
         * @brief OpticalPowerLowAlarmFlagTx8
         * @details OpticalPowerLowAlarmFlagTx<i> Latched Tx output power Low alarm, media lane <i>
         * @access RO/COR Adv.
         */
    union {
        struct {
            uint8_t OpticalPowerLowAlarmFlagTx1 : 1;  /* r140.0 */
            uint8_t OpticalPowerLowAlarmFlagTx2 : 1;  /* r140.1 */
            uint8_t OpticalPowerLowAlarmFlagTx3 : 1;  /* r140.2 */
            uint8_t OpticalPowerLowAlarmFlagTx4 : 1;  /* r140.3 */
            uint8_t OpticalPowerLowAlarmFlagTx5 : 1;  /* r140.4 */
            uint8_t OpticalPowerLowAlarmFlagTx6 : 1;  /* r140.5 */
            uint8_t OpticalPowerLowAlarmFlagTx7 : 1;  /* r140.6 */
            uint8_t OpticalPowerLowAlarmFlagTx8 : 1;  /* r140.7 */
        };
        uint8_t OpticalPowerLowAlarmFlagTx;
    };
        /**
         * @brief OpticalPowerHighWarningFlagTx1
         */
        /**
         * @brief OpticalPowerHighWarningFlagTx2
         */
        /**
         * @brief OpticalPowerHighWarningFlagTx3
         */
        /**
         * @brief OpticalPowerHighWarningFlagTx4
         */
        /**
         * @brief OpticalPowerHighWarningFlagTx5
         */
        /**
         * @brief OpticalPowerHighWarningFlagTx6
         */
        /**
         * @brief OpticalPowerHighWarningFlagTx7
         */
        /**
         * @brief OpticalPowerHighWarningFlagTx8
         * @details OpticalPowerHighWarningFlagTx<i> Latched Tx output power High warning, media lane <i> 
         * Advertisement:01h:160.1
         * @access RO/COR Adv.
         */
    union {
        struct {
            uint8_t OpticalPowerHighWarningFlagTx1 : 1;  /* r141.0 */
            uint8_t OpticalPowerHighWarningFlagTx2 : 1;  /* r141.1 */
            uint8_t OpticalPowerHighWarningFlagTx3 : 1;  /* r141.2 */
            uint8_t OpticalPowerHighWarningFlagTx4 : 1;  /* r141.3 */
            uint8_t OpticalPowerHighWarningFlagTx5 : 1;  /* r141.4 */
            uint8_t OpticalPowerHighWarningFlagTx6 : 1;  /* r141.5 */
            uint8_t OpticalPowerHighWarningFlagTx7 : 1;  /* r141.6 */
            uint8_t OpticalPowerHighWarningFlagTx8 : 1;  /* r141.7 */
        };
        uint8_t OpticalPowerHighWarningFlagTx;
    };
        /**
         * @brief OpticalPowerLowWarningFlagTx1
         */
        /**
         * @brief OpticalPowerLowWarningFlagTx2
         */
        /**
         * @brief OpticalPowerLowWarningFlagTx3
         */
        /**
         * @brief OpticalPowerLowWarningFlagTx4
         */
        /**
         * @brief OpticalPowerLowWarningFlagTx5
         */
        /**
         * @brief OpticalPowerLowWarningFlagTx6
         */
        /**
         * @brief OpticalPowerLowWarningFlagTx7
         */
        /**
         * @brief OpticalPowerLowWarningFlagTx8
         * @details OpticalPowerLowWarningFlagTx<i> Latched Tx output power Low warning, media lane <i> Advertisement: 
         * 01h:160.1
         * @access RO/COR Adv.
         */
    union {
        struct {
            uint8_t OpticalPowerLowWarningFlagTx1 : 1;  /* r142.0 */
            uint8_t OpticalPowerLowWarningFlagTx2 : 1;  /* r142.1 */
            uint8_t OpticalPowerLowWarningFlagTx3 : 1;  /* r142.2 */
            uint8_t OpticalPowerLowWarningFlagTx4 : 1;  /* r142.3 */
            uint8_t OpticalPowerLowWarningFlagTx5 : 1;  /* r142.4 */
            uint8_t OpticalPowerLowWarningFlagTx6 : 1;  /* r142.5 */
            uint8_t OpticalPowerLowWarningFlagTx7 : 1;  /* r142.6 */
            uint8_t OpticalPowerLowWarningFlagTx8 : 1;  /* r142.7 */
        };
        uint8_t OpticalPowerLowWarningFlagTx;
    };
        /**
         * @brief LaserBiasHighAlarmFlagTx1
         */
        /**
         * @brief LaserBiasHighAlarmFlagTx2
         */
        /**
         * @brief LaserBiasHighAlarmFlagTx3
         */
        /**
         * @brief LaserBiasHighAlarmFlagTx4
         */
        /**
         * @brief LaserBiasHighAlarmFlagTx5
         */
        /**
         * @brief LaserBiasHighAlarmFlagTx6
         */
        /**
         * @brief LaserBiasHighAlarmFlagTx7
         */
        /**
         * @brief LaserBiasHighAlarmFlagTx8
         * @details LaserBiasHighAlarmFlagTx<i> Latched Tx Bias High Alarm, media lane <i> Advertisement: 01h:160.0
         * @access RO/COR Adv.
         */
    union {
        struct {
            uint8_t LaserBiasHighAlarmFlagTx1 : 1;  /* r143.0 */
            uint8_t LaserBiasHighAlarmFlagTx2 : 1;  /* r143.1 */
            uint8_t LaserBiasHighAlarmFlagTx3 : 1;  /* r143.2 */
            uint8_t LaserBiasHighAlarmFlagTx4 : 1;  /* r143.3 */
            uint8_t LaserBiasHighAlarmFlagTx5 : 1;  /* r143.4 */
            uint8_t LaserBiasHighAlarmFlagTx6 : 1;  /* r143.5 */
            uint8_t LaserBiasHighAlarmFlagTx7 : 1;  /* r143.6 */
            uint8_t LaserBiasHighAlarmFlagTx8 : 1;  /* r143.7 */
        };
        uint8_t LaserBiasHighAlarmFlagTx;
    };
        /**
         * @brief LaserBiasLowAlarmFlagTx1
         */
        /**
         * @brief LaserBiasLowAlarmFlagTx2
         */
        /**
         * @brief LaserBiasLowAlarmFlagTx3
         */
        /**
         * @brief LaserBiasLowAlarmFlagTx4
         */
        /**
         * @brief LaserBiasLowAlarmFlagTx5
         */
        /**
         * @brief LaserBiasLowAlarmFlagTx6
         */
        /**
         * @brief LaserBiasLowAlarmFlagTx7
         */
        /**
         * @brief LaserBiasLowAlarmFlagTx8
         * @details LaserBiasLowAlarmFlagTx<i> Latched Tx Bias Low alarm, media lane <i> Advertisement: 01h:160.0
         * @access RO/COR Adv.
         */
    union {
        struct {
            uint8_t LaserBiasLowAlarmFlagTx1 : 1;  /* r144.0 */
            uint8_t LaserBiasLowAlarmFlagTx2 : 1;  /* r144.1 */
            uint8_t LaserBiasLowAlarmFlagTx3 : 1;  /* r144.2 */
            uint8_t LaserBiasLowAlarmFlagTx4 : 1;  /* r144.3 */
            uint8_t LaserBiasLowAlarmFlagTx5 : 1;  /* r144.4 */
            uint8_t LaserBiasLowAlarmFlagTx6 : 1;  /* r144.5 */
            uint8_t LaserBiasLowAlarmFlagTx7 : 1;  /* r144.6 */
            uint8_t LaserBiasLowAlarmFlagTx8 : 1;  /* r144.7 */
        };
        uint8_t LaserBiasLowAlarmFlagTx;
    };
        /**
         * @brief LaserBiasHighWarningFlagTx1
         */
        /**
         * @brief LaserBiasHighWarningFlagTx2
         */
        /**
         * @brief LaserBiasHighWarningFlagTx3
         */
        /**
         * @brief LaserBiasHighWarningFlagTx4
         */
        /**
         * @brief LaserBiasHighWarningFlagTx5
         */
        /**
         * @brief LaserBiasHighWarningFlagTx6
         */
        /**
         * @brief LaserBiasHighWarningFlagTx7
         */
        /**
         * @brief LaserBiasHighWarningFlagTx8
         * @details LaserBiasHighWarningFlagTx<i> Latched Tx Bias High warning, media lane <i> Advertisement: 01h:160.0
         * @access RO/COR Adv.
         */
    union {
        struct {
            uint8_t LaserBiasHighWarningFlagTx1 : 1;  /* r145.0 */
            uint8_t LaserBiasHighWarningFlagTx2 : 1;  /* r145.1 */
            uint8_t LaserBiasHighWarningFlagTx3 : 1;  /* r145.2 */
            uint8_t LaserBiasHighWarningFlagTx4 : 1;  /* r145.3 */
            uint8_t LaserBiasHighWarningFlagTx5 : 1;  /* r145.4 */
            uint8_t LaserBiasHighWarningFlagTx6 : 1;  /* r145.5 */
            uint8_t LaserBiasHighWarningFlagTx7 : 1;  /* r145.6 */
            uint8_t LaserBiasHighWarningFlagTx8 : 1;  /* r145.7 */
        };
        uint8_t LaserBiasHighWarningFlagTx;
    };
        /**
         * @brief LaserBiasLowWarningFlagTx1
         */
        /**
         * @brief LaserBiasLowWarningFlagTx2
         */
        /**
         * @brief LaserBiasLowWarningFlagTx3
         */
        /**
         * @brief LaserBiasLowWarningFlagTx4
         */
        /**
         * @brief LaserBiasLowWarningFlagTx5
         */
        /**
         * @brief LaserBiasLowWarningFlagTx6
         */
        /**
         * @brief LaserBiasLowWarningFlagTx7
         */
        /**
         * @brief LaserBiasLowWarningFlagTx8
         * @details LaserBiasLowWarningFlagTx<i> Latched Tx Bias Low warning, media lane <i> Advertisement: 01h:160.0
         * @access RO/COR Adv.
         */
    union {
        struct {
            uint8_t LaserBiasLowWarningFlagTx1 : 1;  /* r146.0 */
            uint8_t LaserBiasLowWarningFlagTx2 : 1;  /* r146.1 */
            uint8_t LaserBiasLowWarningFlagTx3 : 1;  /* r146.2 */
            uint8_t LaserBiasLowWarningFlagTx4 : 1;  /* r146.3 */
            uint8_t LaserBiasLowWarningFlagTx5 : 1;  /* r146.4 */
            uint8_t LaserBiasLowWarningFlagTx6 : 1;  /* r146.5 */
            uint8_t LaserBiasLowWarningFlagTx7 : 1;  /* r146.6 */
            uint8_t LaserBiasLowWarningFlagTx8 : 1;  /* r146.7 */
        };
        uint8_t LaserBiasLowWarningFlagTx;
    };
        /**
         * @brief LOSFlagRx1
         */
        /**
         * @brief LOSFlagRx2
         */
        /**
         * @brief LOSFlagRx3
         */
        /**
         * @brief LOSFlagRx4
         */
        /**
         * @brief LOSFlagRx5
         */
        /**
         * @brief LOSFlagRx6
         */
        /**
         * @brief LOSFlagRx7
         */
        /**
         * @brief LOSFlagRx8
         * @details LOSFlagRx<i> Latched Rx LOS Flag, media lane <i> Advertisement: 01h:158.1
         * @access RO/COR Adv.
         */
    union {
        struct {
            uint8_t LOSFlagRx1 : 1;  /* r147.0 */
            uint8_t LOSFlagRx2 : 1;  /* r147.1 */
            uint8_t LOSFlagRx3 : 1;  /* r147.2 */
            uint8_t LOSFlagRx4 : 1;  /* r147.3 */
            uint8_t LOSFlagRx5 : 1;  /* r147.4 */
            uint8_t LOSFlagRx6 : 1;  /* r147.5 */
            uint8_t LOSFlagRx7 : 1;  /* r147.6 */
            uint8_t LOSFlagRx8 : 1;  /* r147.7 */
        };
        uint8_t LOSFlagRx;
    };
        /**
         * @brief CDRLOLFlagRx1
         */
        /**
         * @brief CDRLOLFlagRx2
         */
        /**
         * @brief CDRLOLFlagRx3
         */
        /**
         * @brief CDRLOLFlagRx4
         */
        /**
         * @brief CDRLOLFlagRx5
         */
        /**
         * @brief CDRLOLFlagRx6
         */
        /**
         * @brief CDRLOLFlagRx7
         */
        /**
         * @brief CDRLOLFlagRx8
         * @details CDRLOLFlagRx<i> Latched Rx CDR LOL Flag, media lane <i> Advertisement: 01h:158.2
         * @access RO/COR Adv.
         */
    union {
        struct {
            uint8_t CDRLOLFlagRx1 : 1;  /* r148.0 */
            uint8_t CDRLOLFlagRx2 : 1;  /* r148.1 */
            uint8_t CDRLOLFlagRx3 : 1;  /* r148.2 */
            uint8_t CDRLOLFlagRx4 : 1;  /* r148.3 */
            uint8_t CDRLOLFlagRx5 : 1;  /* r148.4 */
            uint8_t CDRLOLFlagRx6 : 1;  /* r148.5 */
            uint8_t CDRLOLFlagRx7 : 1;  /* r148.6 */
            uint8_t CDRLOLFlagRx8 : 1;  /* r148.7 */
        };
        uint8_t CDRLOLFlagRx;
    };
        /**
         * @brief OpticalPowerHighAlarmFlagRx1
         */
        /**
         * @brief OpticalPowerHighAlarmFlagRx2
         */
        /**
         * @brief OpticalPowerHighAlarmFlagRx3
         */
        /**
         * @brief OpticalPowerHighAlarmFlagRx4
         */
        /**
         * @brief OpticalPowerHighAlarmFlagRx5
         */
        /**
         * @brief OpticalPowerHighAlarmFlagRx6
         */
        /**
         * @brief OpticalPowerHighAlarmFlagRx7
         */
        /**
         * @brief OpticalPowerHighAlarmFlagRx8
         * @details OpticalPowerHighAlarmFlagRx<i> Latched Rx input power High alarm, media lane <i> Advertisement: 
         * 01h:160.2
         * @access RO/COR Adv.
         */
    union {
        struct {
            uint8_t OpticalPowerHighAlarmFlagRx1 : 1;  /* r149.0 */
            uint8_t OpticalPowerHighAlarmFlagRx2 : 1;  /* r149.1 */
            uint8_t OpticalPowerHighAlarmFlagRx3 : 1;  /* r149.2 */
            uint8_t OpticalPowerHighAlarmFlagRx4 : 1;  /* r149.3 */
            uint8_t OpticalPowerHighAlarmFlagRx5 : 1;  /* r149.4 */
            uint8_t OpticalPowerHighAlarmFlagRx6 : 1;  /* r149.5 */
            uint8_t OpticalPowerHighAlarmFlagRx7 : 1;  /* r149.6 */
            uint8_t OpticalPowerHighAlarmFlagRx8 : 1;  /* r149.7 */
        };
        uint8_t OpticalPowerHighAlarmFlagRx;
    };
        /**
         * @brief OpticalPowerLowAlarmFlagRx1
         */
        /**
         * @brief OpticalPowerLowAlarmFlagRx2
         */
        /**
         * @brief OpticalPowerLowAlarmFlagRx3
         */
        /**
         * @brief OpticalPowerLowAlarmFlagRx4
         */
        /**
         * @brief OpticalPowerLowAlarmFlagRx5
         */
        /**
         * @brief OpticalPowerLowAlarmFlagRx6
         */
        /**
         * @brief OpticalPowerLowAlarmFlagRx7
         */
        /**
         * @brief OpticalPowerLowAlarmFlagRx8
         * @details OpticalPowerLowAlarmFlagRx<i> Latched Rx input power Low alarm, media lane <i> Advertisement: 
         * 01h:160.2
         * @access RO/COR Adv.
         */
    union {
        struct {
            uint8_t OpticalPowerLowAlarmFlagRx1 : 1;  /* r150.0 */
            uint8_t OpticalPowerLowAlarmFlagRx2 : 1;  /* r150.1 */
            uint8_t OpticalPowerLowAlarmFlagRx3 : 1;  /* r150.2 */
            uint8_t OpticalPowerLowAlarmFlagRx4 : 1;  /* r150.3 */
            uint8_t OpticalPowerLowAlarmFlagRx5 : 1;  /* r150.4 */
            uint8_t OpticalPowerLowAlarmFlagRx6 : 1;  /* r150.5 */
            uint8_t OpticalPowerLowAlarmFlagRx7 : 1;  /* r150.6 */
            uint8_t OpticalPowerLowAlarmFlagRx8 : 1;  /* r150.7 */
        };
        uint8_t OpticalPowerLowAlarmFlagRx;
    };
        /**
         * @brief OpticalPowerHighWarningFlagRx1
         */
        /**
         * @brief OpticalPowerHighWarningFlagRx2
         */
        /**
         * @brief OpticalPowerHighWarningFlagRx3
         */
        /**
         * @brief OpticalPowerHighWarningFlagRx4
         */
        /**
         * @brief OpticalPowerHighWarningFlagRx5
         */
        /**
         * @brief OpticalPowerHighWarningFlagRx6
         */
        /**
         * @brief OpticalPowerHighWarningFlagRx7
         */
        /**
         * @brief OpticalPowerHighWarningFlagRx8
         * @details OpticalPowerHighWarningFlagRx<i> Latched Rx input power High warning, media lane <i> Advertisement: 
         * 01h:160.2
         * @access RO/COR Adv.
         */
    union {
        struct {
            uint8_t OpticalPowerHighWarningFlagRx1 : 1;  /* r151.0 */
            uint8_t OpticalPowerHighWarningFlagRx2 : 1;  /* r151.1 */
            uint8_t OpticalPowerHighWarningFlagRx3 : 1;  /* r151.2 */
            uint8_t OpticalPowerHighWarningFlagRx4 : 1;  /* r151.3 */
            uint8_t OpticalPowerHighWarningFlagRx5 : 1;  /* r151.4 */
            uint8_t OpticalPowerHighWarningFlagRx6 : 1;  /* r151.5 */
            uint8_t OpticalPowerHighWarningFlagRx7 : 1;  /* r151.6 */
            uint8_t OpticalPowerHighWarningFlagRx8 : 1;  /* r151.7 */
        };
        uint8_t OpticalPowerHighWarningFlagRx;
    };
        /**
         * @brief OpticalPowerLowWarningFlagRx1
         */
        /**
         * @brief OpticalPowerLowWarningFlagRx2
         */
        /**
         * @brief OpticalPowerLowWarningFlagRx3
         */
        /**
         * @brief OpticalPowerLowWarningFlagRx4
         */
        /**
         * @brief OpticalPowerLowWarningFlagRx5
         */
        /**
         * @brief OpticalPowerLowWarningFlagRx6
         */
        /**
         * @brief OpticalPowerLowWarningFlagRx7
         */
        /**
         * @brief OpticalPowerLowWarningFlagRx8
         * @details OpticalPowerLowWarningFlagRx<i> Latched Rx input power Low warning, media lane <i> Advertisement: 
         * 01h:160.2
         * @access RO/COR Adv.
         */
    union {
        struct {
            uint8_t OpticalPowerLowWarningFlagRx1 : 1;  /* r152.0 */
            uint8_t OpticalPowerLowWarningFlagRx2 : 1;  /* r152.1 */
            uint8_t OpticalPowerLowWarningFlagRx3 : 1;  /* r152.2 */
            uint8_t OpticalPowerLowWarningFlagRx4 : 1;  /* r152.3 */
            uint8_t OpticalPowerLowWarningFlagRx5 : 1;  /* r152.4 */
            uint8_t OpticalPowerLowWarningFlagRx6 : 1;  /* r152.5 */
            uint8_t OpticalPowerLowWarningFlagRx7 : 1;  /* r152.6 */
            uint8_t OpticalPowerLowWarningFlagRx8 : 1;  /* r152.7 */
        };
        uint8_t OpticalPowerLowWarningFlagRx;
    };
        /**
         * @brief OutputStatusChangedFlagRx1
         */
        /**
         * @brief OutputStatusChangedFlagRx2
         */
        /**
         * @brief OutputStatusChangedFlagRx3
         */
        /**
         * @brief OutputStatusChangedFlagRx4
         */
        /**
         * @brief OutputStatusChangedFlagRx5
         */
        /**
         * @brief OutputStatusChangedFlagRx6
         */
        /**
         * @brief OutputStatusChangedFlagRx7
         */
        /**
         * @brief OutputStatusChangedFlagRx8
         * @details OutputStatusChangedFlagRx<i> Latched Output Status Changed Flag for Rx host lane <i>
         * @access RO/COR Rqd.
         */
    union {
        struct {
            uint8_t OutputStatusChangedFlagRx1 : 1;  /* r153.0 */
            uint8_t OutputStatusChangedFlagRx2 : 1;  /* r153.1 */
            uint8_t OutputStatusChangedFlagRx3 : 1;  /* r153.2 */
            uint8_t OutputStatusChangedFlagRx4 : 1;  /* r153.3 */
            uint8_t OutputStatusChangedFlagRx5 : 1;  /* r153.4 */
            uint8_t OutputStatusChangedFlagRx6 : 1;  /* r153.5 */
            uint8_t OutputStatusChangedFlagRx7 : 1;  /* r153.6 */
            uint8_t OutputStatusChangedFlagRx8 : 1;  /* r153.7 */
        };
        uint8_t OutputStatusChangedFlagRx;
    };
    /**
     * @brief OpticalPowerTx
     * @details U16 OpticalPowerTx<i> Internally measured Tx output optical power: in 0.1 uW increments, yielding a 
     * totalmeasurement range of 0 to 6.5535 mW (~-40 to +8.2 dBm for non-zero values) Advertisement: 01h:160.1
     */
    uint16_t OpticalPowerTx[8];
    /**
     * @brief LaserBiasTx
     * @details U16 LaserBiasTx<i> Internally measured Tx bias current monitor: in 2 uA increments, times the 
     * multiplierfrom Table 8-52. Advertisement: 01h:160.0
     */
    uint16_t LaserBiasTx[8];
    /**
     * @brief OpticalPowerRx
     * @details U16 OpticalPowerRx<i> Internally measured Rx input optical power: in 0.1 uW increments, yielding a 
     * totalmeasurement range of 0 to 6.5535 mW (~-40 to +8.2 dBm for non-zero values) Advertisement: 01h:160.2
     */
    uint16_t OpticalPowerRx[8];
    /** @brief ConfigStatusLane (uint32_t, 4 bytes) */
    union {
        struct __attribute__((packed)) {
        /**
         * @brief ConfigStatusLane1
         */
        uint32_t ConfigStatusLane1 : 4;  /* bits 3:0 */
        /**
         * @brief ConfigStatusLane2
         * @details ConfigStatusLane<i> Configuration Command Execution / Result Status for the Data Path of host lane 
         * <i>,during and after the most recent configuration command. See Table 8-91 for the encoding of values. Note: 
         * Thereis no feedback to the host when an Apply trigger is ignored after failed readiness test (when another 
         * configurationis still in progress)
         * @access RO Rqd.
         */
        uint32_t ConfigStatusLane2 : 4;  /* bits 7:4 */
        /**
         * @brief ConfigStatusLane3
         */
        uint32_t ConfigStatusLane3 : 4;  /* bits 11:8 */
        /**
         * @brief ConfigStatusLane4
         * @access RO Rqd.
         */
        uint32_t ConfigStatusLane4 : 4;  /* bits 15:12 */
        /**
         * @brief ConfigStatusLane5
         */
        uint32_t ConfigStatusLane5 : 4;  /* bits 19:16 */
        /**
         * @brief ConfigStatusLane6
         * @access RO Rqd.
         */
        uint32_t ConfigStatusLane6 : 4;  /* bits 23:20 */
        /**
         * @brief ConfigStatusLane7
         */
        uint32_t ConfigStatusLane7 : 4;  /* bits 27:24 */
        /**
         * @brief ConfigStatusLane8
         * @access RO Rqd.
         */
        uint32_t ConfigStatusLane8 : 4;  /* bits 31:28 */
        };
        uint32_t ConfigStatusLane;
    };
    /** @brief DPConfigLane per lane */
    struct __attribute__((packed)) {
        union {
            struct {
                /**
                 * @brief ExplicitControlLane
                 */
                uint8_t ExplicitControlLane : 1;
                /**
                 * @brief DataPathIDLane
                 */
                uint8_t DataPathIDLane : 3;
                /**
                 * @brief AppSelCodeLane
                 * @details ACS::DPConfigLane1 See Table 8-92
                 * @access RO Rqd.
                 */
                uint8_t AppSelCodeLane : 4;
            };
            uint8_t rval;
        };
    } DPConfigLane[8];
        /**
         * @brief AdaptiveInputEqEnableTx1
         */
        /**
         * @brief AdaptiveInputEqEnableTx2
         */
        /**
         * @brief AdaptiveInputEqEnableTx3
         */
        /**
         * @brief AdaptiveInputEqEnableTx4
         */
        /**
         * @brief AdaptiveInputEqEnableTx5
         */
        /**
         * @brief AdaptiveInputEqEnableTx6
         */
        /**
         * @brief AdaptiveInputEqEnableTx7
         */
        /**
         * @brief AdaptiveInputEqEnableTx8
         * @details ACS::AdaptiveInputEqEnableTx<i> Adaptive Tx input equalization for lane <i> 1b: Enabled 0b: 
         * Disabled(Host-controlled Tx input equalization for lane <i> as per HostControlledInputEqTargetTx<i>, if 
         * supported)Advertisement: 01h:161.3
         * @access RO Adv.
         */
    union {
        struct {
            uint8_t AdaptiveInputEqEnableTx1 : 1;  /* r214.0 */
            uint8_t AdaptiveInputEqEnableTx2 : 1;  /* r214.1 */
            uint8_t AdaptiveInputEqEnableTx3 : 1;  /* r214.2 */
            uint8_t AdaptiveInputEqEnableTx4 : 1;  /* r214.3 */
            uint8_t AdaptiveInputEqEnableTx5 : 1;  /* r214.4 */
            uint8_t AdaptiveInputEqEnableTx6 : 1;  /* r214.5 */
            uint8_t AdaptiveInputEqEnableTx7 : 1;  /* r214.6 */
            uint8_t AdaptiveInputEqEnableTx8 : 1;  /* r214.7 */
        };
        uint8_t AdaptiveInputEqEnableTx;
    };
    /** @brief AdaptiveInputEqRecalledTx (uint16_t, 2 bytes) */
    union {
        struct __attribute__((packed)) {
        /**
         * @brief AdaptiveInputEqRecalledTx1
         */
        uint16_t AdaptiveInputEqRecalledTx1 : 2;  /* bits 1:0 */
        /**
         * @brief AdaptiveInputEqRecalledTx2
         */
        uint16_t AdaptiveInputEqRecalledTx2 : 2;  /* bits 3:2 */
        /**
         * @brief AdaptiveInputEqRecalledTx3
         */
        uint16_t AdaptiveInputEqRecalledTx3 : 2;  /* bits 5:4 */
        /**
         * @brief AdaptiveInputEqRecalledTx4
         * @details ACS::AdaptiveInputEqRecalledTx<i> Recalled Tx Eq settings status for lane <i> 00b: settings are not 
         * recalled01b: settings have been recalled from recall buffer 1 10b: settings have been recalled from recall 
         * buffer2 11b: reserved Note: See Table 8-73 and Table 8-78 for the recall settings in the staged control 
         * sets.Advertisement: 01h:161.6-5
         * @access RO Adv.
         */
        uint16_t AdaptiveInputEqRecalledTx4 : 2;  /* bits 7:6 */
        /**
         * @brief AdaptiveInputEqRecalledTx5
         */
        uint16_t AdaptiveInputEqRecalledTx5 : 2;  /* bits 9:8 */
        /**
         * @brief AdaptiveInputEqRecalledTx6
         */
        uint16_t AdaptiveInputEqRecalledTx6 : 2;  /* bits 11:10 */
        /**
         * @brief AdaptiveInputEqRecalledTx7
         */
        uint16_t AdaptiveInputEqRecalledTx7 : 2;  /* bits 13:12 */
        /**
         * @brief AdaptiveInputEqRecalledTx8
         * @access RO Adv.
         */
        uint16_t AdaptiveInputEqRecalledTx8 : 2;  /* bits 15:14 */
        };
        uint16_t AdaptiveInputEqRecalledTx;
    };
    /** @brief HostControlledInputEqTargetTx (uint32_t, 4 bytes) */
    union {
        struct __attribute__((packed)) {
        /**
         * @brief HostControlledInputEqTargetTx1
         */
        uint32_t HostControlledInputEqTargetTx1 : 4;  /* bits 3:0 */
        /**
         * @brief HostControlledInputEqTargetTx2
         * @details ACS:: HostControlledInputEqTargetTx<i> Host-controlled Tx input equalization target for lane <i> 
         * encodedas defined in Table 6-6 Advertisement: 01h:161.2
         * @access RO Adv.
         */
        uint32_t HostControlledInputEqTargetTx2 : 4;  /* bits 7:4 */
        /**
         * @brief HostControlledInputEqTargetTx3
         */
        uint32_t HostControlledInputEqTargetTx3 : 4;  /* bits 11:8 */
        /**
         * @brief HostControlledInputEqTargetTx4
         * @access RO Adv.
         */
        uint32_t HostControlledInputEqTargetTx4 : 4;  /* bits 15:12 */
        /**
         * @brief HostControlledInputEqTargetTx5
         */
        uint32_t HostControlledInputEqTargetTx5 : 4;  /* bits 19:16 */
        /**
         * @brief HostControlledInputEqTargetTx6
         * @access RO Adv.
         */
        uint32_t HostControlledInputEqTargetTx6 : 4;  /* bits 23:20 */
        /**
         * @brief HostControlledInputEqTargetTx7
         */
        uint32_t HostControlledInputEqTargetTx7 : 4;  /* bits 27:24 */
        /**
         * @brief HostControlledInputEqTargetTx8
         * @access RO Adv.
         */
        uint32_t HostControlledInputEqTargetTx8 : 4;  /* bits 31:28 */
        };
        uint32_t HostControlledInputEqTargetTx;
    };
        /**
         * @brief CDREnableTx1
         */
        /**
         * @brief CDREnableTx2
         */
        /**
         * @brief CDREnableTx3
         */
        /**
         * @brief CDREnableTx4
         */
        /**
         * @brief CDREnableTx5
         */
        /**
         * @brief CDREnableTx6
         */
        /**
         * @brief CDREnableTx7
         */
        /**
         * @brief CDREnableTx8
         * @details ACS::CDREnableTx<i> 1b: CDR enabled 0b: CDR bypassed Advertisement: 01h:161.1
         * @access RO Adv.
         */
    union {
        struct {
            uint8_t CDREnableTx1 : 1;  /* r221.0 */
            uint8_t CDREnableTx2 : 1;  /* r221.1 */
            uint8_t CDREnableTx3 : 1;  /* r221.2 */
            uint8_t CDREnableTx4 : 1;  /* r221.3 */
            uint8_t CDREnableTx5 : 1;  /* r221.4 */
            uint8_t CDREnableTx6 : 1;  /* r221.5 */
            uint8_t CDREnableTx7 : 1;  /* r221.6 */
            uint8_t CDREnableTx8 : 1;  /* r221.7 */
        };
        uint8_t CDREnableTx;
    };
        /**
         * @brief CDREnabledRx1
         */
        /**
         * @brief CDREnabledRx2
         */
        /**
         * @brief CDREnabledRx3
         */
        /**
         * @brief CDREnabledRx4
         */
        /**
         * @brief CDREnabledRx5
         */
        /**
         * @brief CDREnabledRx6
         */
        /**
         * @brief CDREnabledRx7
         */
        /**
         * @brief CDREnabledRx8
         * @details ACS::CDREnableRx<i> 1b: CDR enabled 0b: CDR bypassed Advertisement: 01h:162.1
         * @access RO Adv.
         */
    union {
        struct {
            uint8_t CDREnabledRx1 : 1;  /* r222.0 */
            uint8_t CDREnabledRx2 : 1;  /* r222.1 */
            uint8_t CDREnabledRx3 : 1;  /* r222.2 */
            uint8_t CDREnabledRx4 : 1;  /* r222.3 */
            uint8_t CDREnabledRx5 : 1;  /* r222.4 */
            uint8_t CDREnabledRx6 : 1;  /* r222.5 */
            uint8_t CDREnabledRx7 : 1;  /* r222.6 */
            uint8_t CDREnabledRx8 : 1;  /* r222.7 */
        };
        uint8_t CDREnabledRx;
    };
    /** @brief OutputEqPreCursorTargetRx (uint32_t, 4 bytes) */
    union {
        struct __attribute__((packed)) {
        /**
         * @brief OutputEqPreCursorTargetRx1
         */
        uint32_t OutputEqPreCursorTargetRx1 : 4;  /* bits 3:0 */
        /**
         * @brief OutputEqPreCursorTargetRx2
         * @details ACS::OutputEqPreCursorTargetRx<i> Rx output pre-cursor equalization for lane <i> encoded as per 
         * Table6-7 Advertisement: 01h:162.4-3
         * @access RO Adv.
         */
        uint32_t OutputEqPreCursorTargetRx2 : 4;  /* bits 7:4 */
        /**
         * @brief OutputEqPreCursorTargetRx3
         */
        uint32_t OutputEqPreCursorTargetRx3 : 4;  /* bits 11:8 */
        /**
         * @brief OutputEqPreCursorTargetRx4
         * @access RO Adv.
         */
        uint32_t OutputEqPreCursorTargetRx4 : 4;  /* bits 15:12 */
        /**
         * @brief OutputEqPreCursorTargetRx5
         */
        uint32_t OutputEqPreCursorTargetRx5 : 4;  /* bits 19:16 */
        /**
         * @brief OutputEqPreCursorTargetRx6
         * @access RO Adv.
         */
        uint32_t OutputEqPreCursorTargetRx6 : 4;  /* bits 23:20 */
        /**
         * @brief OutputEqPreCursorTargetRx7
         */
        uint32_t OutputEqPreCursorTargetRx7 : 4;  /* bits 27:24 */
        /**
         * @brief OutputEqPreCursorTargetRx8
         * @access RO Adv.
         */
        uint32_t OutputEqPreCursorTargetRx8 : 4;  /* bits 31:28 */
        };
        uint32_t OutputEqPreCursorTargetRx;
    };
    /** @brief OutputEqPostCursorTargetRx (uint32_t, 4 bytes) */
    union {
        struct __attribute__((packed)) {
        /**
         * @brief OutputEqPostCursorTargetRx1
         */
        uint32_t OutputEqPostCursorTargetRx1 : 4;  /* bits 3:0 */
        /**
         * @brief OutputEqPostCursorTargetRx2
         * @details ACS::OutputEqPostCursorTargetRx<i> Rx output post-cursor equalization for lane <i> encoded as per 
         * Table6-7 Advertisement: 01h:162.4-3
         * @access RO Adv.
         */
        uint32_t OutputEqPostCursorTargetRx2 : 4;  /* bits 7:4 */
        /**
         * @brief OutputEqPostCursorTargetRx3
         */
        uint32_t OutputEqPostCursorTargetRx3 : 4;  /* bits 11:8 */
        /**
         * @brief OutputEqPostCursorTargetRx4
         * @access RO Adv.
         */
        uint32_t OutputEqPostCursorTargetRx4 : 4;  /* bits 15:12 */
        /**
         * @brief OutputEqPostCursorTargetRx5
         */
        uint32_t OutputEqPostCursorTargetRx5 : 4;  /* bits 19:16 */
        /**
         * @brief OutputEqPostCursorTargetRx6
         * @access RO Adv.
         */
        uint32_t OutputEqPostCursorTargetRx6 : 4;  /* bits 23:20 */
        /**
         * @brief OutputEqPostCursorTargetRx7
         */
        uint32_t OutputEqPostCursorTargetRx7 : 4;  /* bits 27:24 */
        /**
         * @brief OutputEqPostCursorTargetRx8
         * @access RO Adv.
         */
        uint32_t OutputEqPostCursorTargetRx8 : 4;  /* bits 31:28 */
        };
        uint32_t OutputEqPostCursorTargetRx;
    };
    /** @brief OutputAmplitudeTargetRx (uint32_t, 4 bytes) */
    union {
        struct __attribute__((packed)) {
        /**
         * @brief OutputAmplitudeTargetRx1
         */
        uint32_t OutputAmplitudeTargetRx1 : 4;  /* bits 3:0 */
        /**
         * @brief OutputAmplitudeTargetRx2
         * @details ACS::OutputAmplitudeTargetRx<i> Rx output amplitude level for lane <i> encoded as per Table 6-8 
         * Advertisement:01h:162.2
         * @access RO Adv.
         */
        uint32_t OutputAmplitudeTargetRx2 : 4;  /* bits 7:4 */
        /**
         * @brief OutputAmplitudeTargetRx3
         */
        uint32_t OutputAmplitudeTargetRx3 : 4;  /* bits 11:8 */
        /**
         * @brief OutputAmplitudeTargetRx4
         * @access RO Adv.
         */
        uint32_t OutputAmplitudeTargetRx4 : 4;  /* bits 15:12 */
        /**
         * @brief OutputAmplitudeTargetRx5
         */
        uint32_t OutputAmplitudeTargetRx5 : 4;  /* bits 19:16 */
        /**
         * @brief OutputAmplitudeTargetRx6
         * @access RO Adv.
         */
        uint32_t OutputAmplitudeTargetRx6 : 4;  /* bits 23:20 */
        /**
         * @brief OutputAmplitudeTargetRx7
         */
        uint32_t OutputAmplitudeTargetRx7 : 4;  /* bits 27:24 */
        /**
         * @brief OutputAmplitudeTargetRx8
         * @access RO Adv.
         */
        uint32_t OutputAmplitudeTargetRx8 : 4;  /* bits 31:28 */
        };
        uint32_t OutputAmplitudeTargetRx;
    };
        /**
         * @brief DPInitPendingLane1
         */
        /**
         * @brief DPInitPendingLane2
         */
        /**
         * @brief DPInitPendingLane3
         */
        /**
         * @brief DPInitPendingLane4
         */
        /**
         * @brief DPInitPendingLane5
         */
        /**
         * @brief DPInitPendingLane6
         */
        /**
         * @brief DPInitPendingLane7
         */
        /**
         * @brief DPInitPendingLane8
         * @details DPInitPendingLane<i> 0b: DPInit not pending 1b: DPInit not yet executed after successful 
         * ApplyDPInit,hence the Active Control Set content may deviate from the actual hardware configuration. Note: 
         * WhenSteppedConfigOnly=0, the DPInitPendingLane<i> bits are evaluated in DPSM exit condition equations, see 
         * section6.3.3.1.
         * @access RO Rqd.
         */
    union {
        struct {
            uint8_t DPInitPendingLane1 : 1;  /* r235.0 */
            uint8_t DPInitPendingLane2 : 1;  /* r235.1 */
            uint8_t DPInitPendingLane3 : 1;  /* r235.2 */
            uint8_t DPInitPendingLane4 : 1;  /* r235.3 */
            uint8_t DPInitPendingLane5 : 1;  /* r235.4 */
            uint8_t DPInitPendingLane6 : 1;  /* r235.5 */
            uint8_t DPInitPendingLane7 : 1;  /* r235.6 */
            uint8_t DPInitPendingLane8 : 1;  /* r235.7 */
        };
        uint8_t DPInitPendingLane;
    };
    uint8_t reserved_236[4];  /**< r236.. */
    /** @brief r240 per lane */
    struct __attribute__((packed)) {
        union {
            struct {
                /**
                 * @brief MediaLaneToFiberMappingTx
                 */
                uint8_t MediaLaneToFiberMappingTx : 4;
                /**
                 * @brief MediaLaneToWavelengthMappingTx
                 * @details MediaLaneToWavelengthMappingTx<i> Mapping of media lane <i> 0000: Mapping unknown or 
                 * undefined0001: Maps to media wavelength 1 0010: Maps to media wavelength 2 0011: Maps to media 
                 * wavelength3 0100: Maps to media wavelength 4 0101: Maps to media wavelength 5 0110: Maps to media 
                 * wavelength6 0111: Maps to media wavelength 7 1000: Maps to media wavelength 8 1001-1111: Reserved 
                 * MediaLaneToFiberMappingTx<i>Mapping of media lane <i> 0000: Mapping unknown or undefined 0001: Maps 
                 * tomedia fiber 1 or TR1 0010: Maps to media fiber 2 or RT1 0011: Maps to media fiber 3 or TR2 0100: 
                 * Mapsto media fiber 4 or RT2
                 * @access RO Cnd.
                 */
                uint8_t MediaLaneToWavelengthMappingTx : 4;
            };
            uint8_t rval;
        };
    } r240[8];
    /** @brief r248 per lane */
    struct __attribute__((packed)) {
        union {
            struct {
                /**
                 * @brief MediaLaneToFiberMappingRx
                 */
                uint8_t MediaLaneToFiberMappingRx : 4;
                /**
                 * @brief MediaLaneToWavelengthMappingRx
                 * @access RO Cnd.
                 */
                uint8_t MediaLaneToWavelengthMappingRx : 4;
            };
            uint8_t rval;
        };
    } r248[8];

} cmis_page_11h_t;

#if __STDC_VERSION__ >= 202311L
static_assert(sizeof(cmis_page_11h_t) == 128, "cmis_page_11h_t must be exactly 128 bytes");
#elif __STDC_VERSION__ >= 201112L
_Static_assert(sizeof(cmis_page_11h_t) == 128, "cmis_page_11h_t must be exactly 128 bytes");
#elif defined(__GNUC__) || defined(__clang__)
_Static_assert(sizeof(cmis_page_11h_t) == 128, "cmis_page_11h_t must be exactly 128 bytes");
#else
/* verify manually: sizeof(cmis_page_11h_t) must be 128 */
#endif

#endif  // __CMIS_PAGE_11H_H