/* Auto-generated by CMIS2C - CMIS Page 13h Register Map */
#ifndef __CMIS_PAGE_13H_H
#define __CMIS_PAGE_13H_H

#include <stdint.h>

/** @brief CMIS Page 13h Register Map (Bytes 128-255) */
typedef struct __attribute__((packed)) {

        /**
         * @brief MediaSideOutputLoopback
         */
        /**
         * @brief MediaSideInputLoopback
         */
        /**
         * @brief HostSideOutputLoopback
         */
        /**
         * @brief HostSideInputLoopback
         */
        /**
         * @brief PerLaneHostSideLoopbacks
         */
        /**
         * @brief PerLaneMediaSideLoopbacks
         */
        /**
         * @brief SimultaneousHostAndMediaSideLoopbacks
         * @details 0b: not supported 1b: supported
         */
    union {
        struct {
            uint8_t MediaSideOutputLoopback : 1;  /* r128.0 */
            uint8_t MediaSideInputLoopback : 1;  /* r128.1 */
            uint8_t HostSideOutputLoopback : 1;  /* r128.2 */
            uint8_t HostSideInputLoopback : 1;  /* r128.3 */
            uint8_t PerLaneHostSideLoopbacks : 1;  /* r128.4 */
            uint8_t PerLaneMediaSideLoopbacks : 1;  /* r128.5 */
            uint8_t SimultaneousHostAndMediaSideLoopbacks : 1;  /* r128.6 */
            uint8_t _pad_128_7 : 1;
        };
        uint8_t r128;
    };
        /**
         * @brief AutoRestartGatingSupported
         * @details 0b: AutoRestartGating control (13h:177.4) not supported 1b: AutoRestartGating control (13h:177.4) 
         * supported
         */
        /**
         * @brief PerLaneGatingTimersSupported
         * @details 0b: Only two global gating timers are available for all lanes on all Banks, one for Host Side 
         * Measurementsand one for Media Side Measurements. 1b: Per lane gating timers are supported in all Banks
         */
        /**
         * @brief PeriodicUpdatesSupported
         * @details Real-time statistics selectable by DiagnosticsSelector (14h:128) values 01h-06h are periodically 
         * updatedduring measurement 0b: no periodic update during measurement 1b: periodic update during measurement 
         * Note:The update rate of periodic update is selected by UpdatePeriodSelect (13h:177.0) Note: Single-shot 
         * measurements(un-gated non-periodic) can be started by enabling checkers and stopped by ResetErrorInformation 
         * (13h:177.5)
         */
        /**
         * @brief GatingResultsSupported
         * @details Gating result statistics selectable by DiagnosticsSelector (14h:128) values 11h-15h are 0b: Not 
         * supported1b: Supported
         */
        /**
         * @brief GatingSupport
         * @details Gating (measurement over a given time interval) is 00b: Not supported (host defined measurement 
         * time)01b: Supported with time accuracy <= 2 ms 10b: Supported with time accuracy <= 20 ms 11b: Supported 
         * withtime accuracy > 20 ms Note: The accuracy specifies the interval length error magnitude in the real-time 
         * timebase of the module. Interval length may vary, e.g. by task scheduling jitter in module firmware. Note: 
         * Thetotal bits counted and reported can be used as an accurate measure of the actual time interval length
         * @access RO Rqd.
         */
    union {
        struct {
            uint8_t _pad_129_0 : 2;
            uint8_t AutoRestartGatingSupported : 1;  /* r129.2 */
            uint8_t PerLaneGatingTimersSupported : 1;  /* r129.3 */
            uint8_t PeriodicUpdatesSupported : 1;  /* r129.4 */
            uint8_t GatingResultsSupported : 1;  /* r129.5 */
            uint8_t GatingSupport : 2;  /* r129.7-6 */
        };
        uint8_t r129;
    };
        /**
         * @brief BitErrorRatioResultsSupported
         * @details Indicates if DiagnosticsSelector value 01h is supported (See Table 8-127) 1b: Supported 0b: Not 
         * supported
         */
        /**
         * @brief BitsAndErrorsCountingSupported
         * @details Indicates if DiagnosticsSelector values 02h-05h are supported (Page 14h byte 128, Table 8-127) 1b: 
         * Supported0b: Not supported Some modules are unable to perform a 64-bit division to calculate and present 
         * BER.It is expected these types of module will present the BER as error counts and total bits elapsed for the 
         * errorcounts presented.
         */
        /**
         * @brief HostSideInputSNRMeasurement
         * @details Indicates if host side SNR measurement reported via Diagnostics Selection value 06h is supported 
         * (Byte14h:128, see Table 8-127) 1b: Supported 0b: Not supported
         */
        /**
         * @brief MediaSideInputSNRMeasurement
         * @details Indicates if media side SNR measurement reported via DiagnosticsSelector value 06h is supported 
         * (seeTable 8-127) 1b: Supported 0b: Not supported
         */
        /**
         * @brief HostSideFEC
         * @details 1b: Supported (PRBS error information available) 0b: Not supported
         */
        /**
         * @brief MediaSideFEC
         * @details 1b: Supported (PRBS error information available) 0b: Not supported
         * @access RO Rqd.
         */
    union {
        struct {
            uint8_t BitErrorRatioResultsSupported : 1;  /* r130.0 */
            uint8_t BitsAndErrorsCountingSupported : 1;  /* r130.1 */
            uint8_t _pad_130_2 : 2;
            uint8_t HostSideInputSNRMeasurement : 1;  /* r130.4 */
            uint8_t MediaSideInputSNRMeasurement : 1;  /* r130.5 */
            uint8_t HostSideFEC : 1;  /* r130.6 */
            uint8_t MediaSideFEC : 1;  /* r130.7 */
        };
        uint8_t r130;
    };
        /**
         * @brief PRBSCheckerHostSidePostFEC
         */
        /**
         * @brief PRBSCheckerHostSidePreFEC
         */
        /**
         * @brief PRBSGeneratorHostSidePostFEC
         */
        /**
         * @brief PRBSGeneratorHostSidePreFEC
         */
        /**
         * @brief PRBSCheckerMediaSidePostFEC
         */
        /**
         * @brief PRBSCheckerMediaSidePreFEC
         */
        /**
         * @brief PRBSGeneratorMediaSidePostFEC
         */
        /**
         * @brief PRBSGeneratorMediaSidePreFEC
         * @details 1b: Supported 0b: Not supported Note: see reference diagram in Figure 8-4
         * @access RO Rqd.
         */
    union {
        struct {
            uint8_t PRBSCheckerHostSidePostFEC : 1;  /* r131.0 */
            uint8_t PRBSCheckerHostSidePreFEC : 1;  /* r131.1 */
            uint8_t PRBSGeneratorHostSidePostFEC : 1;  /* r131.2 */
            uint8_t PRBSGeneratorHostSidePreFEC : 1;  /* r131.3 */
            uint8_t PRBSCheckerMediaSidePostFEC : 1;  /* r131.4 */
            uint8_t PRBSCheckerMediaSidePreFEC : 1;  /* r131.5 */
            uint8_t PRBSGeneratorMediaSidePostFEC : 1;  /* r131.6 */
            uint8_t PRBSGeneratorMediaSidePreFEC : 1;  /* r131.7 */
        };
        uint8_t r131;
    };
    /** @brief HostSideGeneratorSupportsPattern (uint16_t, 2 bytes) */
    union {
        struct __attribute__((packed)) {
        /**
         * @brief HostSideGeneratorSupportsPattern0
         */
        uint16_t HostSideGeneratorSupportsPattern0 : 1;  /* bits 0:0 */
        /**
         * @brief HostSideGeneratorSupportsPattern1
         */
        uint16_t HostSideGeneratorSupportsPattern1 : 1;  /* bits 1:1 */
        /**
         * @brief HostSideGeneratorSupportsPattern2
         */
        uint16_t HostSideGeneratorSupportsPattern2 : 1;  /* bits 2:2 */
        /**
         * @brief HostSideGeneratorSupportsPattern3
         */
        uint16_t HostSideGeneratorSupportsPattern3 : 1;  /* bits 3:3 */
        /**
         * @brief HostSideGeneratorSupportsPattern4
         */
        uint16_t HostSideGeneratorSupportsPattern4 : 1;  /* bits 4:4 */
        /**
         * @brief HostSideGeneratorSupportsPattern5
         */
        uint16_t HostSideGeneratorSupportsPattern5 : 1;  /* bits 5:5 */
        /**
         * @brief HostSideGeneratorSupportsPattern6
         */
        uint16_t HostSideGeneratorSupportsPattern6 : 1;  /* bits 6:6 */
        /**
         * @brief HostSideGeneratorSupportsPattern7
         * @details HostSideGeneratorSupportsPattern<i> Pattern with ID <i> (see Table 8-105) 1b: Supported 0b: Not 
         * supported(Little Endian)
         * @access RO Rqd.
         */
        uint16_t HostSideGeneratorSupportsPattern7 : 1;  /* bits 7:7 */
        /**
         * @brief HostSideGeneratorSupportsPattern8
         */
        uint16_t HostSideGeneratorSupportsPattern8 : 1;  /* bits 8:8 */
        /**
         * @brief HostSideGeneratorSupportsPattern9
         */
        uint16_t HostSideGeneratorSupportsPattern9 : 1;  /* bits 9:9 */
        /**
         * @brief HostSideGeneratorSupportsPattern10
         */
        uint16_t HostSideGeneratorSupportsPattern10 : 1;  /* bits 10:10 */
        /**
         * @brief HostSideGeneratorSupportsPattern11
         */
        uint16_t HostSideGeneratorSupportsPattern11 : 1;  /* bits 11:11 */
        /**
         * @brief HostSideGeneratorSupportsPattern12
         */
        uint16_t HostSideGeneratorSupportsPattern12 : 1;  /* bits 12:12 */
        /**
         * @brief HostSideGeneratorSupportsPattern13
         */
        uint16_t HostSideGeneratorSupportsPattern13 : 1;  /* bits 13:13 */
        /**
         * @brief HostSideGeneratorSupportsPattern14
         */
        uint16_t HostSideGeneratorSupportsPattern14 : 1;  /* bits 14:14 */
        /**
         * @brief HostSideGeneratorSupportsPattern15
         * @access RO Rqd.
         */
        uint16_t HostSideGeneratorSupportsPattern15 : 1;  /* bits 15:15 */
        };
        uint16_t HostSideGeneratorSupportsPattern;
    };
    /** @brief MediaSideGeneratorSupportsPattern (uint16_t, 2 bytes) */
    union {
        struct __attribute__((packed)) {
        /**
         * @brief MediaSideGeneratorSupportsPattern0
         */
        uint16_t MediaSideGeneratorSupportsPattern0 : 1;  /* bits 0:0 */
        /**
         * @brief MediaSideGeneratorSupportsPattern1
         */
        uint16_t MediaSideGeneratorSupportsPattern1 : 1;  /* bits 1:1 */
        /**
         * @brief MediaSideGeneratorSupportsPattern2
         */
        uint16_t MediaSideGeneratorSupportsPattern2 : 1;  /* bits 2:2 */
        /**
         * @brief MediaSideGeneratorSupportsPattern3
         */
        uint16_t MediaSideGeneratorSupportsPattern3 : 1;  /* bits 3:3 */
        /**
         * @brief MediaSideGeneratorSupportsPattern4
         */
        uint16_t MediaSideGeneratorSupportsPattern4 : 1;  /* bits 4:4 */
        /**
         * @brief MediaSideGeneratorSupportsPattern5
         */
        uint16_t MediaSideGeneratorSupportsPattern5 : 1;  /* bits 5:5 */
        /**
         * @brief MediaSideGeneratorSupportsPattern6
         */
        uint16_t MediaSideGeneratorSupportsPattern6 : 1;  /* bits 6:6 */
        /**
         * @brief MediaSideGeneratorSupportsPattern7
         * @details MediaSideGeneratorSupportsPattern<i> Pattern <i> (see Table 8-105 for Pattern IDs) 1b: Supported 
         * 0b:Not supported (Little Endian)
         * @access RO Rqd.
         */
        uint16_t MediaSideGeneratorSupportsPattern7 : 1;  /* bits 7:7 */
        /**
         * @brief MediaSideGeneratorSupportsPattern8
         */
        uint16_t MediaSideGeneratorSupportsPattern8 : 1;  /* bits 8:8 */
        /**
         * @brief MediaSideGeneratorSupportsPattern9
         */
        uint16_t MediaSideGeneratorSupportsPattern9 : 1;  /* bits 9:9 */
        /**
         * @brief MediaSideGeneratorSupportsPattern10
         */
        uint16_t MediaSideGeneratorSupportsPattern10 : 1;  /* bits 10:10 */
        /**
         * @brief MediaSideGeneratorSupportsPattern11
         */
        uint16_t MediaSideGeneratorSupportsPattern11 : 1;  /* bits 11:11 */
        /**
         * @brief MediaSideGeneratorSupportsPattern12
         */
        uint16_t MediaSideGeneratorSupportsPattern12 : 1;  /* bits 12:12 */
        /**
         * @brief MediaSideGeneratorSupportsPattern13
         */
        uint16_t MediaSideGeneratorSupportsPattern13 : 1;  /* bits 13:13 */
        /**
         * @brief MediaSideGeneratorSupportsPattern14
         */
        uint16_t MediaSideGeneratorSupportsPattern14 : 1;  /* bits 14:14 */
        /**
         * @brief MediaSideGeneratorSupportsPattern15
         * @access RO Rqd.
         */
        uint16_t MediaSideGeneratorSupportsPattern15 : 1;  /* bits 15:15 */
        };
        uint16_t MediaSideGeneratorSupportsPattern;
    };
    /** @brief HostSideCheckerSupportsPattern (uint16_t, 2 bytes) */
    union {
        struct __attribute__((packed)) {
        /**
         * @brief HostSideCheckerSupportsPattern0
         */
        uint16_t HostSideCheckerSupportsPattern0 : 1;  /* bits 0:0 */
        /**
         * @brief HostSideCheckerSupportsPattern1
         */
        uint16_t HostSideCheckerSupportsPattern1 : 1;  /* bits 1:1 */
        /**
         * @brief HostSideCheckerSupportsPattern2
         */
        uint16_t HostSideCheckerSupportsPattern2 : 1;  /* bits 2:2 */
        /**
         * @brief HostSideCheckerSupportsPattern3
         */
        uint16_t HostSideCheckerSupportsPattern3 : 1;  /* bits 3:3 */
        /**
         * @brief HostSideCheckerSupportsPattern4
         */
        uint16_t HostSideCheckerSupportsPattern4 : 1;  /* bits 4:4 */
        /**
         * @brief HostSideCheckerSupportsPattern5
         */
        uint16_t HostSideCheckerSupportsPattern5 : 1;  /* bits 5:5 */
        /**
         * @brief HostSideCheckerSupportsPattern6
         */
        uint16_t HostSideCheckerSupportsPattern6 : 1;  /* bits 6:6 */
        /**
         * @brief HostSideCheckerSupportsPattern7
         * @details HostSideCheckerSupportsPattern<i> Pattern <i> (see Table 8-105 for Pattern IDs) 1b: Supported 0b: 
         * Notsupported (Little Endian)
         * @access RO Rqd.
         */
        uint16_t HostSideCheckerSupportsPattern7 : 1;  /* bits 7:7 */
        /**
         * @brief HostSideCheckerSupportsPattern8
         */
        uint16_t HostSideCheckerSupportsPattern8 : 1;  /* bits 8:8 */
        /**
         * @brief HostSideCheckerSupportsPattern9
         */
        uint16_t HostSideCheckerSupportsPattern9 : 1;  /* bits 9:9 */
        /**
         * @brief HostSideCheckerSupportsPattern10
         */
        uint16_t HostSideCheckerSupportsPattern10 : 1;  /* bits 10:10 */
        /**
         * @brief HostSideCheckerSupportsPattern11
         */
        uint16_t HostSideCheckerSupportsPattern11 : 1;  /* bits 11:11 */
        /**
         * @brief HostSideCheckerSupportsPattern12
         */
        uint16_t HostSideCheckerSupportsPattern12 : 1;  /* bits 12:12 */
        /**
         * @brief HostSideCheckerSupportsPattern13
         */
        uint16_t HostSideCheckerSupportsPattern13 : 1;  /* bits 13:13 */
        /**
         * @brief HostSideCheckerSupportsPattern14
         */
        uint16_t HostSideCheckerSupportsPattern14 : 1;  /* bits 14:14 */
        /**
         * @brief HostSideCheckerSupportsPattern15
         * @access RO Rqd.
         */
        uint16_t HostSideCheckerSupportsPattern15 : 1;  /* bits 15:15 */
        };
        uint16_t HostSideCheckerSupportsPattern;
    };
    /** @brief MediaSideCheckerSupportsPattern (uint16_t, 2 bytes) */
    union {
        struct __attribute__((packed)) {
        /**
         * @brief MediaSideCheckerSupportsPattern0
         */
        uint16_t MediaSideCheckerSupportsPattern0 : 1;  /* bits 0:0 */
        /**
         * @brief MediaSideCheckerSupportsPattern1
         */
        uint16_t MediaSideCheckerSupportsPattern1 : 1;  /* bits 1:1 */
        /**
         * @brief MediaSideCheckerSupportsPattern2
         */
        uint16_t MediaSideCheckerSupportsPattern2 : 1;  /* bits 2:2 */
        /**
         * @brief MediaSideCheckerSupportsPattern3
         */
        uint16_t MediaSideCheckerSupportsPattern3 : 1;  /* bits 3:3 */
        /**
         * @brief MediaSideCheckerSupportsPattern4
         */
        uint16_t MediaSideCheckerSupportsPattern4 : 1;  /* bits 4:4 */
        /**
         * @brief MediaSideCheckerSupportsPattern5
         */
        uint16_t MediaSideCheckerSupportsPattern5 : 1;  /* bits 5:5 */
        /**
         * @brief MediaSideCheckerSupportsPattern6
         */
        uint16_t MediaSideCheckerSupportsPattern6 : 1;  /* bits 6:6 */
        /**
         * @brief MediaSideCheckerSupportsPattern7
         * @details MediaSideCheckerSupportsPattern<i> Pattern <i> (see Table 8-105 for Pattern IDs) 1b: Supported 0b: 
         * Notsupported (Little Endian)
         * @access RO Rqd.
         */
        uint16_t MediaSideCheckerSupportsPattern7 : 1;  /* bits 7:7 */
        /**
         * @brief MediaSideCheckerSupportsPattern8
         */
        uint16_t MediaSideCheckerSupportsPattern8 : 1;  /* bits 8:8 */
        /**
         * @brief MediaSideCheckerSupportsPattern9
         */
        uint16_t MediaSideCheckerSupportsPattern9 : 1;  /* bits 9:9 */
        /**
         * @brief MediaSideCheckerSupportsPattern10
         */
        uint16_t MediaSideCheckerSupportsPattern10 : 1;  /* bits 10:10 */
        /**
         * @brief MediaSideCheckerSupportsPattern11
         */
        uint16_t MediaSideCheckerSupportsPattern11 : 1;  /* bits 11:11 */
        /**
         * @brief MediaSideCheckerSupportsPattern12
         */
        uint16_t MediaSideCheckerSupportsPattern12 : 1;  /* bits 12:12 */
        /**
         * @brief MediaSideCheckerSupportsPattern13
         */
        uint16_t MediaSideCheckerSupportsPattern13 : 1;  /* bits 13:13 */
        /**
         * @brief MediaSideCheckerSupportsPattern14
         */
        uint16_t MediaSideCheckerSupportsPattern14 : 1;  /* bits 14:14 */
        /**
         * @brief MediaSideCheckerSupportsPattern15
         * @access RO Rqd.
         */
        uint16_t MediaSideCheckerSupportsPattern15 : 1;  /* bits 15:15 */
        };
        uint16_t MediaSideCheckerSupportsPattern;
    };
        /**
         * @brief UserPatternLengthSupported
         * @details U4 Maximum length Lof the user defined pattern, where the field value n encodes Las L=2(n+1), i.e. 
         * 0000b:2 bytes, …, 1111b: 32 bytes
         */
        /**
         * @brief ReferenceClockForPatternsSupported
         * @details Option to use reference clock for pattern generation 1b/0b: supported/not supported
         */
        /**
         * @brief RecoveredClockForGeneratorOptions
         * @details Options to use recovered clock for contra-directional pattern generator on the same module side 
         * 00b:not supported 01b: supported without loopback 10b: supported with loopback 11b: supported with and 
         * withoutloopback
         * @access RO Rqd.
         */
    union {
        struct {
            uint8_t UserPatternLengthSupported : 4;  /* r140.3-0 */
            uint8_t _pad_140_4 : 1;
            uint8_t ReferenceClockForPatternsSupported : 1;  /* r140.5 */
            uint8_t RecoveredClockForGeneratorOptions : 2;  /* r140.7-6 */
        };
        uint8_t r140;
    };
        /**
         * @brief HostSideGeneratorSupportsDataInvert
         * @details 0b/1b: Byte 13h:145 not supported/supported
         */
        /**
         * @brief HostSideGeneratorSupportsDataSwap
         * @details 0b/1b: Byte 13h:146 not supported/supported
         */
        /**
         * @brief HostSideCheckerSupportsDataInvert
         * @details 0b/1b: Byte 13h:161 not supported/supported
         */
        /**
         * @brief HostSideCheckerSupportsDataSwap
         * @details 0b/1b: Byte 13h:162 not supported/supported
         */
        /**
         * @brief MediaSideGeneratorSupportsDataInvert
         * @details 0b/1b: Byte 13h:153 not supported/supported
         */
        /**
         * @brief MediaSideGeneratorSupportsDataSwap
         * @details 0b/1b: Byte 13h:154 not supported/supported
         */
        /**
         * @brief MediaSideCheckerSupportsDataInvert
         * @details 0b/1b: Byte 13h:169 not supported/supported
         */
        /**
         * @brief MediaSideCheckerSupportsDataSwap
         * @details 0b/1b: Byte 13h:170 not supported/supported
         * @access RO Rqd.
         */
    union {
        struct {
            uint8_t HostSideGeneratorSupportsDataInvert : 1;  /* r141.0 */
            uint8_t HostSideGeneratorSupportsDataSwap : 1;  /* r141.1 */
            uint8_t HostSideCheckerSupportsDataInvert : 1;  /* r141.2 */
            uint8_t HostSideCheckerSupportsDataSwap : 1;  /* r141.3 */
            uint8_t MediaSideGeneratorSupportsDataInvert : 1;  /* r141.4 */
            uint8_t MediaSideGeneratorSupportsDataSwap : 1;  /* r141.5 */
            uint8_t MediaSideCheckerSupportsDataInvert : 1;  /* r141.6 */
            uint8_t MediaSideCheckerSupportsDataSwap : 1;  /* r141.7 */
        };
        uint8_t r141;
    };
        /**
         * @brief HostGeneratorSupportsPerLanePattern
         * @details Host side pattern selection for generator 0b: Lane 1 pattern 13h:148.3-0 is used for all lanes 1b: 
         * Perlane pattern selection in 13h:148-151
         */
        /**
         * @brief HostGeneratorSupportsPerLaneEnable
         * @details Host side pattern generator for lane i enabled in 13h:144 enables lane i (or all lanes of the Bank) 
         * 0b/1b:per lane enable not supported/supported
         */
        /**
         * @brief HostCheckerSupportsPerLanePattern
         * @details Host side pattern selection for checker 0b: Lane 1 pattern 13h:164.3-0 is used for all lanes 1b: 
         * Perlane pattern selection in 13h:164-167
         */
        /**
         * @brief HostCheckerSupportsPerLaneEnable
         * @details Host side pattern checker for lane i enabled in 13h:160 enables lane i (or all lanes of the Bank) 
         * 0b/1b:per lane enable not supported/supported
         */
        /**
         * @brief MediaGeneratorSupportsPerLanePattern
         * @details Media side pattern selection for generator 0b: Lane 1 pattern 13h:156.3-0 is used for all lanes 1b: 
         * Perlane pattern selection in 13h:156-159
         */
        /**
         * @brief MediaGeneratorSupportsPerLaneEnable
         * @details Media side pattern generator for lane i enabled in 13h:152 enables lane i (or all lanes of the 
         * Bank)0b/1b: per lane enable not supported/supported
         */
        /**
         * @brief MediaCheckerSupportsPerLanePattern
         * @details Media side pattern selection for checker 0b: Lane 1 pattern 13h:172.3-0 is used for all lanes 1b: 
         * Perlane pattern selection in 13h:172-175
         */
        /**
         * @brief MediaCheckerSupportsPerLaneEnable
         * @details Media side pattern checker for lane i enabled in 13h:168 enables lane i (or all lanes of the Bank) 
         * 0b/1b:per lane enable not supported/supported
         * @access RO Rqd.
         */
    union {
        struct {
            uint8_t HostGeneratorSupportsPerLanePattern : 1;  /* r142.0 */
            uint8_t HostGeneratorSupportsPerLaneEnable : 1;  /* r142.1 */
            uint8_t HostCheckerSupportsPerLanePattern : 1;  /* r142.2 */
            uint8_t HostCheckerSupportsPerLaneEnable : 1;  /* r142.3 */
            uint8_t MediaGeneratorSupportsPerLanePattern : 1;  /* r142.4 */
            uint8_t MediaGeneratorSupportsPerLaneEnable : 1;  /* r142.5 */
            uint8_t MediaCheckerSupportsPerLanePattern : 1;  /* r142.6 */
            uint8_t MediaCheckerSupportsPerLaneEnable : 1;  /* r142.7 */
        };
        uint8_t r142;
    };
    uint8_t reserved_143;  /**< r143 Reserved */
        /**
         * @brief HostSideGeneratorEnableLane1
         */
        /**
         * @brief HostSideGeneratorEnableLane2
         */
        /**
         * @brief HostSideGeneratorEnableLane3
         */
        /**
         * @brief HostSideGeneratorEnableLane4
         */
        /**
         * @brief HostSideGeneratorEnableLane5
         */
        /**
         * @brief HostSideGeneratorEnableLane6
         */
        /**
         * @brief HostSideGeneratorEnableLane7
         */
        /**
         * @brief HostSideGeneratorEnableLane8
         * @details 1b: Enable generator with configuration defined in Bytes 145-151 0b: Disable pattern generator 
         * Advertisement:13h:131.3-2
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t HostSideGeneratorEnableLane1 : 1;  /* r144.0 */
            uint8_t HostSideGeneratorEnableLane2 : 1;  /* r144.1 */
            uint8_t HostSideGeneratorEnableLane3 : 1;  /* r144.2 */
            uint8_t HostSideGeneratorEnableLane4 : 1;  /* r144.3 */
            uint8_t HostSideGeneratorEnableLane5 : 1;  /* r144.4 */
            uint8_t HostSideGeneratorEnableLane6 : 1;  /* r144.5 */
            uint8_t HostSideGeneratorEnableLane7 : 1;  /* r144.6 */
            uint8_t HostSideGeneratorEnableLane8 : 1;  /* r144.7 */
        };
        uint8_t HostSideGeneratorEnableLane;
    };
        /**
         * @brief HostSideGeneratorDataInvertLane1
         */
        /**
         * @brief HostSideGeneratorDataInvertLane2
         */
        /**
         * @brief HostSideGeneratorDataInvertLane3
         */
        /**
         * @brief HostSideGeneratorDataInvertLane4
         */
        /**
         * @brief HostSideGeneratorDataInvertLane5
         */
        /**
         * @brief HostSideGeneratorDataInvertLane6
         */
        /**
         * @brief HostSideGeneratorDataInvertLane7
         */
        /**
         * @brief HostSideGeneratorDataInvertLane8
         * @details 1b: Invert the selected pattern 0b: Do not invert the selected pattern Note: This control inverts 
         * thepattern; it does not swap the Pand Nsignals (see polarity controls in Table 8-69.)
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t HostSideGeneratorDataInvertLane1 : 1;  /* r145.0 */
            uint8_t HostSideGeneratorDataInvertLane2 : 1;  /* r145.1 */
            uint8_t HostSideGeneratorDataInvertLane3 : 1;  /* r145.2 */
            uint8_t HostSideGeneratorDataInvertLane4 : 1;  /* r145.3 */
            uint8_t HostSideGeneratorDataInvertLane5 : 1;  /* r145.4 */
            uint8_t HostSideGeneratorDataInvertLane6 : 1;  /* r145.5 */
            uint8_t HostSideGeneratorDataInvertLane7 : 1;  /* r145.6 */
            uint8_t HostSideGeneratorDataInvertLane8 : 1;  /* r145.7 */
        };
        uint8_t HostSideGeneratorDataInvertLane;
    };
        /**
         * @brief HostSideGeneratorSwapSymbolBitsLane1
         */
        /**
         * @brief HostSideGeneratorSwapSymbolBitsLane2
         */
        /**
         * @brief HostSideGeneratorSwapSymbolBitsLane3
         */
        /**
         * @brief HostSideGeneratorSwapSymbolBitsLane4
         */
        /**
         * @brief HostSideGeneratorSwapSymbolBitsLane5
         */
        /**
         * @brief HostSideGeneratorSwapSymbolBitsLane6
         */
        /**
         * @brief HostSideGeneratorSwapSymbolBitsLane7
         */
        /**
         * @brief HostSideGeneratorSwapSymbolBitsLane8
         * @details 1b: Swap MSB and LSB for PAM4 patterns 0b: Do not swap MSB and LSB
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t HostSideGeneratorSwapSymbolBitsLane1 : 1;  /* r146.0 */
            uint8_t HostSideGeneratorSwapSymbolBitsLane2 : 1;  /* r146.1 */
            uint8_t HostSideGeneratorSwapSymbolBitsLane3 : 1;  /* r146.2 */
            uint8_t HostSideGeneratorSwapSymbolBitsLane4 : 1;  /* r146.3 */
            uint8_t HostSideGeneratorSwapSymbolBitsLane5 : 1;  /* r146.4 */
            uint8_t HostSideGeneratorSwapSymbolBitsLane6 : 1;  /* r146.5 */
            uint8_t HostSideGeneratorSwapSymbolBitsLane7 : 1;  /* r146.6 */
            uint8_t HostSideGeneratorSwapSymbolBitsLane8 : 1;  /* r146.7 */
        };
        uint8_t HostSideGeneratorSwapSymbolBitsLane;
    };
        /**
         * @brief HostSideGeneratorPreFECEnableLane1
         */
        /**
         * @brief HostSideGeneratorPreFECEnableLane2
         */
        /**
         * @brief HostSideGeneratorPreFECEnableLane3
         */
        /**
         * @brief HostSideGeneratorPreFECEnableLane4
         */
        /**
         * @brief HostSideGeneratorPreFECEnableLane5
         */
        /**
         * @brief HostSideGeneratorPreFECEnableLane6
         */
        /**
         * @brief HostSideGeneratorPreFECEnableLane7
         */
        /**
         * @brief HostSideGeneratorPreFECEnableLane8
         * @details 1b: Encoded pattern: Generate the selected pattern at the input to the internal host side FEC 
         * encoder0b: Unencoded pattern: Generate the selected pattern at a location after the internal host side FEC 
         * encoderblock
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t HostSideGeneratorPreFECEnableLane1 : 1;  /* r147.0 */
            uint8_t HostSideGeneratorPreFECEnableLane2 : 1;  /* r147.1 */
            uint8_t HostSideGeneratorPreFECEnableLane3 : 1;  /* r147.2 */
            uint8_t HostSideGeneratorPreFECEnableLane4 : 1;  /* r147.3 */
            uint8_t HostSideGeneratorPreFECEnableLane5 : 1;  /* r147.4 */
            uint8_t HostSideGeneratorPreFECEnableLane6 : 1;  /* r147.5 */
            uint8_t HostSideGeneratorPreFECEnableLane7 : 1;  /* r147.6 */
            uint8_t HostSideGeneratorPreFECEnableLane8 : 1;  /* r147.7 */
        };
        uint8_t HostSideGeneratorPreFECEnableLane;
    };
    /** @brief HostSideGeneratorPatternSelectLane (uint32_t, 4 bytes) */
    union {
        struct __attribute__((packed)) {
        /**
         * @brief HostSideGeneratorPatternSelectLane1
         */
        uint32_t HostSideGeneratorPatternSelectLane1 : 4;  /* bits 3:0 */
        /**
         * @brief HostSideGeneratorPatternSelectLane2
         * @details Selected pattern to be generated on each lane. See Table 8-105 for pattern coding.
         * @access RW Adv.
         */
        uint32_t HostSideGeneratorPatternSelectLane2 : 4;  /* bits 7:4 */
        /**
         * @brief HostSideGeneratorPatternSelectLane3
         */
        uint32_t HostSideGeneratorPatternSelectLane3 : 4;  /* bits 11:8 */
        /**
         * @brief HostSideGeneratorPatternSelectLane4
         */
        uint32_t HostSideGeneratorPatternSelectLane4 : 4;  /* bits 15:12 */
        /**
         * @brief HostSideGeneratorPatternSelectLane5
         */
        uint32_t HostSideGeneratorPatternSelectLane5 : 4;  /* bits 19:16 */
        /**
         * @brief HostSideGeneratorPatternSelectLane6
         */
        uint32_t HostSideGeneratorPatternSelectLane6 : 4;  /* bits 23:20 */
        /**
         * @brief HostSideGeneratorPatternSelectLane7
         */
        uint32_t HostSideGeneratorPatternSelectLane7 : 4;  /* bits 27:24 */
        /**
         * @brief HostSideGeneratorPatternSelectLane8
         */
        uint32_t HostSideGeneratorPatternSelectLane8 : 4;  /* bits 31:28 */
        };
        uint32_t HostSideGeneratorPatternSelectLane;
    };
        /**
         * @brief MediaSideGeneratorEnableLane1
         */
        /**
         * @brief MediaSideGeneratorEnableLane2
         */
        /**
         * @brief MediaSideGeneratorEnableLane3
         */
        /**
         * @brief MediaSideGeneratorEnableLane4
         */
        /**
         * @brief MediaSideGeneratorEnableLane5
         */
        /**
         * @brief MediaSideGeneratorEnableLane6
         */
        /**
         * @brief MediaSideGeneratorEnableLane7
         */
        /**
         * @brief MediaSideGeneratorEnableLane8
         * @details 1b: Enable pattern generator with configuration defined in Bytes 153-159 0b: Disable pattern 
         * generatorAdvertisement: 13h:131.7-6
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t MediaSideGeneratorEnableLane1 : 1;  /* r152.0 */
            uint8_t MediaSideGeneratorEnableLane2 : 1;  /* r152.1 */
            uint8_t MediaSideGeneratorEnableLane3 : 1;  /* r152.2 */
            uint8_t MediaSideGeneratorEnableLane4 : 1;  /* r152.3 */
            uint8_t MediaSideGeneratorEnableLane5 : 1;  /* r152.4 */
            uint8_t MediaSideGeneratorEnableLane6 : 1;  /* r152.5 */
            uint8_t MediaSideGeneratorEnableLane7 : 1;  /* r152.6 */
            uint8_t MediaSideGeneratorEnableLane8 : 1;  /* r152.7 */
        };
        uint8_t MediaSideGeneratorEnableLane;
    };
        /**
         * @brief MediaSideGeneratorDataInvertLane1
         */
        /**
         * @brief MediaSideGeneratorDataInvertLane2
         */
        /**
         * @brief MediaSideGeneratorDataInvertLane3
         */
        /**
         * @brief MediaSideGeneratorDataInvertLane4
         */
        /**
         * @brief MediaSideGeneratorDataInvertLane5
         */
        /**
         * @brief MediaSideGeneratorDataInvertLane6
         */
        /**
         * @brief MediaSideGeneratorDataInvertLane7
         */
        /**
         * @brief MediaSideGeneratorDataInvertLane8
         * @details 1b: Invert the selected pattern 0b: Do not invert the selected pattern Note: This control inverts 
         * thepattern; it does not swap the Pand Nsignals (see polarity controls in Table 8-69)
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t MediaSideGeneratorDataInvertLane1 : 1;  /* r153.0 */
            uint8_t MediaSideGeneratorDataInvertLane2 : 1;  /* r153.1 */
            uint8_t MediaSideGeneratorDataInvertLane3 : 1;  /* r153.2 */
            uint8_t MediaSideGeneratorDataInvertLane4 : 1;  /* r153.3 */
            uint8_t MediaSideGeneratorDataInvertLane5 : 1;  /* r153.4 */
            uint8_t MediaSideGeneratorDataInvertLane6 : 1;  /* r153.5 */
            uint8_t MediaSideGeneratorDataInvertLane7 : 1;  /* r153.6 */
            uint8_t MediaSideGeneratorDataInvertLane8 : 1;  /* r153.7 */
        };
        uint8_t MediaSideGeneratorDataInvertLane;
    };
        /**
         * @brief MediaSideGeneratorSwapSymbolBitsLane1
         */
        /**
         * @brief MediaSideGeneratorSwapSymbolBitsLane2
         */
        /**
         * @brief MediaSideGeneratorSwapSymbolBitsLane3
         */
        /**
         * @brief MediaSideGeneratorSwapSymbolBitsLane4
         */
        /**
         * @brief MediaSideGeneratorSwapSymbolBitsLane5
         */
        /**
         * @brief MediaSideGeneratorSwapSymbolBitsLane6
         */
        /**
         * @brief MediaSideGeneratorSwapSymbolBitsLane7
         */
        /**
         * @brief MediaSideGeneratorSwapSymbolBitsLane8
         * @details 1b: Swap MSB and LSB for PAM4 patterns 0b: Do not swap MSB and LSB
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t MediaSideGeneratorSwapSymbolBitsLane1 : 1;  /* r154.0 */
            uint8_t MediaSideGeneratorSwapSymbolBitsLane2 : 1;  /* r154.1 */
            uint8_t MediaSideGeneratorSwapSymbolBitsLane3 : 1;  /* r154.2 */
            uint8_t MediaSideGeneratorSwapSymbolBitsLane4 : 1;  /* r154.3 */
            uint8_t MediaSideGeneratorSwapSymbolBitsLane5 : 1;  /* r154.4 */
            uint8_t MediaSideGeneratorSwapSymbolBitsLane6 : 1;  /* r154.5 */
            uint8_t MediaSideGeneratorSwapSymbolBitsLane7 : 1;  /* r154.6 */
            uint8_t MediaSideGeneratorSwapSymbolBitsLane8 : 1;  /* r154.7 */
        };
        uint8_t MediaSideGeneratorSwapSymbolBitsLane;
    };
        /**
         * @brief MediaSideGeneratorPreFECEnableLane1
         */
        /**
         * @brief MediaSideGeneratorPreFECEnableLane2
         */
        /**
         * @brief MediaSideGeneratorPreFECEnableLane3
         */
        /**
         * @brief MediaSideGeneratorPreFECEnableLane4
         */
        /**
         * @brief MediaSideGeneratorPreFECEnableLane5
         */
        /**
         * @brief MediaSideGeneratorPreFECEnableLane6
         */
        /**
         * @brief MediaSideGeneratorPreFECEnableLane7
         */
        /**
         * @brief MediaSideGeneratorPreFECEnableLane8
         * @details 1b: Encoded pattern: Generate the selected pattern at the input to the internal media side FEC 
         * encoder0b: Unencoded pattern: Generate the selected pattern at a location after the internal media side FEC 
         * encoderblock
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t MediaSideGeneratorPreFECEnableLane1 : 1;  /* r155.0 */
            uint8_t MediaSideGeneratorPreFECEnableLane2 : 1;  /* r155.1 */
            uint8_t MediaSideGeneratorPreFECEnableLane3 : 1;  /* r155.2 */
            uint8_t MediaSideGeneratorPreFECEnableLane4 : 1;  /* r155.3 */
            uint8_t MediaSideGeneratorPreFECEnableLane5 : 1;  /* r155.4 */
            uint8_t MediaSideGeneratorPreFECEnableLane6 : 1;  /* r155.5 */
            uint8_t MediaSideGeneratorPreFECEnableLane7 : 1;  /* r155.6 */
            uint8_t MediaSideGeneratorPreFECEnableLane8 : 1;  /* r155.7 */
        };
        uint8_t MediaSideGeneratorPreFECEnableLane;
    };
    /** @brief MediaSideGeneratorPatternSelectLane (uint32_t, 4 bytes) */
    union {
        struct __attribute__((packed)) {
        /**
         * @brief MediaSideGeneratorPatternSelectLane1
         */
        uint32_t MediaSideGeneratorPatternSelectLane1 : 4;  /* bits 3:0 */
        /**
         * @brief MediaSideGeneratorPatternSelectLane2
         * @details Selected pattern to be generated on each lane. See Table 8-105 for pattern coding.
         * @access RW Adv.
         */
        uint32_t MediaSideGeneratorPatternSelectLane2 : 4;  /* bits 7:4 */
        /**
         * @brief MediaSideGeneratorPatternSelectLane3
         */
        uint32_t MediaSideGeneratorPatternSelectLane3 : 4;  /* bits 11:8 */
        /**
         * @brief MediaSideGeneratorPatternSelectLane4
         */
        uint32_t MediaSideGeneratorPatternSelectLane4 : 4;  /* bits 15:12 */
        /**
         * @brief MediaSideGeneratorPatternSelectLane5
         */
        uint32_t MediaSideGeneratorPatternSelectLane5 : 4;  /* bits 19:16 */
        /**
         * @brief MediaSideGeneratorPatternSelectLane6
         */
        uint32_t MediaSideGeneratorPatternSelectLane6 : 4;  /* bits 23:20 */
        /**
         * @brief MediaSideGeneratorPatternSelectLane7
         */
        uint32_t MediaSideGeneratorPatternSelectLane7 : 4;  /* bits 27:24 */
        /**
         * @brief MediaSideGeneratorPatternSelectLane8
         */
        uint32_t MediaSideGeneratorPatternSelectLane8 : 4;  /* bits 31:28 */
        };
        uint32_t MediaSideGeneratorPatternSelectLane;
    };
        /**
         * @brief HostSideCheckerEnableLane1
         */
        /**
         * @brief HostSideCheckerEnableLane2
         */
        /**
         * @brief HostSideCheckerEnableLane3
         */
        /**
         * @brief HostSideCheckerEnableLane4
         */
        /**
         * @brief HostSideCheckerEnableLane5
         */
        /**
         * @brief HostSideCheckerEnableLane6
         */
        /**
         * @brief HostSideCheckerEnableLane7
         */
        /**
         * @brief HostSideCheckerEnableLane8
         * @details 1b: Enable pattern checker with configuration defined in Bytes 161-167 0b: Disable pattern checker 
         * Advertisement:13h:131.1-0
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t HostSideCheckerEnableLane1 : 1;  /* r160.0 */
            uint8_t HostSideCheckerEnableLane2 : 1;  /* r160.1 */
            uint8_t HostSideCheckerEnableLane3 : 1;  /* r160.2 */
            uint8_t HostSideCheckerEnableLane4 : 1;  /* r160.3 */
            uint8_t HostSideCheckerEnableLane5 : 1;  /* r160.4 */
            uint8_t HostSideCheckerEnableLane6 : 1;  /* r160.5 */
            uint8_t HostSideCheckerEnableLane7 : 1;  /* r160.6 */
            uint8_t HostSideCheckerEnableLane8 : 1;  /* r160.7 */
        };
        uint8_t HostSideCheckerEnableLane;
    };
        /**
         * @brief HostSideCheckerDataInvertLane1
         */
        /**
         * @brief HostSideCheckerDataInvertLane2
         */
        /**
         * @brief HostSideCheckerDataInvertLane3
         */
        /**
         * @brief HostSideCheckerDataInvertLane4
         */
        /**
         * @brief HostSideCheckerDataInvertLane5
         */
        /**
         * @brief HostSideCheckerDataInvertLane6
         */
        /**
         * @brief HostSideCheckerDataInvertLane7
         */
        /**
         * @brief HostSideCheckerDataInvertLane8
         * @details 1b: Invert the selected pattern 0b: Do not invert the selected pattern Note: This control inverts 
         * thepattern; it does not swap the Pand Nsignals (P/Nswap for input signals is not currently supported by this 
         * specification).
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t HostSideCheckerDataInvertLane1 : 1;  /* r161.0 */
            uint8_t HostSideCheckerDataInvertLane2 : 1;  /* r161.1 */
            uint8_t HostSideCheckerDataInvertLane3 : 1;  /* r161.2 */
            uint8_t HostSideCheckerDataInvertLane4 : 1;  /* r161.3 */
            uint8_t HostSideCheckerDataInvertLane5 : 1;  /* r161.4 */
            uint8_t HostSideCheckerDataInvertLane6 : 1;  /* r161.5 */
            uint8_t HostSideCheckerDataInvertLane7 : 1;  /* r161.6 */
            uint8_t HostSideCheckerDataInvertLane8 : 1;  /* r161.7 */
        };
        uint8_t HostSideCheckerDataInvertLane;
    };
        /**
         * @brief HostSideCheckerSwapSymbolBitsLane1
         */
        /**
         * @brief HostSideCheckerSwapSymbolBitsLane2
         */
        /**
         * @brief HostSideCheckerSwapSymbolBitsLane3
         */
        /**
         * @brief HostSideCheckerSwapSymbolBitsLane4
         */
        /**
         * @brief HostSideCheckerSwapSymbolBitsLane5
         */
        /**
         * @brief HostSideCheckerSwapSymbolBitsLane6
         */
        /**
         * @brief HostSideCheckerSwapSymbolBitsLane7
         */
        /**
         * @brief HostSideCheckerSwapSymbolBitsLane8
         * @details 1b: Swap MSB and LSB for PAM4 patterns 0b: Do not swap MSB and LSB
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t HostSideCheckerSwapSymbolBitsLane1 : 1;  /* r162.0 */
            uint8_t HostSideCheckerSwapSymbolBitsLane2 : 1;  /* r162.1 */
            uint8_t HostSideCheckerSwapSymbolBitsLane3 : 1;  /* r162.2 */
            uint8_t HostSideCheckerSwapSymbolBitsLane4 : 1;  /* r162.3 */
            uint8_t HostSideCheckerSwapSymbolBitsLane5 : 1;  /* r162.4 */
            uint8_t HostSideCheckerSwapSymbolBitsLane6 : 1;  /* r162.5 */
            uint8_t HostSideCheckerSwapSymbolBitsLane7 : 1;  /* r162.6 */
            uint8_t HostSideCheckerSwapSymbolBitsLane8 : 1;  /* r162.7 */
        };
        uint8_t HostSideCheckerSwapSymbolBitsLane;
    };
        /**
         * @brief HostSideCheckerPostFECEnableLane1
         */
        /**
         * @brief HostSideCheckerPostFECEnableLane2
         */
        /**
         * @brief HostSideCheckerPostFECEnableLane3
         */
        /**
         * @brief HostSideCheckerPostFECEnableLane4
         */
        /**
         * @brief HostSideCheckerPostFECEnableLane5
         */
        /**
         * @brief HostSideCheckerPostFECEnableLane6
         */
        /**
         * @brief HostSideCheckerPostFECEnableLane7
         */
        /**
         * @brief HostSideCheckerPostFECEnableLane8
         * @details 1b: Check the selected encoded pattern at the output from the internal FEC decoder 0b: Check the 
         * selectedunencoded pattern at the input to the internal FEC decoder block
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t HostSideCheckerPostFECEnableLane1 : 1;  /* r163.0 */
            uint8_t HostSideCheckerPostFECEnableLane2 : 1;  /* r163.1 */
            uint8_t HostSideCheckerPostFECEnableLane3 : 1;  /* r163.2 */
            uint8_t HostSideCheckerPostFECEnableLane4 : 1;  /* r163.3 */
            uint8_t HostSideCheckerPostFECEnableLane5 : 1;  /* r163.4 */
            uint8_t HostSideCheckerPostFECEnableLane6 : 1;  /* r163.5 */
            uint8_t HostSideCheckerPostFECEnableLane7 : 1;  /* r163.6 */
            uint8_t HostSideCheckerPostFECEnableLane8 : 1;  /* r163.7 */
        };
        uint8_t HostSideCheckerPostFECEnableLane;
    };
    /** @brief HostSideCheckerPatternSelectLane (uint32_t, 4 bytes) */
    union {
        struct __attribute__((packed)) {
        /**
         * @brief HostSideCheckerPatternSelectLane1
         */
        uint32_t HostSideCheckerPatternSelectLane1 : 4;  /* bits 3:0 */
        /**
         * @brief HostSideCheckerPatternSelectLane2
         * @details Selected pattern to be generated on each lane. See Table 8-105 for pattern coding.
         * @access RW Adv.
         */
        uint32_t HostSideCheckerPatternSelectLane2 : 4;  /* bits 7:4 */
        /**
         * @brief HostSideCheckerPatternSelectLane3
         */
        uint32_t HostSideCheckerPatternSelectLane3 : 4;  /* bits 11:8 */
        /**
         * @brief HostSideCheckerPatternSelectLane4
         */
        uint32_t HostSideCheckerPatternSelectLane4 : 4;  /* bits 15:12 */
        /**
         * @brief HostSideCheckerPatternSelectLane5
         */
        uint32_t HostSideCheckerPatternSelectLane5 : 4;  /* bits 19:16 */
        /**
         * @brief HostSideCheckerPatternSelectLane6
         */
        uint32_t HostSideCheckerPatternSelectLane6 : 4;  /* bits 23:20 */
        /**
         * @brief HostSideCheckerPatternSelectLane7
         */
        uint32_t HostSideCheckerPatternSelectLane7 : 4;  /* bits 27:24 */
        /**
         * @brief HostSideCheckerPatternSelectLane8
         */
        uint32_t HostSideCheckerPatternSelectLane8 : 4;  /* bits 31:28 */
        };
        uint32_t HostSideCheckerPatternSelectLane;
    };
        /**
         * @brief MediaSideCheckerEnableLane1
         */
        /**
         * @brief MediaSideCheckerEnableLane2
         */
        /**
         * @brief MediaSideCheckerEnableLane3
         */
        /**
         * @brief MediaSideCheckerEnableLane4
         */
        /**
         * @brief MediaSideCheckerEnableLane5
         */
        /**
         * @brief MediaSideCheckerEnableLane6
         */
        /**
         * @brief MediaSideCheckerEnableLane7
         */
        /**
         * @brief MediaSideCheckerEnableLane8
         * @details 1b: Enable pattern checker with configuration defined in Bytes 169-175 0b: Disable pattern checker 
         * Advertisement:13h:131.5-4
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t MediaSideCheckerEnableLane1 : 1;  /* r168.0 */
            uint8_t MediaSideCheckerEnableLane2 : 1;  /* r168.1 */
            uint8_t MediaSideCheckerEnableLane3 : 1;  /* r168.2 */
            uint8_t MediaSideCheckerEnableLane4 : 1;  /* r168.3 */
            uint8_t MediaSideCheckerEnableLane5 : 1;  /* r168.4 */
            uint8_t MediaSideCheckerEnableLane6 : 1;  /* r168.5 */
            uint8_t MediaSideCheckerEnableLane7 : 1;  /* r168.6 */
            uint8_t MediaSideCheckerEnableLane8 : 1;  /* r168.7 */
        };
        uint8_t MediaSideCheckerEnableLane;
    };
        /**
         * @brief MediaSideCheckerDataInvertLane1
         */
        /**
         * @brief MediaSideCheckerDataInvertLane2
         */
        /**
         * @brief MediaSideCheckerDataInvertLane3
         */
        /**
         * @brief MediaSideCheckerDataInvertLane4
         */
        /**
         * @brief MediaSideCheckerDataInvertLane5
         */
        /**
         * @brief MediaSideCheckerDataInvertLane6
         */
        /**
         * @brief MediaSideCheckerDataInvertLane7
         */
        /**
         * @brief MediaSideCheckerDataInvertLane8
         * @details 1b: Invert the selected pattern 0b: Do not invert the selected pattern Note: This control inverts 
         * thepattern; it does not swap the Pand Nsignals (P/Nswap for input signals is not currently supported by this 
         * specification).
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t MediaSideCheckerDataInvertLane1 : 1;  /* r169.0 */
            uint8_t MediaSideCheckerDataInvertLane2 : 1;  /* r169.1 */
            uint8_t MediaSideCheckerDataInvertLane3 : 1;  /* r169.2 */
            uint8_t MediaSideCheckerDataInvertLane4 : 1;  /* r169.3 */
            uint8_t MediaSideCheckerDataInvertLane5 : 1;  /* r169.4 */
            uint8_t MediaSideCheckerDataInvertLane6 : 1;  /* r169.5 */
            uint8_t MediaSideCheckerDataInvertLane7 : 1;  /* r169.6 */
            uint8_t MediaSideCheckerDataInvertLane8 : 1;  /* r169.7 */
        };
        uint8_t MediaSideCheckerDataInvertLane;
    };
        /**
         * @brief MediaSideCheckerSwapSymbolBitsLane1
         */
        /**
         * @brief MediaSideCheckerSwapSymbolBitsLane2
         */
        /**
         * @brief MediaSideCheckerSwapSymbolBitsLane3
         */
        /**
         * @brief MediaSideCheckerSwapSymbolBitsLane4
         */
        /**
         * @brief MediaSideCheckerSwapSymbolBitsLane5
         */
        /**
         * @brief MediaSideCheckerSwapSymbolBitsLane6
         */
        /**
         * @brief MediaSideCheckerSwapSymbolBitsLane7
         */
        /**
         * @brief MediaSideCheckerSwapSymbolBitsLane8
         * @details 1b: Swap MSB and LSB for PAM4 patterns 0b: Do not swap MSB and LSB
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t MediaSideCheckerSwapSymbolBitsLane1 : 1;  /* r170.0 */
            uint8_t MediaSideCheckerSwapSymbolBitsLane2 : 1;  /* r170.1 */
            uint8_t MediaSideCheckerSwapSymbolBitsLane3 : 1;  /* r170.2 */
            uint8_t MediaSideCheckerSwapSymbolBitsLane4 : 1;  /* r170.3 */
            uint8_t MediaSideCheckerSwapSymbolBitsLane5 : 1;  /* r170.4 */
            uint8_t MediaSideCheckerSwapSymbolBitsLane6 : 1;  /* r170.5 */
            uint8_t MediaSideCheckerSwapSymbolBitsLane7 : 1;  /* r170.6 */
            uint8_t MediaSideCheckerSwapSymbolBitsLane8 : 1;  /* r170.7 */
        };
        uint8_t MediaSideCheckerSwapSymbolBitsLane;
    };
        /**
         * @brief MediaSideCheckerPostFECEnableLane1
         */
        /**
         * @brief MediaSideCheckerPostFECEnableLane2
         */
        /**
         * @brief MediaSideCheckerPostFECEnableLane3
         */
        /**
         * @brief MediaSideCheckerPostFECEnableLane4
         */
        /**
         * @brief MediaSideCheckerPostFECEnableLane5
         */
        /**
         * @brief MediaSideCheckerPostFECEnableLane6
         */
        /**
         * @brief MediaSideCheckerPostFECEnableLane7
         */
        /**
         * @brief MediaSideCheckerPostFECEnableLane8
         * @details 1b: Check the selected encoded pattern at the output from the internal FEC decoder 0b: Check the 
         * selectedunencoded pattern at the input to the internal FEC decoder block
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t MediaSideCheckerPostFECEnableLane1 : 1;  /* r171.0 */
            uint8_t MediaSideCheckerPostFECEnableLane2 : 1;  /* r171.1 */
            uint8_t MediaSideCheckerPostFECEnableLane3 : 1;  /* r171.2 */
            uint8_t MediaSideCheckerPostFECEnableLane4 : 1;  /* r171.3 */
            uint8_t MediaSideCheckerPostFECEnableLane5 : 1;  /* r171.4 */
            uint8_t MediaSideCheckerPostFECEnableLane6 : 1;  /* r171.5 */
            uint8_t MediaSideCheckerPostFECEnableLane7 : 1;  /* r171.6 */
            uint8_t MediaSideCheckerPostFECEnableLane8 : 1;  /* r171.7 */
        };
        uint8_t MediaSideCheckerPostFECEnableLane;
    };
    /** @brief MediaSideCheckerPatternSelectLane (uint32_t, 4 bytes) */
    union {
        struct __attribute__((packed)) {
        /**
         * @brief MediaSideCheckerPatternSelectLane1
         */
        uint32_t MediaSideCheckerPatternSelectLane1 : 4;  /* bits 3:0 */
        /**
         * @brief MediaSideCheckerPatternSelectLane2
         * @details Selected pattern to be generated on each lane. See Table 8-105 for pattern coding.
         * @access RW Adv.
         */
        uint32_t MediaSideCheckerPatternSelectLane2 : 4;  /* bits 7:4 */
        /**
         * @brief MediaSideCheckerPatternSelectLane3
         */
        uint32_t MediaSideCheckerPatternSelectLane3 : 4;  /* bits 11:8 */
        /**
         * @brief MediaSideCheckerPatternSelectLane4
         */
        uint32_t MediaSideCheckerPatternSelectLane4 : 4;  /* bits 15:12 */
        /**
         * @brief MediaSideCheckerPatternSelectLane5
         */
        uint32_t MediaSideCheckerPatternSelectLane5 : 4;  /* bits 19:16 */
        /**
         * @brief MediaSideCheckerPatternSelectLane6
         */
        uint32_t MediaSideCheckerPatternSelectLane6 : 4;  /* bits 23:20 */
        /**
         * @brief MediaSideCheckerPatternSelectLane7
         */
        uint32_t MediaSideCheckerPatternSelectLane7 : 4;  /* bits 27:24 */
        /**
         * @brief MediaSideCheckerPatternSelectLane8
         */
        uint32_t MediaSideCheckerPatternSelectLane8 : 4;  /* bits 31:28 */
        };
        uint32_t MediaSideCheckerPatternSelectLane;
    };
        /**
         * @brief MediaPRBSGeneratorClockSource
         * @details Clock source for Media Side PRBS Pattern Generation: 0: All lanes use Internal Clock 1: All lanes 
         * useReference Clock i= 2-9: All lanes use Reference Clock Host Lane i-1 10-14: Reserved 15: Recovered clock 
         * perHost Lane or Data Path
         */
        /**
         * @brief HostPRBSGeneratorClockSource
         * @details Clock source for Host Side PRBS Pattern Generation: 0: All lanes use Internal Clock i=1-8: All 
         * lanesuse Reference Clock Media Lane i 9-14: Reserved 15: Recovered clock per Media Lane or Data Path
         * @access RW Opt.
         */
    union {
        struct {
            uint8_t MediaPRBSGeneratorClockSource : 4;  /* r176.3-0 */
            uint8_t HostPRBSGeneratorClockSource : 4;  /* r176.7-4 */
        };
        uint8_t r176;
    };
        /**
         * @brief UpdatePeriodSelect
         * @details Time between incremental updates to intermediate error counting results during a longer gating 
         * period0b: 1 sec update interval 1b: 5 sec update interval This period is relevant only if 
         * PeriodicUpdatesSupported(13h:129.4=1b) advertises that the module will update the BER or Error counters 
         * whilegating is in progress. Then two update rates at which the module will process the internal error 
         * countersand update the error counter fields in the Memory Map are possible. The host can then poll 
         * “real-time”error counts, up until the gating results are completed.
         */
        /**
         * @brief MeasurementTime
         * @details Measurement (gating) time for one complete result over a defined measurement period. 000b: ungated, 
         * countersaccrue indefinitely (infinite gate time 001b: 5 sec gate time 010b: 10 sec gate time 011b: 30 sec 
         * gatetime 100b: 60 sec gate time 101b: 120 sec gate time 110b: 300 sec gate time 111b: Custom
         */
        /**
         * @brief AutoRestartGating
         * @details 0b: When Gate Time expires, the module will set the Gate Complete Flag in Bytes 14h:134-135. The 
         * modulewill update the error counter result and stop error detection. 1b: When Gate Time expires, the module 
         * willset the Gate Complete Flag in Bytes 14h:134-135. The module will update the error counter results, then 
         * immediatelyclear internal error counters and restart the Gate Timer, while continuing to count errors. Note: 
         * WithAuto-restart the host must read the error counter results before the Gate Time expires to avoid the 
         * resultvalues to be overwritten with new results.
         */
        /**
         * @brief ResetErrorInformation
         * @details This bit has effects on error information, and on gating timers when the value changes. Effect on 
         * ErrorInformation 0b→1b: Freeze. Currently accumulating error statistics identified by DiagnosticsSelector 
         * 01hto 05h are frozen and, if supported, gated results identified by Selectors 11h-15h are updated with the 
         * frozencurrent error statistics. 1b→0b: Reset. Error statistics identified by Selectors 01h-05h are reset to 
         * 0,whereas results identified by Selectors 11h-15h are unaffected. Whenever a ResetErrorInformation operation 
         * onan individual lane or all lanes is triggered, it should always clear associated Error Information (both 
         * PRBSBER and Error Counters) in the Diagnostics Data memory at the same time. The effect of 
         * ResetErrorInformationdepends also on - PerLaneGatingTimersSupported (13h:129.3) - StartStopIsGlobal 
         * (13h:177.7)Effect on global gating timers (13h:129.3=0b)
         */
        /**
         * @brief StartStopIsGlobal
         * @details Bool StartStopIsGlobal controls whether writing a measurement Start/Stop control (see below for a 
         * list)on one Bank globally starts/stops measurements across all Banks as if the same control value change had 
         * occurredin all supported Banks synchronously (which is impossible): 0b: Astart/stop control change acts on 
         * currentBank 1b: Astart/stop control change acts on all Banks Start/Stop controls (instances) Locations 
         * ResetErrorInformation(4) (0-3:13h:177.5) HostSideCheckerEnable (32) (0-3:13h:160.0-7) MediaSideCheckerEnable 
         * (32)(0-3:13h:168.0-7) Note: The intended effect of StartStopIsGlobal is that starting or stopping error 
         * countingmeasurement in one supported Bank occurs on all affected lanes in all supported Banks synchronously. 
         * Note:The actually affected lanes depend on per Bank capabilities like *CheckerSupportsPerLaneEnable.
         * @access RW Opt.
         */
    union {
        struct {
            uint8_t UpdatePeriodSelect : 1;  /* r177.0 */
            uint8_t MeasurementTime : 3;  /* r177.3-1 */
            uint8_t AutoRestartGating : 1;  /* r177.4 */
            uint8_t ResetErrorInformation : 1;  /* r177.5 */
            uint8_t _pad_177_6 : 1;
            uint8_t StartStopIsGlobal : 1;  /* r177.7 */
        };
        uint8_t r177;
    };
        /**
         * @brief MediaPRBSCheckerClockSource
         * @details The clock source used for the Media PRBS Pattern Checker can be configured using this control 
         * register:0h: Recovered clocks from Media Lane/Data paths 1h: All lanes use Internal Clock 2h: All lanes use 
         * ReferenceClock 3h: Reserved.
         * @access RW
         */
        /**
         * @brief HostPRBSCheckerClockSource
         * @details The clock source used for the Host PRBS Pattern Checker can be configured using this control 
         * register:0h: Recovered clocks from Host Lane/Data paths 1h: All lanes use Internal Clock 2h: All lanes use 
         * ReferenceClock 3h: Reserved
         * @access RW
         */
    union {
        struct {
            uint8_t MediaPRBSCheckerClockSource : 2;  /* r178.1-0 */
            uint8_t HostPRBSCheckerClockSource : 2;  /* r178.3-2 */
            uint8_t _pad_178_4 : 4;
        };
        uint8_t r178;
    };
    uint8_t reserved_179;  /**< r179 Reserved */
        /**
         * @brief MediaSideOutputLoopbackEnableLane1
         */
        /**
         * @brief MediaSideOutputLoopbackEnableLane2
         */
        /**
         * @brief MediaSideOutputLoopbackEnableLane3
         */
        /**
         * @brief MediaSideOutputLoopbackEnableLane4
         */
        /**
         * @brief MediaSideOutputLoopbackEnableLane5
         */
        /**
         * @brief MediaSideOutputLoopbackEnableLane6
         */
        /**
         * @brief MediaSideOutputLoopbackEnableLane7
         */
        /**
         * @brief MediaSideOutputLoopbackEnableLane8
         * @details MediaSideOutputLoopbackEnableLane<i> 0b: normal non-loopback operation 1b: loopback enabled. If the 
         * Per-laneMedia Side Loopback Supported field=1, loopback control is per lane. Otherwise, if any loopback 
         * enablebit is set to 1, all Media side lanes are in output loopback. Advertisement: 13h:128.
         * @access RWW Adv.
         */
    union {
        struct {
            uint8_t MediaSideOutputLoopbackEnableLane1 : 1;  /* r180.0 */
            uint8_t MediaSideOutputLoopbackEnableLane2 : 1;  /* r180.1 */
            uint8_t MediaSideOutputLoopbackEnableLane3 : 1;  /* r180.2 */
            uint8_t MediaSideOutputLoopbackEnableLane4 : 1;  /* r180.3 */
            uint8_t MediaSideOutputLoopbackEnableLane5 : 1;  /* r180.4 */
            uint8_t MediaSideOutputLoopbackEnableLane6 : 1;  /* r180.5 */
            uint8_t MediaSideOutputLoopbackEnableLane7 : 1;  /* r180.6 */
            uint8_t MediaSideOutputLoopbackEnableLane8 : 1;  /* r180.7 */
        };
        uint8_t MediaSideOutputLoopbackEnableLane;
    };
        /**
         * @brief MediaSideInputLoopbackEnableLane1
         */
        /**
         * @brief MediaSideInputLoopbackEnableLane2
         */
        /**
         * @brief MediaSideInputLoopbackEnableLane3
         */
        /**
         * @brief MediaSideInputLoopbackEnableLane4
         */
        /**
         * @brief MediaSideInputLoopbackEnableLane5
         */
        /**
         * @brief MediaSideInputLoopbackEnableLane6
         */
        /**
         * @brief MediaSideInputLoopbackEnableLane7
         */
        /**
         * @brief MediaSideInputLoopbackEnableLane8
         * @details MediaSideInputLoopbackEnableLane<i> 0b: normal non-loopback operation 1b: loopback enabled. If the 
         * Per-laneMedia Side Loopback Supported field=1, loopback control is per lane. Otherwise, if any loopback 
         * enablebit is set to 1, all media side lanes are in input loopback. Advertisement: 13h:128.1
         * @access RWW Adv.
         */
    union {
        struct {
            uint8_t MediaSideInputLoopbackEnableLane1 : 1;  /* r181.0 */
            uint8_t MediaSideInputLoopbackEnableLane2 : 1;  /* r181.1 */
            uint8_t MediaSideInputLoopbackEnableLane3 : 1;  /* r181.2 */
            uint8_t MediaSideInputLoopbackEnableLane4 : 1;  /* r181.3 */
            uint8_t MediaSideInputLoopbackEnableLane5 : 1;  /* r181.4 */
            uint8_t MediaSideInputLoopbackEnableLane6 : 1;  /* r181.5 */
            uint8_t MediaSideInputLoopbackEnableLane7 : 1;  /* r181.6 */
            uint8_t MediaSideInputLoopbackEnableLane8 : 1;  /* r181.7 */
        };
        uint8_t MediaSideInputLoopbackEnableLane;
    };
        /**
         * @brief HostSideOutputLoopbackEnableLane1
         */
        /**
         * @brief HostSideOutputLoopbackEnableLane2
         */
        /**
         * @brief HostSideOutputLoopbackEnableLane3
         */
        /**
         * @brief HostSideOutputLoopbackEnableLane4
         */
        /**
         * @brief HostSideOutputLoopbackEnableLane5
         */
        /**
         * @brief HostSideOutputLoopbackEnableLane6
         */
        /**
         * @brief HostSideOutputLoopbackEnableLane7
         */
        /**
         * @brief HostSideOutputLoopbackEnableLane8
         * @details HostSideOutputLoopbackEnableLane<i> 0b: normal non-loopback operation 1b: loopback enabled. If the 
         * Per-laneHost Side Loopback Supported field=1, loopback control is per lane. Otherwise, if any loopback 
         * enablebit is set to 1, all host side lanes are in output loopback. Advertisement: 13h:128.2
         * @access RWW Adv.
         */
    union {
        struct {
            uint8_t HostSideOutputLoopbackEnableLane1 : 1;  /* r182.0 */
            uint8_t HostSideOutputLoopbackEnableLane2 : 1;  /* r182.1 */
            uint8_t HostSideOutputLoopbackEnableLane3 : 1;  /* r182.2 */
            uint8_t HostSideOutputLoopbackEnableLane4 : 1;  /* r182.3 */
            uint8_t HostSideOutputLoopbackEnableLane5 : 1;  /* r182.4 */
            uint8_t HostSideOutputLoopbackEnableLane6 : 1;  /* r182.5 */
            uint8_t HostSideOutputLoopbackEnableLane7 : 1;  /* r182.6 */
            uint8_t HostSideOutputLoopbackEnableLane8 : 1;  /* r182.7 */
        };
        uint8_t HostSideOutputLoopbackEnableLane;
    };
        /**
         * @brief HostSideInputLoopbackEnableLane1
         */
        /**
         * @brief HostSideInputLoopbackEnableLane2
         */
        /**
         * @brief HostSideInputLoopbackEnableLane3
         */
        /**
         * @brief HostSideInputLoopbackEnableLane4
         */
        /**
         * @brief HostSideInputLoopbackEnableLane5
         */
        /**
         * @brief HostSideInputLoopbackEnableLane6
         */
        /**
         * @brief HostSideInputLoopbackEnableLane7
         */
        /**
         * @brief HostSideInputLoopbackEnableLane8
         * @details HostSideInputLoopbackEnableLane<i> 0b: normal non-loopback operation 1b: loopback enabled. If the 
         * Per-laneHost Side Loopback Supported field=1, loopback control is per lane. Otherwise, if any loopback 
         * enablebit is set to 1, all Host side lanes are in input loopback. Advertisement: 13h:128.3
         * @access RWW Adv.
         */
    union {
        struct {
            uint8_t HostSideInputLoopbackEnableLane1 : 1;  /* r183.0 */
            uint8_t HostSideInputLoopbackEnableLane2 : 1;  /* r183.1 */
            uint8_t HostSideInputLoopbackEnableLane3 : 1;  /* r183.2 */
            uint8_t HostSideInputLoopbackEnableLane4 : 1;  /* r183.3 */
            uint8_t HostSideInputLoopbackEnableLane5 : 1;  /* r183.4 */
            uint8_t HostSideInputLoopbackEnableLane6 : 1;  /* r183.5 */
            uint8_t HostSideInputLoopbackEnableLane7 : 1;  /* r183.6 */
            uint8_t HostSideInputLoopbackEnableLane8 : 1;  /* r183.7 */
        };
        uint8_t HostSideInputLoopbackEnableLane;
    };
    /**
     * @brief HostScratchPad
     * @details HostScratchPad<i>, <i> = 0, …,7 These 8 bytes can be used by the host to store state in the module. The 
     * scratchpad clears in every firmware restart to its default zero values. It can therefore also be used by the 
     * hostto detect a module-initiated recovery reboot. Advertisement: 01h:251.7
     */
    uint8_t HostScratchPad[8];
    uint8_t reserved_192[14];  /**< r192.. */
        /**
         * @brief LossOfReferenceClockMask
         * @details Loss of reference clock Mask for the module
         * @access RW Opt.
         */
    union {
        struct {
            uint8_t _pad_206_0 : 7;
            uint8_t LossOfReferenceClockMask : 1;  /* r206.7 */
        };
        uint8_t LossOfReferenceClockMask_206;
    };
    uint8_t reserved_207;  /**< r207 Reserved */
        /**
         * @brief PatternCheckGatingCompleteMaskHostLane1
         */
        /**
         * @brief PatternCheckGatingCompleteMaskHostLane2
         */
        /**
         * @brief PatternCheckGatingCompleteMaskHostLane3
         */
        /**
         * @brief PatternCheckGatingCompleteMaskHostLane4
         */
        /**
         * @brief PatternCheckGatingCompleteMaskHostLane5
         */
        /**
         * @brief PatternCheckGatingCompleteMaskHostLane6
         */
        /**
         * @brief PatternCheckGatingCompleteMaskHostLane7
         */
        /**
         * @brief PatternCheckGatingCompleteMaskHostLane8
         * @details PatternCheckGatingCompleteMaskHost Lane<i> Per-host lane gating complete Mask. Default:1
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t PatternCheckGatingCompleteMaskHostLane1 : 1;  /* r208.0 */
            uint8_t PatternCheckGatingCompleteMaskHostLane2 : 1;  /* r208.1 */
            uint8_t PatternCheckGatingCompleteMaskHostLane3 : 1;  /* r208.2 */
            uint8_t PatternCheckGatingCompleteMaskHostLane4 : 1;  /* r208.3 */
            uint8_t PatternCheckGatingCompleteMaskHostLane5 : 1;  /* r208.4 */
            uint8_t PatternCheckGatingCompleteMaskHostLane6 : 1;  /* r208.5 */
            uint8_t PatternCheckGatingCompleteMaskHostLane7 : 1;  /* r208.6 */
            uint8_t PatternCheckGatingCompleteMaskHostLane8 : 1;  /* r208.7 */
        };
        uint8_t PatternCheckGatingCompleteMaskHostLane;
    };
        /**
         * @brief PatternCheckGatingCompleteMaskMediaLane1
         */
        /**
         * @brief PatternCheckGatingCompleteMaskMediaLane2
         */
        /**
         * @brief PatternCheckGatingCompleteMaskMediaLane3
         */
        /**
         * @brief PatternCheckGatingCompleteMaskMediaLane4
         */
        /**
         * @brief PatternCheckGatingCompleteMaskMediaLane5
         */
        /**
         * @brief PatternCheckGatingCompleteMaskMediaLane6
         */
        /**
         * @brief PatternCheckGatingCompleteMaskMediaLane7
         */
        /**
         * @brief PatternCheckGatingCompleteMaskMediaLane8
         * @details PatternCheckGatingCompleteMaskMed iaLane<i> Per-media lane gating complete Mask. Default:1
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t PatternCheckGatingCompleteMaskMediaLane1 : 1;  /* r209.0 */
            uint8_t PatternCheckGatingCompleteMaskMediaLane2 : 1;  /* r209.1 */
            uint8_t PatternCheckGatingCompleteMaskMediaLane3 : 1;  /* r209.2 */
            uint8_t PatternCheckGatingCompleteMaskMediaLane4 : 1;  /* r209.3 */
            uint8_t PatternCheckGatingCompleteMaskMediaLane5 : 1;  /* r209.4 */
            uint8_t PatternCheckGatingCompleteMaskMediaLane6 : 1;  /* r209.5 */
            uint8_t PatternCheckGatingCompleteMaskMediaLane7 : 1;  /* r209.6 */
            uint8_t PatternCheckGatingCompleteMaskMediaLane8 : 1;  /* r209.7 */
        };
        uint8_t PatternCheckGatingCompleteMaskMediaLane;
    };
        /**
         * @brief PatternGeneratorLOLMaskHostLane1
         */
        /**
         * @brief PatternGeneratorLOLMaskHostLane2
         */
        /**
         * @brief PatternGeneratorLOLMaskHostLane3
         */
        /**
         * @brief PatternGeneratorLOLMaskHostLane4
         */
        /**
         * @brief PatternGeneratorLOLMaskHostLane5
         */
        /**
         * @brief PatternGeneratorLOLMaskHostLane6
         */
        /**
         * @brief PatternGeneratorLOLMaskHostLane7
         */
        /**
         * @brief PatternGeneratorLOLMaskHostLane8
         * @details PatternGeneratorLOLMaskHostLane<i > Per-host lane pattern generator loss of lock Mask Default:1
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t PatternGeneratorLOLMaskHostLane1 : 1;  /* r210.0 */
            uint8_t PatternGeneratorLOLMaskHostLane2 : 1;  /* r210.1 */
            uint8_t PatternGeneratorLOLMaskHostLane3 : 1;  /* r210.2 */
            uint8_t PatternGeneratorLOLMaskHostLane4 : 1;  /* r210.3 */
            uint8_t PatternGeneratorLOLMaskHostLane5 : 1;  /* r210.4 */
            uint8_t PatternGeneratorLOLMaskHostLane6 : 1;  /* r210.5 */
            uint8_t PatternGeneratorLOLMaskHostLane7 : 1;  /* r210.6 */
            uint8_t PatternGeneratorLOLMaskHostLane8 : 1;  /* r210.7 */
        };
        uint8_t PatternGeneratorLOLMaskHostLane;
    };
        /**
         * @brief PatternGeneratorLOLMaskMediaLane1
         */
        /**
         * @brief PatternGeneratorLOLMaskMediaLane2
         */
        /**
         * @brief PatternGeneratorLOLMaskMediaLane3
         */
        /**
         * @brief PatternGeneratorLOLMaskMediaLane4
         */
        /**
         * @brief PatternGeneratorLOLMaskMediaLane5
         */
        /**
         * @brief PatternGeneratorLOLMaskMediaLane6
         */
        /**
         * @brief PatternGeneratorLOLMaskMediaLane7
         */
        /**
         * @brief PatternGeneratorLOLMaskMediaLane8
         * @details PatternGeneratorLOLMaskMediaLane< i> Per-media lane pattern generator loss of lock Mask Default:1
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t PatternGeneratorLOLMaskMediaLane1 : 1;  /* r211.0 */
            uint8_t PatternGeneratorLOLMaskMediaLane2 : 1;  /* r211.1 */
            uint8_t PatternGeneratorLOLMaskMediaLane3 : 1;  /* r211.2 */
            uint8_t PatternGeneratorLOLMaskMediaLane4 : 1;  /* r211.3 */
            uint8_t PatternGeneratorLOLMaskMediaLane5 : 1;  /* r211.4 */
            uint8_t PatternGeneratorLOLMaskMediaLane6 : 1;  /* r211.5 */
            uint8_t PatternGeneratorLOLMaskMediaLane7 : 1;  /* r211.6 */
            uint8_t PatternGeneratorLOLMaskMediaLane8 : 1;  /* r211.7 */
        };
        uint8_t PatternGeneratorLOLMaskMediaLane;
    };
        /**
         * @brief PatternCheckerLOLMaskHostLane1
         */
        /**
         * @brief PatternCheckerLOLMaskHostLane2
         */
        /**
         * @brief PatternCheckerLOLMaskHostLane3
         */
        /**
         * @brief PatternCheckerLOLMaskHostLane4
         */
        /**
         * @brief PatternCheckerLOLMaskHostLane5
         */
        /**
         * @brief PatternCheckerLOLMaskHostLane6
         */
        /**
         * @brief PatternCheckerLOLMaskHostLane7
         */
        /**
         * @brief PatternCheckerLOLMaskHostLane8
         * @details PatternCheckerLOLMaskHostLane<i> Per-host lane pattern checker loss of lock Mask Default:1
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t PatternCheckerLOLMaskHostLane1 : 1;  /* r212.0 */
            uint8_t PatternCheckerLOLMaskHostLane2 : 1;  /* r212.1 */
            uint8_t PatternCheckerLOLMaskHostLane3 : 1;  /* r212.2 */
            uint8_t PatternCheckerLOLMaskHostLane4 : 1;  /* r212.3 */
            uint8_t PatternCheckerLOLMaskHostLane5 : 1;  /* r212.4 */
            uint8_t PatternCheckerLOLMaskHostLane6 : 1;  /* r212.5 */
            uint8_t PatternCheckerLOLMaskHostLane7 : 1;  /* r212.6 */
            uint8_t PatternCheckerLOLMaskHostLane8 : 1;  /* r212.7 */
        };
        uint8_t PatternCheckerLOLMaskHostLane;
    };
        /**
         * @brief PatternCheckerLOLMaskMediaLane1
         */
        /**
         * @brief PatternCheckerLOLMaskMediaLane2
         */
        /**
         * @brief PatternCheckerLOLMaskMediaLane3
         */
        /**
         * @brief PatternCheckerLOLMaskMediaLane4
         */
        /**
         * @brief PatternCheckerLOLMaskMediaLane5
         */
        /**
         * @brief PatternCheckerLOLMaskMediaLane6
         */
        /**
         * @brief PatternCheckerLOLMaskMediaLane7
         */
        /**
         * @brief PatternCheckerLOLMaskMediaLane8
         * @details PatternCheckerLOLMaskMediaLane<i> Per-media lane pattern checker loss of lock Mask Default:1
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t PatternCheckerLOLMaskMediaLane1 : 1;  /* r213.0 */
            uint8_t PatternCheckerLOLMaskMediaLane2 : 1;  /* r213.1 */
            uint8_t PatternCheckerLOLMaskMediaLane3 : 1;  /* r213.2 */
            uint8_t PatternCheckerLOLMaskMediaLane4 : 1;  /* r213.3 */
            uint8_t PatternCheckerLOLMaskMediaLane5 : 1;  /* r213.4 */
            uint8_t PatternCheckerLOLMaskMediaLane6 : 1;  /* r213.5 */
            uint8_t PatternCheckerLOLMaskMediaLane7 : 1;  /* r213.6 */
            uint8_t PatternCheckerLOLMaskMediaLane8 : 1;  /* r213.7 */
        };
        uint8_t PatternCheckerLOLMaskMediaLane;
    };
    uint8_t reserved_214[10];  /**< r214.. */
    /**
     * @brief UserPattern
     * @details Host defined user pattern (32 Bytes)
     * @access RW Opt.
     */
    uint8_t UserPattern[32];  /* r224 */

} cmis_page_13h_t;

#if __STDC_VERSION__ >= 202311L
static_assert(sizeof(cmis_page_13h_t) == 128, "cmis_page_13h_t must be exactly 128 bytes");
#elif __STDC_VERSION__ >= 201112L
_Static_assert(sizeof(cmis_page_13h_t) == 128, "cmis_page_13h_t must be exactly 128 bytes");
#elif defined(__GNUC__) || defined(__clang__)
_Static_assert(sizeof(cmis_page_13h_t) == 128, "cmis_page_13h_t must be exactly 128 bytes");
#else
/* verify manually: sizeof(cmis_page_13h_t) must be 128 */
#endif

#endif  // __CMIS_PAGE_13H_H