/* Auto-generated by CMIS2C - CMIS Page 2Fh Register Map */
#ifndef __CMIS_PAGE_2FH_H
#define __CMIS_PAGE_2FH_H

#include <stdint.h>

/** @brief CMIS Page 2Fh Register Map (Bytes 128-255) */
typedef struct __attribute__((packed)) {

        /**
         * @brief VDMSupport
         * @details Advertisement 0: Group 1 (Page 20h, 24h, 28h, first ¼ of 2Ch, 2Dh) 1: Groups 1-2 (Page 20h-21h, 
         * 24h-25h,28h-29h, first ½ of 2Ch, 2Dh) 2: Groups 1-3 (Page 20h-22h, 24h-26h, 28h-2Ah, first ¾ of 2Ch, 2Dh) 3: 
         * Groups1-4 (Page 20h-23h, 24h-27h, 28h-2Bh, 2Ch, 2Dh)
         * @access RO
         */
        /**
         * @brief PowerSavingSupport
         * @details 1b: PowerSavingMode is supported
         * @access RO
         */
    union {
        struct {
            uint8_t VDMSupport : 2;  /* r128.1-0 */
            uint8_t PowerSavingSupport : 1;  /* r128.2 */
            uint8_t _pad_128_3 : 5;
        };
        uint8_t r128;
    };
    /**
     * @brief FineIntervalLength
     * @details U16 Length of fine interval (measurement time for one sample) used for internal BER/FERC monitoring, in 
     * unitsof 0.1 ms
     * @access RO
     */
    uint16_t FineIntervalLength;  /* r129 */
    uint8_t reserved_131[13];  /**< r131.. */
        /**
         * @brief PowerSavingMode
         * @details 0b: VDM monitoring functions are enabled (ON) 1b: VDM monitoring functions are disabled (OFF) for 
         * powersaving Advertisement: 2Fh:128.2 (PowerSavingSupport)
         * @access RW Adv.
         */
        /**
         * @brief FreezeRequest
         * @details When raised by the host, causes the module to freeze and hold all reported statistics reporting 
         * registers(minimum, maximum and average values) in Pages 24h-27h. When ceased by the host, releases the 
         * freezerequest, allowing the reported minimum, maximum and average values to update again. Multi-bank 
         * behavior:Freezing or unfreezing in one supported bank occurs in all supported banks synchronously, 
         * independentof whether BankBroadcastEnable is supported and enabled. Note. The module internally records new 
         * statisticswhile the reporting registers are frozen, so that no data is lost.
         * @access RW
         */
    union {
        struct {
            uint8_t _pad_144_0 : 6;
            uint8_t PowerSavingMode : 1;  /* r144.6 */
            uint8_t FreezeRequest : 1;  /* r144.7 */
        };
        uint8_t r144;
    };
        /**
         * @brief UnfreezeDone
         * @details Raised by the module when real-time updates of the reporting registers are performed again Ceased 
         * bythe module (within Ttime from when Freeze Request is VDMF ceased by the host). The UnfreezeDone status in 
         * anyof the supported banks reflects the completion of unfreezing across all supported banks. Until a first 
         * requestto unfreeze is served, the module reports 0b.
         * @access RO
         */
        /**
         * @brief FreezeDone
         * @details Raised by the module when it has finished freezing the reporting registers (such that the host can 
         * nowsafely read) and simultaneously restarted all supported statistics internally. Ceased by the module 
         * (withinTtime from when Freeze Request is VDMF raised by the host). The FreezeDone status in any of the 
         * supportedbanks reflects the completion of a FreezeRequest across all supported banks. Until a first 
         * FreezeRequestis served, the module reports 0b.
         * @access RO
         */
    union {
        struct {
            uint8_t _pad_145_0 : 6;
            uint8_t UnfreezeDone : 1;  /* r145.6 */
            uint8_t FreezeDone : 1;  /* r145.7 */
        };
        uint8_t r145;
    };
    uint8_t reserved_146[110];  /**< r146.. */

} cmis_page_2fh_t;

#if __STDC_VERSION__ >= 202311L
static_assert(sizeof(cmis_page_2fh_t) == 128, "cmis_page_2fh_t must be exactly 128 bytes");
#elif __STDC_VERSION__ >= 201112L
_Static_assert(sizeof(cmis_page_2fh_t) == 128, "cmis_page_2fh_t must be exactly 128 bytes");
#elif defined(__GNUC__) || defined(__clang__)
_Static_assert(sizeof(cmis_page_2fh_t) == 128, "cmis_page_2fh_t must be exactly 128 bytes");
#else
/* verify manually: sizeof(cmis_page_2fh_t) must be 128 */
#endif

#endif  // __CMIS_PAGE_2FH_H