/* Auto-generated by CMIS2C - CMIS Page 14h Register Map */
#ifndef __CMIS_PAGE_14H_H
#define __CMIS_PAGE_14H_H

#include <stdint.h>

/** @brief CMIS Page 14h Register Map (Bytes 128-255) */
typedef struct __attribute__((packed)) {

    /**
     * @brief DiagnosticsSelector
     * @details Selects the content of Diagnostics Data (Bytes 192-255)
     */
    uint8_t DiagnosticsSelector;  /* r128 */
    uint8_t reserved_129;  /**< r129 Reserved */
    /**
     * @brief Custom1
     * @details Custom byte 1
     */
    uint8_t Custom1;  /* r130 */
    /**
     * @brief Custom2
     * @details Custom byte 2
     */
    uint8_t Custom2;  /* r131 */
        /**
         * @brief LossOfReferenceClockFlag
         * @details Latched loss of reference clock Flag.
         * @access RO/COR Opt.
         */
    union {
        struct {
            uint8_t _pad_132_0 : 7;
            uint8_t LossOfReferenceClockFlag : 1;  /* r132.7 */
        };
        uint8_t LossOfReferenceClockFlag_132;
    };
    uint8_t reserved_133;  /**< r133 Reserved */
        /**
         * @brief PatternCheckGatingCompleteFlagHostLane1
         */
        /**
         * @brief PatternCheckGatingCompleteFlagHostLane2
         */
        /**
         * @brief PatternCheckGatingCompleteFlagHostLane3
         */
        /**
         * @brief PatternCheckGatingCompleteFlagHostLane4
         */
        /**
         * @brief PatternCheckGatingCompleteFlagHostLane5
         */
        /**
         * @brief PatternCheckGatingCompleteFlagHostLane6
         */
        /**
         * @brief PatternCheckGatingCompleteFlagHostLane7
         */
        /**
         * @brief PatternCheckGatingCompleteFlagHostLane8
         * @details PatternCheckGatingCompleteFlag HostLane<i> Latched per-host lane gating complete Flag. When gating 
         * iscomplete, this bit will be set.
         * @access RO/COR Adv.
         */
    union {
        struct {
            uint8_t PatternCheckGatingCompleteFlagHostLane1 : 1;  /* r134.0 */
            uint8_t PatternCheckGatingCompleteFlagHostLane2 : 1;  /* r134.1 */
            uint8_t PatternCheckGatingCompleteFlagHostLane3 : 1;  /* r134.2 */
            uint8_t PatternCheckGatingCompleteFlagHostLane4 : 1;  /* r134.3 */
            uint8_t PatternCheckGatingCompleteFlagHostLane5 : 1;  /* r134.4 */
            uint8_t PatternCheckGatingCompleteFlagHostLane6 : 1;  /* r134.5 */
            uint8_t PatternCheckGatingCompleteFlagHostLane7 : 1;  /* r134.6 */
            uint8_t PatternCheckGatingCompleteFlagHostLane8 : 1;  /* r134.7 */
        };
        uint8_t PatternCheckGatingCompleteFlagHostLane;
    };
        /**
         * @brief PatternCheckGatingCompleteFlagMediaLane1
         */
        /**
         * @brief PatternCheckGatingCompleteFlagMediaLane2
         */
        /**
         * @brief PatternCheckGatingCompleteFlagMediaLane3
         */
        /**
         * @brief PatternCheckGatingCompleteFlagMediaLane4
         */
        /**
         * @brief PatternCheckGatingCompleteFlagMediaLane5
         */
        /**
         * @brief PatternCheckGatingCompleteFlagMediaLane6
         */
        /**
         * @brief PatternCheckGatingCompleteFlagMediaLane7
         */
        /**
         * @brief PatternCheckGatingCompleteFlagMediaLane8
         * @details PatternCheckGatingCompleteFlag MediaLane<i> Latched per-media lane gating complete Flag. When 
         * gatingis complete, this bit will be set.
         * @access RO/COR Adv.
         */
    union {
        struct {
            uint8_t PatternCheckGatingCompleteFlagMediaLane1 : 1;  /* r135.0 */
            uint8_t PatternCheckGatingCompleteFlagMediaLane2 : 1;  /* r135.1 */
            uint8_t PatternCheckGatingCompleteFlagMediaLane3 : 1;  /* r135.2 */
            uint8_t PatternCheckGatingCompleteFlagMediaLane4 : 1;  /* r135.3 */
            uint8_t PatternCheckGatingCompleteFlagMediaLane5 : 1;  /* r135.4 */
            uint8_t PatternCheckGatingCompleteFlagMediaLane6 : 1;  /* r135.5 */
            uint8_t PatternCheckGatingCompleteFlagMediaLane7 : 1;  /* r135.6 */
            uint8_t PatternCheckGatingCompleteFlagMediaLane8 : 1;  /* r135.7 */
        };
        uint8_t PatternCheckGatingCompleteFlagMediaLane;
    };
        /**
         * @brief PatternGeneratorLOLFlagHostLane1
         */
        /**
         * @brief PatternGeneratorLOLFlagHostLane2
         */
        /**
         * @brief PatternGeneratorLOLFlagHostLane3
         */
        /**
         * @brief PatternGeneratorLOLFlagHostLane4
         */
        /**
         * @brief PatternGeneratorLOLFlagHostLane5
         */
        /**
         * @brief PatternGeneratorLOLFlagHostLane6
         */
        /**
         * @brief PatternGeneratorLOLFlagHostLane7
         */
        /**
         * @brief PatternGeneratorLOLFlagHostLane8
         * @details PatternGeneratorLOLFlagHostLan e<i> Latched per-host lane pattern generator failure Flag. Indicates 
         * thatthe generator has failed to generate a valid pattern.
         * @access RO/COR Adv.
         */
    union {
        struct {
            uint8_t PatternGeneratorLOLFlagHostLane1 : 1;  /* r136.0 */
            uint8_t PatternGeneratorLOLFlagHostLane2 : 1;  /* r136.1 */
            uint8_t PatternGeneratorLOLFlagHostLane3 : 1;  /* r136.2 */
            uint8_t PatternGeneratorLOLFlagHostLane4 : 1;  /* r136.3 */
            uint8_t PatternGeneratorLOLFlagHostLane5 : 1;  /* r136.4 */
            uint8_t PatternGeneratorLOLFlagHostLane6 : 1;  /* r136.5 */
            uint8_t PatternGeneratorLOLFlagHostLane7 : 1;  /* r136.6 */
            uint8_t PatternGeneratorLOLFlagHostLane8 : 1;  /* r136.7 */
        };
        uint8_t PatternGeneratorLOLFlagHostLane;
    };
        /**
         * @brief PatternGeneratorLOLFlagMediaLane1
         */
        /**
         * @brief PatternGeneratorLOLFlagMediaLane2
         */
        /**
         * @brief PatternGeneratorLOLFlagMediaLane3
         */
        /**
         * @brief PatternGeneratorLOLFlagMediaLane4
         */
        /**
         * @brief PatternGeneratorLOLFlagMediaLane5
         */
        /**
         * @brief PatternGeneratorLOLFlagMediaLane6
         */
        /**
         * @brief PatternGeneratorLOLFlagMediaLane7
         */
        /**
         * @brief PatternGeneratorLOLFlagMediaLane8
         * @details PatternGeneratorLOLFlagMediaLa ne<i> Latched per-media lane pattern generator failure Flag. 
         * Indicatesthat the generator has failed to generate a valid pattern.
         * @access RO/COR Adv.
         */
    union {
        struct {
            uint8_t PatternGeneratorLOLFlagMediaLane1 : 1;  /* r137.0 */
            uint8_t PatternGeneratorLOLFlagMediaLane2 : 1;  /* r137.1 */
            uint8_t PatternGeneratorLOLFlagMediaLane3 : 1;  /* r137.2 */
            uint8_t PatternGeneratorLOLFlagMediaLane4 : 1;  /* r137.3 */
            uint8_t PatternGeneratorLOLFlagMediaLane5 : 1;  /* r137.4 */
            uint8_t PatternGeneratorLOLFlagMediaLane6 : 1;  /* r137.5 */
            uint8_t PatternGeneratorLOLFlagMediaLane7 : 1;  /* r137.6 */
            uint8_t PatternGeneratorLOLFlagMediaLane8 : 1;  /* r137.7 */
        };
        uint8_t PatternGeneratorLOLFlagMediaLane;
    };
        /**
         * @brief PatternCheckerLOLFlagHostLane1
         */
        /**
         * @brief PatternCheckerLOLFlagHostLane2
         */
        /**
         * @brief PatternCheckerLOLFlagHostLane3
         */
        /**
         * @brief PatternCheckerLOLFlagHostLane4
         */
        /**
         * @brief PatternCheckerLOLFlagHostLane5
         */
        /**
         * @brief PatternCheckerLOLFlagHostLane6
         */
        /**
         * @brief PatternCheckerLOLFlagHostLane7
         */
        /**
         * @brief PatternCheckerLOLFlagHostLane8
         * @details PatternCheckerLOLFlagHostLane< i> Latched per-host lane pattern checker loss of pattern lock Flag.
         * @access RO/COR Adv.
         */
    union {
        struct {
            uint8_t PatternCheckerLOLFlagHostLane1 : 1;  /* r138.0 */
            uint8_t PatternCheckerLOLFlagHostLane2 : 1;  /* r138.1 */
            uint8_t PatternCheckerLOLFlagHostLane3 : 1;  /* r138.2 */
            uint8_t PatternCheckerLOLFlagHostLane4 : 1;  /* r138.3 */
            uint8_t PatternCheckerLOLFlagHostLane5 : 1;  /* r138.4 */
            uint8_t PatternCheckerLOLFlagHostLane6 : 1;  /* r138.5 */
            uint8_t PatternCheckerLOLFlagHostLane7 : 1;  /* r138.6 */
            uint8_t PatternCheckerLOLFlagHostLane8 : 1;  /* r138.7 */
        };
        uint8_t PatternCheckerLOLFlagHostLane;
    };
        /**
         * @brief PatternCheckerLOLFlagMediaLane1
         */
        /**
         * @brief PatternCheckerLOLFlagMediaLane2
         */
        /**
         * @brief PatternCheckerLOLFlagMediaLane3
         */
        /**
         * @brief PatternCheckerLOLFlagMediaLane4
         */
        /**
         * @brief PatternCheckerLOLFlagMediaLane5
         */
        /**
         * @brief PatternCheckerLOLFlagMediaLane6
         */
        /**
         * @brief PatternCheckerLOLFlagMediaLane7
         */
        /**
         * @brief PatternCheckerLOLFlagMediaLane8
         * @details PatternCheckerLOLFlagMediaLane <i> Latched per-media lane pattern checker loss of pattern lock 
         * Flag.
         * @access RO/COR Adv.
         */
    union {
        struct {
            uint8_t PatternCheckerLOLFlagMediaLane1 : 1;  /* r139.0 */
            uint8_t PatternCheckerLOLFlagMediaLane2 : 1;  /* r139.1 */
            uint8_t PatternCheckerLOLFlagMediaLane3 : 1;  /* r139.2 */
            uint8_t PatternCheckerLOLFlagMediaLane4 : 1;  /* r139.3 */
            uint8_t PatternCheckerLOLFlagMediaLane5 : 1;  /* r139.4 */
            uint8_t PatternCheckerLOLFlagMediaLane6 : 1;  /* r139.5 */
            uint8_t PatternCheckerLOLFlagMediaLane7 : 1;  /* r139.6 */
            uint8_t PatternCheckerLOLFlagMediaLane8 : 1;  /* r139.7 */
        };
        uint8_t PatternCheckerLOLFlagMediaLane;
    };
    uint8_t reserved_140[10];  /**< r140.. */
    uint8_t reserved_150[42];  /**< r150.. */
    /**
     * @brief DiagnosticsData
     * @details Diagnostics Data selected by Diagnostics Selector (a host visible set of Error Information Registers)
     */
    uint8_t DiagnosticsData[64];  /* r192 */

} cmis_page_14h_t;

#if __STDC_VERSION__ >= 202311L
static_assert(sizeof(cmis_page_14h_t) == 128, "cmis_page_14h_t must be exactly 128 bytes");
#elif __STDC_VERSION__ >= 201112L
_Static_assert(sizeof(cmis_page_14h_t) == 128, "cmis_page_14h_t must be exactly 128 bytes");
#elif defined(__GNUC__) || defined(__clang__)
_Static_assert(sizeof(cmis_page_14h_t) == 128, "cmis_page_14h_t must be exactly 128 bytes");
#else
/* verify manually: sizeof(cmis_page_14h_t) must be 128 */
#endif

#endif  // __CMIS_PAGE_14H_H