/* Auto-generated by CMIS2C - CMIS Page 02h Register Map */
#ifndef __CMIS_PAGE_02H_H
#define __CMIS_PAGE_02H_H

#include <stdint.h>

/** @brief CMIS Page 02h Register Map (Bytes 128-255) */
typedef struct __attribute__((packed)) {

    /**
     * @brief TempMonHighAlarmThreshold
     * @details S16 Thresholds for internal temperature monitor: 1/256 degree Celsius increments
     * @access RO Cnd.
     */
    uint16_t TempMonHighAlarmThreshold;  /* r128 */
    /**
     * @brief TempMonLowAlarmThreshold
     */
    uint16_t TempMonLowAlarmThreshold;  /* r130 */
    /**
     * @brief TempMonHighWarningThreshold
     */
    uint16_t TempMonHighWarningThreshold;  /* r132 */
    /**
     * @brief TempMonLowWarningThreshold
     */
    uint16_t TempMonLowWarningThreshold;  /* r134 */
    /**
     * @brief VccMonHighAlarmThreshold
     * @details U16 Thresholds for internal 3.3 volt input supply voltage monitor: 100 µV increments
     * @access RO Cnd.
     */
    uint16_t VccMonHighAlarmThreshold;  /* r136 */
    /**
     * @brief VccMonLowAlarmThreshold
     */
    uint16_t VccMonLowAlarmThreshold;  /* r138 */
    /**
     * @brief VccMonHighWarningThreshold
     */
    uint16_t VccMonHighWarningThreshold;  /* r140 */
    /**
     * @brief VccMonLowWarningThreshold
     */
    uint16_t VccMonLowWarningThreshold;  /* r142 */
    /**
     * @brief Aux1MonHighAlarmThreshold
     * @details S16 Thresholds for TEC Current monitor or custom Aux 1 monitor TEC Current: 100/32767% increments of 
     * maximumTEC current +32767 (100%) – Max Heating -32767 (-100%) – Max Cooling
     * @access RO Cnd.
     */
    uint16_t Aux1MonHighAlarmThreshold;  /* r144 */
    /**
     * @brief Aux1MonLowAlarmThreshold
     */
    uint16_t Aux1MonLowAlarmThreshold;  /* r146 */
    /**
     * @brief Aux1MonHighWarningThreshold
     */
    uint16_t Aux1MonHighWarningThreshold;  /* r148 */
    /**
     * @brief Aux1MonLowWarningThreshold
     */
    uint16_t Aux1MonLowWarningThreshold;  /* r150 */
    /**
     * @brief Aux2MonHighAlarmThreshold
     * @details S16 Thresholds for TEC Current or Laser Temperature monitor TEC Current: 100/32767% increments of 
     * maximumTEC current +32767 (100%) – Max Heating -32767 (-100%) – Max Cooling Laser Temperature: 1/256 degree 
     * Celsiusincrements
     * @access RO Cnd.
     */
    uint16_t Aux2MonHighAlarmThreshold;  /* r152 */
    /**
     * @brief Aux2MonLowAlarmThreshold
     */
    uint16_t Aux2MonLowAlarmThreshold;  /* r154 */
    /**
     * @brief Aux2MonHighWarningThreshold
     */
    uint16_t Aux2MonHighWarningThreshold;  /* r156 */
    /**
     * @brief Aux2MonLowWarningThreshold
     */
    uint16_t Aux2MonLowWarningThreshold;  /* r158 */
    /**
     * @brief Aux3MonHighAlarmThreshold
     * @details S16 Thresholds for Laser Temperature or additional supply voltage monitor Laser Temperature: 1/256 
     * degreeCelsius increments
     * @access RO Cnd.
     */
    uint16_t Aux3MonHighAlarmThreshold;  /* r160 */
    /**
     * @brief Aux3MonLowAlarmThreshold
     */
    uint16_t Aux3MonLowAlarmThreshold;  /* r162 */
    /**
     * @brief Aux3MonHighWarningThreshold
     */
    uint16_t Aux3MonHighWarningThreshold;  /* r164 */
    /**
     * @brief Aux3MonLowWarningThreshold
     */
    uint16_t Aux3MonLowWarningThreshold;  /* r166 */
    /**
     * @brief CustomMonHighAlarmThreshold
     * @details S16 or U16 Custom monitor
     * @access RO Cnd.
     */
    uint16_t CustomMonHighAlarmThreshold;  /* r168 */
    /**
     * @brief CustomMonLowAlarmThreshold
     */
    uint16_t CustomMonLowAlarmThreshold;  /* r170 */
    /**
     * @brief CustomMonHighWarningThreshold
     */
    uint16_t CustomMonHighWarningThreshold;  /* r172 */
    /**
     * @brief CustomMonLowWarningThreshold
     */
    uint16_t CustomMonLowWarningThreshold;  /* r174 */
    /**
     * @brief OpticalPowerTxHighAlarmThreshold
     * @details U16 Thresholds for Tx optical power monitor: in 0.1 uW increments Total measurement range of 0 to 
     * 6.5535mW (~-40 dBm to +8.2 dBm for non-zero values)
     * @access RO Cnd.
     */
    uint16_t OpticalPowerTxHighAlarmThreshold;  /* r176 */
    /**
     * @brief OpticalPowerTxLowAlarmThreshold
     */
    uint16_t OpticalPowerTxLowAlarmThreshold;  /* r178 */
    /**
     * @brief OpticalPowerTxHighWarningThreshold
     */
    uint16_t OpticalPowerTxHighWarningThreshold;  /* r180 */
    /**
     * @brief OpticalPowerTxLowWarningThreshold
     */
    uint16_t OpticalPowerTxLowWarningThreshold;  /* r182 */
    /**
     * @brief LaserBiasCurrentHighAlarmThreshold
     * @details U16 Thresholds for Tx laser bias monitor: 2 uA increments, times the multiplier encoded in 01h:160.4-3 
     * (seeTable 8-52)
     * @access RO Cnd.
     */
    uint16_t LaserBiasCurrentHighAlarmThreshold;  /* r184 */
    /**
     * @brief LaserBiasCurrentLowAlarmThreshold
     */
    uint16_t LaserBiasCurrentLowAlarmThreshold;  /* r186 */
    /**
     * @brief LaserBiasCurrentHighWarningThreshold
     */
    uint16_t LaserBiasCurrentHighWarningThreshold;  /* r188 */
    /**
     * @brief LaserBiasCurrentLowWarningThreshold
     */
    uint16_t LaserBiasCurrentLowWarningThreshold;  /* r190 */
    /**
     * @brief OpticalPowerRxHighAlarmThreshold
     * @details U16 Thresholds for Rx optical power monitor: 0.1 uW increments Total measurement range of 0 to 6.5535 
     * mW(~-40 dBm to +8.2 dBm for non-zero values)
     * @access RO Cnd.
     */
    uint16_t OpticalPowerRxHighAlarmThreshold;  /* r192 */
    /**
     * @brief OpticalPowerRxLowAlarmThreshold
     */
    uint16_t OpticalPowerRxLowAlarmThreshold;  /* r194 */
    /**
     * @brief OpticalPowerRxHighWarningThreshold
     */
    uint16_t OpticalPowerRxHighWarningThreshold;  /* r196 */
    /**
     * @brief OpticalPowerRxLowWarningThreshold
     */
    uint16_t OpticalPowerRxLowWarningThreshold;  /* r198 */
    uint8_t reserved_200[55];  /**< r200.. */
    /**
     * @brief PageChecksum
     * @details Covers bytes 128-254
     */
    uint8_t PageChecksum;  /* r255 */

} cmis_page_02h_t;

#if __STDC_VERSION__ >= 202311L
static_assert(sizeof(cmis_page_02h_t) == 128, "cmis_page_02h_t must be exactly 128 bytes");
#elif __STDC_VERSION__ >= 201112L
_Static_assert(sizeof(cmis_page_02h_t) == 128, "cmis_page_02h_t must be exactly 128 bytes");
#elif defined(__GNUC__) || defined(__clang__)
_Static_assert(sizeof(cmis_page_02h_t) == 128, "cmis_page_02h_t must be exactly 128 bytes");
#else
/* verify manually: sizeof(cmis_page_02h_t) must be 128 */
#endif

#endif  // __CMIS_PAGE_02H_H