/* Auto-generated by CMIS2C - CMIS Page 12h Register Map */
#ifndef __CMIS_PAGE_12H_H
#define __CMIS_PAGE_12H_H

#include <stdint.h>

/** @brief CMIS Page 12h Register Map (Bytes 128-255) */
typedef struct __attribute__((packed)) {

    /** @brief GridSpacing per lane */
    struct __attribute__((packed)) {
        union {
            struct {
                /**
                 * @brief FineTuningEnableTx
                 * @details Fine-tuning enabled lane 1
                 */
                uint8_t FineTuningEnableTx : 1;
                    uint8_t _pad_128_1 : 3;
                /**
                 * @brief GridSpacingTx
                 * @details Grid spacing for media lane lane 1
                 */
                uint8_t GridSpacingTx : 4;
            };
            uint8_t rval;
        };
    } GridSpacing[8];
    /**
     * @brief ChannelOffsetNumber
     * @details Channel offset number lane 1
     */
    uint16_t ChannelOffsetNumber[8];
    /**
     * @brief FineTuningOffset
     * @details Fine tuning offset lane 1
     */
    uint16_t FineTuningOffset[8];
    /**
     * @brief LaserFrequency
     * @details Laser frequency lane 1
     */
    uint32_t LaserFrequency[8];
    /**
     * @brief TargetOutputPower
     * @details Target output power lane 1
     */
    uint16_t TargetOutputPower[8];
    uint8_t reserved_216[6];  /**< r216.. */
    /** @brief StatusIndicator per lane */
    struct __attribute__((packed)) {
        union {
            struct {
                /**
                 * @brief WavelengthUnlockStatusTx
                 * @details Bool: Unlocked status indication for laser wavelength on media lane, 0b/1b: Wavelength 
                 * locked/unlockedlane 1
                 */
                uint8_t WavelengthUnlockStatusTx : 1;
                /**
                 * @brief TuningInProgressTx
                 * @details 0b/1b: Tuning not in progress/in progress lane 1
                 */
                uint8_t TuningInProgressTx : 1;
                    uint8_t _pad_222_2 : 6;
            };
            uint8_t rval;
        };
    } StatusIndicator[8];
    /**
     * @brief FlagSummary
     * @details one Bit per media lane
     */
    uint8_t FlagSummary;  /* r230 */
    /** @brief Flag per lane */
    struct __attribute__((packed)) {
        union {
            struct {
                /**
                 * @brief TuningCompleteFlagTx
                 * @details Latched Flag set after tuning has completed lane 1
                 */
                uint8_t TuningCompleteFlagTx : 1;
                /**
                 * @brief WavelengthUnlockedFlagTx
                 * @details Latched Flag indicating an unlocked wavelength condition lane 1
                 */
                uint8_t WavelengthUnlockedFlagTx : 1;
                /**
                 * @brief InvalidChannelNumberFlagTx
                 * @details Latched Flag indicating an invalid channel number was selected lane 1
                 */
                uint8_t InvalidChannelNumberFlagTx : 1;
                /**
                 * @brief TuningNotAcceptedFlagTx
                 * @details Latched Flag indicating a failed tuning operation: module temporarily unable to serve a 
                 * tuningrequest lane 1
                 */
                uint8_t TuningNotAcceptedFlagTx : 1;
                /**
                 * @brief FineTuningOutOfRangeFlagTx
                 * @details Latched Flag indicating a fine-tuning value outside the allowed range was given lane 1
                 */
                uint8_t FineTuningOutOfRangeFlagTx : 1;
                /**
                 * @brief TargetOutputPowerOORFlagTx
                 * @details Latched Flag indicating a target output power value outside the allowed range was entered 
                 * lane1
                 */
                uint8_t TargetOutputPowerOORFlagTx : 1;
                    uint8_t _pad_231_6 : 2;
            };
            uint8_t rval;
        };
    } Flag[8];
    /** @brief Mask per lane */
    struct __attribute__((packed)) {
        union {
            struct {
                /**
                 * @brief TuningCompleteMaskTx
                 * @details Mask for TuningCompleteFlagTx lane 1
                 */
                uint8_t TuningCompleteMaskTx : 1;
                /**
                 * @brief WavelengthUnlockedMaskTx
                 * @details Mask for WavelengthUnlockedFlagTx lane 1
                 */
                uint8_t WavelengthUnlockedMaskTx : 1;
                /**
                 * @brief InvalidChannelMaskTx
                 * @details Mask for InvalidChannelNumberFlagTx lane 1
                 */
                uint8_t InvalidChannelMaskTx : 1;
                /**
                 * @brief TuningNotAcceptedMaskTx
                 * @details Mask for TuningNotAcceptedFlagTx lane 1
                 */
                uint8_t TuningNotAcceptedMaskTx : 1;
                /**
                 * @brief FineTuningOutOfRangeMaskTx
                 * @details Mask for FineTuningOutOfRangeFlagTx lane 1
                 */
                uint8_t FineTuningOutOfRangeMaskTx : 1;
                /**
                 * @brief TargetOutputPowerOORMaskTx
                 * @details Mask for TargetOutputPowerOORFlagTx lane 1
                 */
                uint8_t TargetOutputPowerOORMaskTx : 1;
                    uint8_t _pad_239_6 : 2;
            };
            uint8_t rval;
        };
    } Mask[8];
    uint8_t reserved_247[9];  /**< r247.. */

} cmis_page_12h_t;

#if __STDC_VERSION__ >= 202311L
static_assert(sizeof(cmis_page_12h_t) == 128, "cmis_page_12h_t must be exactly 128 bytes");
#elif __STDC_VERSION__ >= 201112L
_Static_assert(sizeof(cmis_page_12h_t) == 128, "cmis_page_12h_t must be exactly 128 bytes");
#elif defined(__GNUC__) || defined(__clang__)
_Static_assert(sizeof(cmis_page_12h_t) == 128, "cmis_page_12h_t must be exactly 128 bytes");
#else
/* verify manually: sizeof(cmis_page_12h_t) must be 128 */
#endif

#endif  // __CMIS_PAGE_12H_H