/* Auto-generated by CMIS2C - CMIS Page 10h Register Map */
#ifndef __CMIS_PAGE_10H_H
#define __CMIS_PAGE_10H_H

#include <stdint.h>

/** @brief CMIS Page 10h Register Map (Bytes 128-255) */
typedef struct __attribute__((packed)) {

        /**
         * @brief DPDeinitLane1
         */
        /**
         * @brief DPDeinitLane2
         */
        /**
         * @brief DPDeinitLane3
         */
        /**
         * @brief DPDeinitLane4
         */
        /**
         * @brief DPDeinitLane5
         */
        /**
         * @brief DPDeinitLane6
         */
        /**
         * @brief DPDeinitLane7
         */
        /**
         * @brief DPDeinitLane8
         * @details DPDeinitLane<i> Data Path initialization control for host lane <i> 0b: Initialize the Data Path 
         * associatedwith host lane 1b: Deinitialize the Data Path associated with host lane All lanes of a Data Path 
         * musthave the same value Note: These bits represent static requests, not trigger events
         * @access RW Rqd.
         */
    union {
        struct {
            uint8_t DPDeinitLane1 : 1;  /* r128.0 */
            uint8_t DPDeinitLane2 : 1;  /* r128.1 */
            uint8_t DPDeinitLane3 : 1;  /* r128.2 */
            uint8_t DPDeinitLane4 : 1;  /* r128.3 */
            uint8_t DPDeinitLane5 : 1;  /* r128.4 */
            uint8_t DPDeinitLane6 : 1;  /* r128.5 */
            uint8_t DPDeinitLane7 : 1;  /* r128.6 */
            uint8_t DPDeinitLane8 : 1;  /* r128.7 */
        };
        uint8_t DPDeinitLane;
    };
        /**
         * @brief InputPolarityFlipTx1
         */
        /**
         * @brief InputPolarityFlipTx2
         */
        /**
         * @brief InputPolarityFlipTx3
         */
        /**
         * @brief InputPolarityFlipTx4
         */
        /**
         * @brief InputPolarityFlipTx5
         */
        /**
         * @brief InputPolarityFlipTx6
         */
        /**
         * @brief InputPolarityFlipTx7
         */
        /**
         * @brief InputPolarityFlipTx8
         * @details InputPolarityFlipTx<i> 0b: No Tx input polarity flip for lane <i> 1b: Tx input polarity flip for 
         * lane<i> Advertisement: 01h:155.0
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t InputPolarityFlipTx1 : 1;  /* r129.0 */
            uint8_t InputPolarityFlipTx2 : 1;  /* r129.1 */
            uint8_t InputPolarityFlipTx3 : 1;  /* r129.2 */
            uint8_t InputPolarityFlipTx4 : 1;  /* r129.3 */
            uint8_t InputPolarityFlipTx5 : 1;  /* r129.4 */
            uint8_t InputPolarityFlipTx6 : 1;  /* r129.5 */
            uint8_t InputPolarityFlipTx7 : 1;  /* r129.6 */
            uint8_t InputPolarityFlipTx8 : 1;  /* r129.7 */
        };
        uint8_t InputPolarityFlipTx;
    };
        /**
         * @brief OutputDisableTx1
         */
        /**
         * @brief OutputDisableTx2
         */
        /**
         * @brief OutputDisableTx3
         */
        /**
         * @brief OutputDisableTx4
         */
        /**
         * @brief OutputDisableTx5
         */
        /**
         * @brief OutputDisableTx6
         */
        /**
         * @brief OutputDisableTx7
         */
        /**
         * @brief OutputDisableTx8
         * @details OutputDisableTx<i> 0b: Tx output enabled for media lane <i> 1b: Tx output disabled for media lane 
         * <i>Advertisement: 01h:155.1
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t OutputDisableTx1 : 1;  /* r130.0 */
            uint8_t OutputDisableTx2 : 1;  /* r130.1 */
            uint8_t OutputDisableTx3 : 1;  /* r130.2 */
            uint8_t OutputDisableTx4 : 1;  /* r130.3 */
            uint8_t OutputDisableTx5 : 1;  /* r130.4 */
            uint8_t OutputDisableTx6 : 1;  /* r130.5 */
            uint8_t OutputDisableTx7 : 1;  /* r130.6 */
            uint8_t OutputDisableTx8 : 1;  /* r130.7 */
        };
        uint8_t OutputDisableTx;
    };
        /**
         * @brief AutoSquelchDisableTx1
         */
        /**
         * @brief AutoSquelchDisableTx2
         */
        /**
         * @brief AutoSquelchDisableTx3
         */
        /**
         * @brief AutoSquelchDisableTx4
         * @details 1b: Automatic Tx output squelching control disabled for media lane<i> Advertisement: 01h:155.2
         */
        /**
         * @brief AutoSquelchDisableTx5
         */
        /**
         * @brief AutoSquelchDisableTx6
         */
        /**
         * @brief AutoSquelchDisableTx7
         */
        /**
         * @brief AutoSquelchDisableTx8
         * @details AutoSquelchDisableTx<i> 0b: Automatic Tx output squelching control enabled for media lane <i>
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t AutoSquelchDisableTx1 : 1;  /* r131.0 */
            uint8_t AutoSquelchDisableTx2 : 1;  /* r131.1 */
            uint8_t AutoSquelchDisableTx3 : 1;  /* r131.2 */
            uint8_t AutoSquelchDisableTx4 : 1;  /* r131.3 */
            uint8_t AutoSquelchDisableTx5 : 1;  /* r131.4 */
            uint8_t AutoSquelchDisableTx6 : 1;  /* r131.5 */
            uint8_t AutoSquelchDisableTx7 : 1;  /* r131.6 */
            uint8_t AutoSquelchDisableTx8 : 1;  /* r131.7 */
        };
        uint8_t AutoSquelchDisableTx;
    };
        /**
         * @brief OutputSquelchForceTx1
         */
        /**
         * @brief OutputSquelchForceTx2
         */
        /**
         * @brief OutputSquelchForceTx3
         */
        /**
         * @brief OutputSquelchForceTx4
         */
        /**
         * @brief OutputSquelchForceTx5
         */
        /**
         * @brief OutputSquelchForceTx6
         */
        /**
         * @brief OutputSquelchForceTx7
         */
        /**
         * @brief OutputSquelchForceTx8
         * @details OutputSquelchForceTx<i> 0b: No impact on Tx output for media lane <i> 1b: Tx output squelched for 
         * medialane <i> Advertisement: 01h:155.3
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t OutputSquelchForceTx1 : 1;  /* r132.0 */
            uint8_t OutputSquelchForceTx2 : 1;  /* r132.1 */
            uint8_t OutputSquelchForceTx3 : 1;  /* r132.2 */
            uint8_t OutputSquelchForceTx4 : 1;  /* r132.3 */
            uint8_t OutputSquelchForceTx5 : 1;  /* r132.4 */
            uint8_t OutputSquelchForceTx6 : 1;  /* r132.5 */
            uint8_t OutputSquelchForceTx7 : 1;  /* r132.6 */
            uint8_t OutputSquelchForceTx8 : 1;  /* r132.7 */
        };
        uint8_t OutputSquelchForceTx;
    };
    uint8_t reserved_133;  /**< r133 Reserved */
        /**
         * @brief AdaptiveInputEqFreezeTx1
         */
        /**
         * @brief AdaptiveInputEqFreezeTx2
         */
        /**
         * @brief AdaptiveInputEqFreezeTx3
         */
        /**
         * @brief AdaptiveInputEqFreezeTx4
         */
        /**
         * @brief AdaptiveInputEqFreezeTx5
         */
        /**
         * @brief AdaptiveInputEqFreezeTx6
         */
        /**
         * @brief AdaptiveInputEqFreezeTx7
         */
        /**
         * @brief AdaptiveInputEqFreezeTx8
         * @details AdaptiveInputEqFreezeTx<i> 0b: No impact on Tx input eq adaptation behavior for lane <i> 1b: Tx 
         * inputequalizer adaptation frozen at last value for lane <i> See section 6.2.5.4 Advertisement: 01h:161.4
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t AdaptiveInputEqFreezeTx1 : 1;  /* r134.0 */
            uint8_t AdaptiveInputEqFreezeTx2 : 1;  /* r134.1 */
            uint8_t AdaptiveInputEqFreezeTx3 : 1;  /* r134.2 */
            uint8_t AdaptiveInputEqFreezeTx4 : 1;  /* r134.3 */
            uint8_t AdaptiveInputEqFreezeTx5 : 1;  /* r134.4 */
            uint8_t AdaptiveInputEqFreezeTx6 : 1;  /* r134.5 */
            uint8_t AdaptiveInputEqFreezeTx7 : 1;  /* r134.6 */
            uint8_t AdaptiveInputEqFreezeTx8 : 1;  /* r134.7 */
        };
        uint8_t AdaptiveInputEqFreezeTx;
    };
    /** @brief AdaptiveInputEqStoreTx (uint16_t, 2 bytes) */
    union {
        struct __attribute__((packed)) {
        /**
         * @brief AdaptiveInputEqStoreTx1
         */
        uint16_t AdaptiveInputEqStoreTx1 : 2;  /* bits 1:0 */
        /**
         * @brief AdaptiveInputEqStoreTx2
         */
        uint16_t AdaptiveInputEqStoreTx2 : 2;  /* bits 3:2 */
        /**
         * @brief AdaptiveInputEqStoreTx3
         */
        uint16_t AdaptiveInputEqStoreTx3 : 2;  /* bits 5:4 */
        /**
         * @brief AdaptiveInputEqStoreTx4
         * @details AdaptiveInputEqStoreTx<i> Tx Input Equalizer Adaptation Store location for lane <i> 00b: reserved 
         * 01b:store to recall buffer 1 10b: store to recall buffer 2 11b: reserved See section 6.2.5.4 Advertisement: 
         * 01h:161.6-5
         * @access WO Adv.
         */
        uint16_t AdaptiveInputEqStoreTx4 : 2;  /* bits 7:6 */
        /**
         * @brief AdaptiveInputEqStoreTx5
         */
        uint16_t AdaptiveInputEqStoreTx5 : 2;  /* bits 9:8 */
        /**
         * @brief AdaptiveInputEqStoreTx6
         */
        uint16_t AdaptiveInputEqStoreTx6 : 2;  /* bits 11:10 */
        /**
         * @brief AdaptiveInputEqStoreTx7
         */
        uint16_t AdaptiveInputEqStoreTx7 : 2;  /* bits 13:12 */
        /**
         * @brief AdaptiveInputEqStoreTx8
         * @access WO Adv.
         */
        uint16_t AdaptiveInputEqStoreTx8 : 2;  /* bits 15:14 */
        };
        uint16_t AdaptiveInputEqStoreTx;
    };
        /**
         * @brief OutputPolarityFlipRx1
         */
        /**
         * @brief OutputPolarityFlipRx2
         */
        /**
         * @brief OutputPolarityFlipRx3
         */
        /**
         * @brief OutputPolarityFlipRx4
         */
        /**
         * @brief OutputPolarityFlipRx5
         */
        /**
         * @brief OutputPolarityFlipRx6
         */
        /**
         * @brief OutputPolarityFlipRx7
         */
        /**
         * @brief OutputPolarityFlipRx8
         * @details OutputPolarityFlipRx<i> 0b: No Rx output polarity flip for lane <i> 1b: Rx output polarity flip for 
         * lane<i> Advertisement: 01h:156.0
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t OutputPolarityFlipRx1 : 1;  /* r137.0 */
            uint8_t OutputPolarityFlipRx2 : 1;  /* r137.1 */
            uint8_t OutputPolarityFlipRx3 : 1;  /* r137.2 */
            uint8_t OutputPolarityFlipRx4 : 1;  /* r137.3 */
            uint8_t OutputPolarityFlipRx5 : 1;  /* r137.4 */
            uint8_t OutputPolarityFlipRx6 : 1;  /* r137.5 */
            uint8_t OutputPolarityFlipRx7 : 1;  /* r137.6 */
            uint8_t OutputPolarityFlipRx8 : 1;  /* r137.7 */
        };
        uint8_t OutputPolarityFlipRx;
    };
        /**
         * @brief OutputDisableRx1
         */
        /**
         * @brief OutputDisableRx2
         */
        /**
         * @brief OutputDisableRx3
         */
        /**
         * @brief OutputDisableRx4
         */
        /**
         * @brief OutputDisableRx5
         */
        /**
         * @brief OutputDisableRx6
         */
        /**
         * @brief OutputDisableRx7
         */
        /**
         * @brief OutputDisableRx8
         * @details OutputDisableRx<i> 0b: Rx output enabled for lane <i> 1b: Rx output disabled for lane <i> 
         * Advertisement:01h:156.1
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t OutputDisableRx1 : 1;  /* r138.0 */
            uint8_t OutputDisableRx2 : 1;  /* r138.1 */
            uint8_t OutputDisableRx3 : 1;  /* r138.2 */
            uint8_t OutputDisableRx4 : 1;  /* r138.3 */
            uint8_t OutputDisableRx5 : 1;  /* r138.4 */
            uint8_t OutputDisableRx6 : 1;  /* r138.5 */
            uint8_t OutputDisableRx7 : 1;  /* r138.6 */
            uint8_t OutputDisableRx8 : 1;  /* r138.7 */
        };
        uint8_t OutputDisableRx;
    };
        /**
         * @brief AutoSquelchDisableRx1
         */
        /**
         * @brief AutoSquelchDisableRx2
         */
        /**
         * @brief AutoSquelchDisableRx3
         */
        /**
         * @brief AutoSquelchDisableRx4
         */
        /**
         * @brief AutoSquelchDisableRx5
         */
        /**
         * @brief AutoSquelchDisableRx6
         */
        /**
         * @brief AutoSquelchDisableRx7
         */
        /**
         * @brief AutoSquelchDisableRx8
         * @details AutoSquelchDisableRx<i> 0b: Automatic Rx output squelching enabled for host lane <i> 1b: Automatic 
         * Rxoutput squelching disabled for host lane <i> Note: Automatic Rx output squelching control is not 
         * advertised,hence always assumed to be supported. Advertisement: 01h:156.2
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t AutoSquelchDisableRx1 : 1;  /* r139.0 */
            uint8_t AutoSquelchDisableRx2 : 1;  /* r139.1 */
            uint8_t AutoSquelchDisableRx3 : 1;  /* r139.2 */
            uint8_t AutoSquelchDisableRx4 : 1;  /* r139.3 */
            uint8_t AutoSquelchDisableRx5 : 1;  /* r139.4 */
            uint8_t AutoSquelchDisableRx6 : 1;  /* r139.5 */
            uint8_t AutoSquelchDisableRx7 : 1;  /* r139.6 */
            uint8_t AutoSquelchDisableRx8 : 1;  /* r139.7 */
        };
        uint8_t AutoSquelchDisableRx;
    };
    uint8_t reserved_140[3];  /**< r140.. */
    /** @brief Staged Control Set (SCS0 @ r143, SCS1 @ r178) */
    struct __attribute__((packed)) {
        /**
         * @brief ApplyDPInitLane1
         */
        /**
         * @brief ApplyDPInitLane2
         */
        /**
         * @brief ApplyDPInitLane3
         */
        /**
         * @brief ApplyDPInitLane4
         */
        /**
         * @brief ApplyDPInitLane5
         */
        /**
         * @brief ApplyDPInitLane6
         */
        /**
         * @brief ApplyDPInitLane7
         */
        /**
         * @brief ApplyDPInitLane8
         * @details SCS0::ApplyDPInitLane<i> 0b: No action for host lane <i> 1b: Trigger the Provision procedure using 
         * theStaged Control Set 0 settings for host lane <i>, with feedback provided in the associated 
         * ConfigStatusLane<i>field Restriction: This byte must be written in a single-byte WRITE Note: See Table 6-3 
         * forpreconditions and state dependencies
         * @access WO Rqd.
         */
        union {
            struct {
                uint8_t ApplyDPInitLane1 : 1;  /* r143.0 */
                uint8_t ApplyDPInitLane2 : 1;  /* r143.1 */
                uint8_t ApplyDPInitLane3 : 1;  /* r143.2 */
                uint8_t ApplyDPInitLane4 : 1;  /* r143.3 */
                uint8_t ApplyDPInitLane5 : 1;  /* r143.4 */
                uint8_t ApplyDPInitLane6 : 1;  /* r143.5 */
                uint8_t ApplyDPInitLane7 : 1;  /* r143.6 */
                uint8_t ApplyDPInitLane8 : 1;  /* r143.7 */
            };
            uint8_t ApplyDPInitLane;
        };
        /**
         * @brief ApplyImmediateLane1
         */
        /**
         * @brief ApplyImmediateLane2
         */
        /**
         * @brief ApplyImmediateLane3
         */
        /**
         * @brief ApplyImmediateLane4
         */
        /**
         * @brief ApplyImmediateLane5
         */
        /**
         * @brief ApplyImmediateLane6
         */
        /**
         * @brief ApplyImmediateLane7
         */
        /**
         * @brief ApplyImmediateLane8
         * @details SCS0::ApplyImmediate<i> 0b: No action for host lane <i> 1b: Trigger the Provision-and-Commission 
         * procedureusing the Staged Control Set 0 settings for host lane <i>, with feedback provided in the associated 
         * ConfigStatusLane<i>field Restriction: This byte must be written in a single-byte WRITE Condition: 
         * SteppedConfigOnly(00h:2.6) = 0b Note: See Table 6-3 for preconditions and state dependencies
         * @access WO Cnd.
         */
        union {
            struct {
                uint8_t ApplyImmediateLane1 : 1;  /* r144.0 */
                uint8_t ApplyImmediateLane2 : 1;  /* r144.1 */
                uint8_t ApplyImmediateLane3 : 1;  /* r144.2 */
                uint8_t ApplyImmediateLane4 : 1;  /* r144.3 */
                uint8_t ApplyImmediateLane5 : 1;  /* r144.4 */
                uint8_t ApplyImmediateLane6 : 1;  /* r144.5 */
                uint8_t ApplyImmediateLane7 : 1;  /* r144.6 */
                uint8_t ApplyImmediateLane8 : 1;  /* r144.7 */
            };
            uint8_t ApplyImmediateLane;
        };
        /** @brief Data Path Configuration per lane */
        struct __attribute__((packed)) {
            /**
             * @brief ExplicitControlLane1
             */
            /**
             * @brief DataPathIDLane1
             */
            /**
             * @brief AppSelCodeLane1
             * @details SCS0::DPConfigLane1 See Table 8-71
             * @access RW Rqd.
             */
            union {
                struct {
                    uint8_t ExplicitControlLane1 : 1;  /* r145.0 */
                    uint8_t DataPathIDLane1 : 3;  /* r145.3-1 */
                    uint8_t AppSelCodeLane1 : 4;  /* r145.7-4 */
                };
                uint8_t r145;
            };
        } DataPathConfig[8];
        /**
         * @brief AdaptiveInputEqEnableTx1
         */
        /**
         * @brief AdaptiveInputEqEnableTx2
         */
        /**
         * @brief AdaptiveInputEqEnableTx3
         */
        /**
         * @brief AdaptiveInputEqEnableTx4
         */
        /**
         * @brief AdaptiveInputEqEnableTx5
         */
        /**
         * @brief AdaptiveInputEqEnableTx6
         */
        /**
         * @brief AdaptiveInputEqEnableTx7
         */
        /**
         * @brief AdaptiveInputEqEnableTx8
         * @details SCS0::AdaptiveInputEqEnableTx<i> Adaptive Tx input equalizer for host lane <i> 1b: Enable 0b: 
         * Disable(allow host-controlled equalization) Advertisement: 01h:161.3
         * @access RW Adv.
         */
        union {
            struct {
                uint8_t AdaptiveInputEqEnableTx1 : 1;  /* r153.0 */
                uint8_t AdaptiveInputEqEnableTx2 : 1;  /* r153.1 */
                uint8_t AdaptiveInputEqEnableTx3 : 1;  /* r153.2 */
                uint8_t AdaptiveInputEqEnableTx4 : 1;  /* r153.3 */
                uint8_t AdaptiveInputEqEnableTx5 : 1;  /* r153.4 */
                uint8_t AdaptiveInputEqEnableTx6 : 1;  /* r153.5 */
                uint8_t AdaptiveInputEqEnableTx7 : 1;  /* r153.6 */
                uint8_t AdaptiveInputEqEnableTx8 : 1;  /* r153.7 */
            };
            uint8_t AdaptiveInputEqEnableTx;
        };
        /** @brief AdaptiveInputEqRecallTx per lane (16-bit register) */
        union {
            struct __attribute__((packed)) {
                /**
                 * @brief AdaptiveInputEqRecallTx1
                 */
                uint16_t AdaptiveInputEqRecallTx1 : 2;  /* bits 1:0 */
                /**
                 * @brief AdaptiveInputEqRecallTx2
                 */
                uint16_t AdaptiveInputEqRecallTx2 : 2;  /* bits 3:2 */
                /**
                 * @brief AdaptiveInputEqRecallTx3
                 */
                uint16_t AdaptiveInputEqRecallTx3 : 2;  /* bits 5:4 */
                /**
                 * @brief AdaptiveInputEqRecallTx4
                 * @details SCS0::AdaptiveInputEqRecallTx<i> Recall stored Tx input equalizer adaptation settings for 
                 * hostlane <i> when Staged Control Set is copied to Active Control Set. See section 6.2.5.4 for 
                 * Store/Recall00b: do not recall 01b: recall buffer 1 10b: recall buffer 2 11b: reserved 
                 * Advertisement:01h:161.6-5
                 * @access RW Adv.
                 */
                uint16_t AdaptiveInputEqRecallTx4 : 2;  /* bits 7:6 */
                /**
                 * @brief AdaptiveInputEqRecallTx5
                 */
                uint16_t AdaptiveInputEqRecallTx5 : 2;  /* bits 9:8 */
                /**
                 * @brief AdaptiveInputEqRecallTx6
                 */
                uint16_t AdaptiveInputEqRecallTx6 : 2;  /* bits 11:10 */
                /**
                 * @brief AdaptiveInputEqRecallTx7
                 */
                uint16_t AdaptiveInputEqRecallTx7 : 2;  /* bits 13:12 */
                /**
                 * @brief AdaptiveInputEqRecallTx8
                 * @access RW Adv.
                 */
                uint16_t AdaptiveInputEqRecallTx8 : 2;  /* bits 15:14 */
            };
            uint16_t AdaptiveInputEqRecallTx;
        };
        /** @brief HostControlledInputEqTargetTx per lane (32-bit register) */
        union {
            struct __attribute__((packed)) {
                /**
                 * @brief HostControlledInputEqTargetTx1
                 */
                uint32_t HostControlledInputEqTargetTx1 : 4;  /* bits 3:0 */
                /**
                 * @brief HostControlledInputEqTargetTx2
                 * @details SCS0:: HostControlledInputEqTargetTx<i> Host-controlled Tx input equalizer target for host 
                 * lane<i>. Encoding as described in Table 6-6 Advertisement: 01h:161.2
                 * @access RW Adv.
                 */
                uint32_t HostControlledInputEqTargetTx2 : 4;  /* bits 7:4 */
                /**
                 * @brief HostControlledInputEqTargetTx3
                 */
                uint32_t HostControlledInputEqTargetTx3 : 4;  /* bits 11:8 */
                /**
                 * @brief HostControlledInputEqTargetTx4
                 * @access RW Adv.
                 */
                uint32_t HostControlledInputEqTargetTx4 : 4;  /* bits 15:12 */
                /**
                 * @brief HostControlledInputEqTargetTx5
                 */
                uint32_t HostControlledInputEqTargetTx5 : 4;  /* bits 19:16 */
                /**
                 * @brief HostControlledInputEqTargetTx6
                 * @access RW Adv.
                 */
                uint32_t HostControlledInputEqTargetTx6 : 4;  /* bits 23:20 */
                /**
                 * @brief HostControlledInputEqTargetTx7
                 */
                uint32_t HostControlledInputEqTargetTx7 : 4;  /* bits 27:24 */
                /**
                 * @brief HostControlledInputEqTargetTx8
                 * @access RW Adv.
                 */
                uint32_t HostControlledInputEqTargetTx8 : 4;  /* bits 31:28 */
            };
            uint32_t HostControlledInputEqTargetTx;
        };
        /**
         * @brief CDREnableTx1
         */
        /**
         * @brief CDREnableTx2
         */
        /**
         * @brief CDREnableTx3
         */
        /**
         * @brief CDREnableTx4
         */
        /**
         * @brief CDREnableTx5
         */
        /**
         * @brief CDREnableTx6
         */
        /**
         * @brief CDREnableTx7
         */
        /**
         * @brief CDREnableTx8
         * @details SCS0::CDREnableTx<i> 1b: CDR enabled 0b: CDR bypassed Advertisement: 01h:161.0-1
         * @access RW Adv.
         */
        union {
            struct {
                uint8_t CDREnableTx1 : 1;  /* r160.0 */
                uint8_t CDREnableTx2 : 1;  /* r160.1 */
                uint8_t CDREnableTx3 : 1;  /* r160.2 */
                uint8_t CDREnableTx4 : 1;  /* r160.3 */
                uint8_t CDREnableTx5 : 1;  /* r160.4 */
                uint8_t CDREnableTx6 : 1;  /* r160.5 */
                uint8_t CDREnableTx7 : 1;  /* r160.6 */
                uint8_t CDREnableTx8 : 1;  /* r160.7 */
            };
            uint8_t CDREnableTx;
        };
        /**
         * @brief CDREnableRx1
         */
        /**
         * @brief CDREnableRx2
         */
        /**
         * @brief CDREnableRx3
         */
        /**
         * @brief CDREnableRx4
         */
        /**
         * @brief CDREnableRx5
         */
        /**
         * @brief CDREnableRx6
         */
        /**
         * @brief CDREnableRx7
         */
        /**
         * @brief CDREnableRx8
         * @details SCS0::CDREnableRx<i> 1b: CDR enabled 0b: CDR bypassed Advertisement: 01h:162.0-1
         * @access RW Adv.
         */
        union {
            struct {
                uint8_t CDREnableRx1 : 1;  /* r161.0 */
                uint8_t CDREnableRx2 : 1;  /* r161.1 */
                uint8_t CDREnableRx3 : 1;  /* r161.2 */
                uint8_t CDREnableRx4 : 1;  /* r161.3 */
                uint8_t CDREnableRx5 : 1;  /* r161.4 */
                uint8_t CDREnableRx6 : 1;  /* r161.5 */
                uint8_t CDREnableRx7 : 1;  /* r161.6 */
                uint8_t CDREnableRx8 : 1;  /* r161.7 */
            };
            uint8_t CDREnableRx;
        };
        /** @brief OutputEqPreCursorTargetRx per lane (32-bit register) */
        union {
            struct __attribute__((packed)) {
                /**
                 * @brief OutputEqPreCursorTargetRx1
                 */
                uint32_t OutputEqPreCursorTargetRx1 : 4;  /* bits 3:0 */
                /**
                 * @brief OutputEqPreCursorTargetRx2
                 * @details SCS0::OutputEqPreCursorTargetRx<i> Rx output equalization pre-cursor target. Used only when 
                 * bothpre- and post-cursor targets are supported. See Table 6-7 and section 6.2.5.2 Advertisement: 
                 * 01h:162.4-3
                 * @access RW Adv.
                 */
                uint32_t OutputEqPreCursorTargetRx2 : 4;  /* bits 7:4 */
                /**
                 * @brief OutputEqPreCursorTargetRx3
                 */
                uint32_t OutputEqPreCursorTargetRx3 : 4;  /* bits 11:8 */
                /**
                 * @brief OutputEqPreCursorTargetRx4
                 * @access RW Adv.
                 */
                uint32_t OutputEqPreCursorTargetRx4 : 4;  /* bits 15:12 */
                /**
                 * @brief OutputEqPreCursorTargetRx5
                 */
                uint32_t OutputEqPreCursorTargetRx5 : 4;  /* bits 19:16 */
                /**
                 * @brief OutputEqPreCursorTargetRx6
                 * @access RW Adv.
                 */
                uint32_t OutputEqPreCursorTargetRx6 : 4;  /* bits 23:20 */
                /**
                 * @brief OutputEqPreCursorTargetRx7
                 */
                uint32_t OutputEqPreCursorTargetRx7 : 4;  /* bits 27:24 */
                /**
                 * @brief OutputEqPreCursorTargetRx8
                 * @access RW Adv.
                 */
                uint32_t OutputEqPreCursorTargetRx8 : 4;  /* bits 31:28 */
            };
            uint32_t OutputEqPreCursorTargetRx;
        };
        /** @brief OutputEqPostCursorTargetRx per lane (32-bit register) */
        union {
            struct __attribute__((packed)) {
                /**
                 * @brief OutputEqPostCursorTargetRx1
                 */
                uint32_t OutputEqPostCursorTargetRx1 : 4;  /* bits 3:0 */
                /**
                 * @brief OutputEqPostCursorTargetRx2
                 * @details SCS0::OutputEqPostCursorTargetRx<i> Rx output equalization post-cursor target, or pre- 
                 * cursortarget when only pre-cursor setting is advertised. See Table 6-7 and section 6.2.5.2 
                 * Advertisement:01h:162.4-3
                 * @access RW Adv.
                 */
                uint32_t OutputEqPostCursorTargetRx2 : 4;  /* bits 7:4 */
                /**
                 * @brief OutputEqPostCursorTargetRx3
                 */
                uint32_t OutputEqPostCursorTargetRx3 : 4;  /* bits 11:8 */
                /**
                 * @brief OutputEqPostCursorTargetRx4
                 * @access RW Adv.
                 */
                uint32_t OutputEqPostCursorTargetRx4 : 4;  /* bits 15:12 */
                /**
                 * @brief OutputEqPostCursorTargetRx5
                 */
                uint32_t OutputEqPostCursorTargetRx5 : 4;  /* bits 19:16 */
                /**
                 * @brief OutputEqPostCursorTargetRx6
                 * @access RW Adv.
                 */
                uint32_t OutputEqPostCursorTargetRx6 : 4;  /* bits 23:20 */
                /**
                 * @brief OutputEqPostCursorTargetRx7
                 */
                uint32_t OutputEqPostCursorTargetRx7 : 4;  /* bits 27:24 */
                /**
                 * @brief OutputEqPostCursorTargetRx8
                 * @access RW Adv.
                 */
                uint32_t OutputEqPostCursorTargetRx8 : 4;  /* bits 31:28 */
            };
            uint32_t OutputEqPostCursorTargetRx;
        };
        /** @brief OutputAmplitudeTargetRx per lane (32-bit register) */
        union {
            struct __attribute__((packed)) {
                /**
                 * @brief OutputAmplitudeTargetRx1
                 */
                uint32_t OutputAmplitudeTargetRx1 : 4;  /* bits 3:0 */
                /**
                 * @brief OutputAmplitudeTargetRx2
                 * @details SCS0::OutputAmplitudeTargetRx<i> Rx output amplitude target See Table 6-8 and section 
                 * 6.2.5.3Advertisement: 01h:162.2
                 * @access RW Adv.
                 */
                uint32_t OutputAmplitudeTargetRx2 : 4;  /* bits 7:4 */
                /**
                 * @brief OutputAmplitudeTargetRx3
                 */
                uint32_t OutputAmplitudeTargetRx3 : 4;  /* bits 11:8 */
                /**
                 * @brief OutputAmplitudeTargetRx4
                 * @access RW Adv.
                 */
                uint32_t OutputAmplitudeTargetRx4 : 4;  /* bits 15:12 */
                /**
                 * @brief OutputAmplitudeTargetRx5
                 */
                uint32_t OutputAmplitudeTargetRx5 : 4;  /* bits 19:16 */
                /**
                 * @brief OutputAmplitudeTargetRx6
                 * @access RW Adv.
                 */
                uint32_t OutputAmplitudeTargetRx6 : 4;  /* bits 23:20 */
                /**
                 * @brief OutputAmplitudeTargetRx7
                 */
                uint32_t OutputAmplitudeTargetRx7 : 4;  /* bits 27:24 */
                /**
                 * @brief OutputAmplitudeTargetRx8
                 * @access RW Adv.
                 */
                uint32_t OutputAmplitudeTargetRx8 : 4;  /* bits 31:28 */
            };
            uint32_t OutputAmplitudeTargetRx;
        };
        uint8_t reserved_31;
        uint8_t reserved_32;
        /**
         * @brief ApplyImmediateTx1
         */
        /**
         * @brief ApplyImmediateTx2
         */
        /**
         * @brief ApplyImmediateTx3
         */
        /**
         * @brief ApplyImmediateTx4
         */
        /**
         * @brief ApplyImmediateTx5
         */
        /**
         * @brief ApplyImmediateTx6
         */
        /**
         * @brief ApplyImmediateTx7
         */
        /**
         * @brief ApplyImmediateTx8
         * @details SCS0::ApplyImmediateTx<i> 0b: No action for host lane <i> 1b: Trigger the Provision-and-Commission 
         * procedurefor Tx using the Staged Control Set 0 settings for host lane <i>, with feedback provided in the 
         * ConfigStatusLane<i>field Restriction: This byte must be written in a single-byte WRITE Condition: 
         * UnidirReconfigSupported(01h:162.6) = 1b Note: See Table 6-3 for preconditions and state dependencies
         * @access WO Cnd.
         */
        union {
            struct {
                uint8_t ApplyImmediateTx1 : 1;  /* r176.0 */
                uint8_t ApplyImmediateTx2 : 1;  /* r176.1 */
                uint8_t ApplyImmediateTx3 : 1;  /* r176.2 */
                uint8_t ApplyImmediateTx4 : 1;  /* r176.3 */
                uint8_t ApplyImmediateTx5 : 1;  /* r176.4 */
                uint8_t ApplyImmediateTx6 : 1;  /* r176.5 */
                uint8_t ApplyImmediateTx7 : 1;  /* r176.6 */
                uint8_t ApplyImmediateTx8 : 1;  /* r176.7 */
            };
            uint8_t ApplyImmediateTx;
        };
        /**
         * @brief ApplyImmediateRx1
         */
        /**
         * @brief ApplyImmediateRx2
         */
        /**
         * @brief ApplyImmediateRx3
         */
        /**
         * @brief ApplyImmediateRx4
         */
        /**
         * @brief ApplyImmediateRx5
         */
        /**
         * @brief ApplyImmediateRx6
         */
        /**
         * @brief ApplyImmediateRx7
         */
        /**
         * @brief ApplyImmediateRx8
         * @details SCS0::ApplyImmediateRx<i> 0b: No action for host lane <i> 1b: Trigger the Provision-and-Commission 
         * procedurefor Rx using the Staged Control Set 0 settings for host lane <i>, with feedback provided in the 
         * ConfigStatusLane<i>field Restriction: This byte must be written in a single-byte WRITE Condition: 
         * UnidirReconfigSupported(01h:162.6) = 1b Note: See Table 6-3 for preconditions and state dependencies
         * @access WO Cnd.
         */
        union {
            struct {
                uint8_t ApplyImmediateRx1 : 1;  /* r177.0 */
                uint8_t ApplyImmediateRx2 : 1;  /* r177.1 */
                uint8_t ApplyImmediateRx3 : 1;  /* r177.2 */
                uint8_t ApplyImmediateRx4 : 1;  /* r177.3 */
                uint8_t ApplyImmediateRx5 : 1;  /* r177.4 */
                uint8_t ApplyImmediateRx6 : 1;  /* r177.5 */
                uint8_t ApplyImmediateRx7 : 1;  /* r177.6 */
                uint8_t ApplyImmediateRx8 : 1;  /* r177.7 */
            };
            uint8_t ApplyImmediateRx;
        };
    } StagedControlSet[2];
        /**
         * @brief DPStateChangedMask1
         */
        /**
         * @brief DPStateChangedMask2
         */
        /**
         * @brief DPStateChangedMask3
         */
        /**
         * @brief DPStateChangedMask4
         */
        /**
         * @brief DPStateChangedMask5
         */
        /**
         * @brief DPStateChangedMask6
         */
        /**
         * @brief DPStateChangedMask7
         */
        /**
         * @brief DPStateChangedMask8
         * @details DPStateChangedMask<i> Mask for DPStateChangedFlag<i> for Data Path of host lane <i>
         * @access RW Rqd.
         */
    union {
        struct {
            uint8_t DPStateChangedMask1 : 1;  /* r213.0 */
            uint8_t DPStateChangedMask2 : 1;  /* r213.1 */
            uint8_t DPStateChangedMask3 : 1;  /* r213.2 */
            uint8_t DPStateChangedMask4 : 1;  /* r213.3 */
            uint8_t DPStateChangedMask5 : 1;  /* r213.4 */
            uint8_t DPStateChangedMask6 : 1;  /* r213.5 */
            uint8_t DPStateChangedMask7 : 1;  /* r213.6 */
            uint8_t DPStateChangedMask8 : 1;  /* r213.7 */
        };
        uint8_t DPStateChangedMask;
    };
        /**
         * @brief FailureMaskTx1
         */
        /**
         * @brief FailureMaskTx2
         */
        /**
         * @brief FailureMaskTx3
         */
        /**
         * @brief FailureMaskTx4
         */
        /**
         * @brief FailureMaskTx5
         */
        /**
         * @brief FailureMaskTx6
         */
        /**
         * @brief FailureMaskTx7
         */
        /**
         * @brief FailureMaskTx8
         * @details FailureMaskTx<i> Mask for FailureFlagTx<i>, affecting media lane <i> Advertisement: 01h:157.0
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t FailureMaskTx1 : 1;  /* r214.0 */
            uint8_t FailureMaskTx2 : 1;  /* r214.1 */
            uint8_t FailureMaskTx3 : 1;  /* r214.2 */
            uint8_t FailureMaskTx4 : 1;  /* r214.3 */
            uint8_t FailureMaskTx5 : 1;  /* r214.4 */
            uint8_t FailureMaskTx6 : 1;  /* r214.5 */
            uint8_t FailureMaskTx7 : 1;  /* r214.6 */
            uint8_t FailureMaskTx8 : 1;  /* r214.7 */
        };
        uint8_t FailureMaskTx;
    };
        /**
         * @brief LOSMaskTx1
         */
        /**
         * @brief LOSMaskTx2
         */
        /**
         * @brief LOSMaskTx3
         */
        /**
         * @brief LOSMaskTx4
         */
        /**
         * @brief LOSMaskTx5
         */
        /**
         * @brief LOSMaskTx6
         */
        /**
         * @brief LOSMaskTx7
         */
        /**
         * @brief LOSMaskTx8
         * @details LOSMaskTx<i> Mask for LOSFlagTx, lane <i> Advertisement: 01h:157.1
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t LOSMaskTx1 : 1;  /* r215.0 */
            uint8_t LOSMaskTx2 : 1;  /* r215.1 */
            uint8_t LOSMaskTx3 : 1;  /* r215.2 */
            uint8_t LOSMaskTx4 : 1;  /* r215.3 */
            uint8_t LOSMaskTx5 : 1;  /* r215.4 */
            uint8_t LOSMaskTx6 : 1;  /* r215.5 */
            uint8_t LOSMaskTx7 : 1;  /* r215.6 */
            uint8_t LOSMaskTx8 : 1;  /* r215.7 */
        };
        uint8_t LOSMaskTx;
    };
        /**
         * @brief CDRLOLMaskTx1
         */
        /**
         * @brief CDRLOLMaskTx2
         */
        /**
         * @brief CDRLOLMaskTx3
         */
        /**
         * @brief CDRLOLMaskTx4
         */
        /**
         * @brief CDRLOLMaskTx5
         */
        /**
         * @brief CDRLOLMaskTx6
         */
        /**
         * @brief CDRLOLMaskTx7
         */
        /**
         * @brief CDRLOLMaskTx8
         * @details CDRLOLMaskTx<i> Mask for CDRLOLFlagTx<i>, lane <i> Advertisement: 01h:157.2
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t CDRLOLMaskTx1 : 1;  /* r216.0 */
            uint8_t CDRLOLMaskTx2 : 1;  /* r216.1 */
            uint8_t CDRLOLMaskTx3 : 1;  /* r216.2 */
            uint8_t CDRLOLMaskTx4 : 1;  /* r216.3 */
            uint8_t CDRLOLMaskTx5 : 1;  /* r216.4 */
            uint8_t CDRLOLMaskTx6 : 1;  /* r216.5 */
            uint8_t CDRLOLMaskTx7 : 1;  /* r216.6 */
            uint8_t CDRLOLMaskTx8 : 1;  /* r216.7 */
        };
        uint8_t CDRLOLMaskTx;
    };
        /**
         * @brief AdaptiveInputEqFailMaskTx1
         */
        /**
         * @brief AdaptiveInputEqFailMaskTx2
         */
        /**
         * @brief AdaptiveInputEqFailMaskTx3
         */
        /**
         * @brief AdaptiveInputEqFailMaskTx4
         */
        /**
         * @brief AdaptiveInputEqFailMaskTx5
         */
        /**
         * @brief AdaptiveInputEqFailMaskTx6
         */
        /**
         * @brief AdaptiveInputEqFailMaskTx7
         */
        /**
         * @brief AdaptiveInputEqFailMaskTx8
         * @details AdaptiveInputEqFailMaskTx<i> Mask for AdaptiveInputEqFailFlagTx<i>, lane <i> Advertisement: 
         * 01h:157.3
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t AdaptiveInputEqFailMaskTx1 : 1;  /* r217.0 */
            uint8_t AdaptiveInputEqFailMaskTx2 : 1;  /* r217.1 */
            uint8_t AdaptiveInputEqFailMaskTx3 : 1;  /* r217.2 */
            uint8_t AdaptiveInputEqFailMaskTx4 : 1;  /* r217.3 */
            uint8_t AdaptiveInputEqFailMaskTx5 : 1;  /* r217.4 */
            uint8_t AdaptiveInputEqFailMaskTx6 : 1;  /* r217.5 */
            uint8_t AdaptiveInputEqFailMaskTx7 : 1;  /* r217.6 */
            uint8_t AdaptiveInputEqFailMaskTx8 : 1;  /* r217.7 */
        };
        uint8_t AdaptiveInputEqFailMaskTx;
    };
        /**
         * @brief OpticalPowerHighAlarmMaskTx1
         */
        /**
         * @brief OpticalPowerHighAlarmMaskTx2
         */
        /**
         * @brief OpticalPowerHighAlarmMaskTx3
         */
        /**
         * @brief OpticalPowerHighAlarmMaskTx4
         */
        /**
         * @brief OpticalPowerHighAlarmMaskTx5
         */
        /**
         * @brief OpticalPowerHighAlarmMaskTx6
         */
        /**
         * @brief OpticalPowerHighAlarmMaskTx7
         */
        /**
         * @brief OpticalPowerHighAlarmMaskTx8
         * @details OpticalPowerHighAlarmMaskTx<i> Mask for OpticalPowerHighAlarmFlagTx<i>, media lane <i> 
         * Advertisement:01h:160.1
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t OpticalPowerHighAlarmMaskTx1 : 1;  /* r218.0 */
            uint8_t OpticalPowerHighAlarmMaskTx2 : 1;  /* r218.1 */
            uint8_t OpticalPowerHighAlarmMaskTx3 : 1;  /* r218.2 */
            uint8_t OpticalPowerHighAlarmMaskTx4 : 1;  /* r218.3 */
            uint8_t OpticalPowerHighAlarmMaskTx5 : 1;  /* r218.4 */
            uint8_t OpticalPowerHighAlarmMaskTx6 : 1;  /* r218.5 */
            uint8_t OpticalPowerHighAlarmMaskTx7 : 1;  /* r218.6 */
            uint8_t OpticalPowerHighAlarmMaskTx8 : 1;  /* r218.7 */
        };
        uint8_t OpticalPowerHighAlarmMaskTx;
    };
        /**
         * @brief OpticalPowerLowAlarmMaskTx1
         */
        /**
         * @brief OpticalPowerLowAlarmMaskTx2
         */
        /**
         * @brief OpticalPowerLowAlarmMaskTx3
         */
        /**
         * @brief OpticalPowerLowAlarmMaskTx4
         */
        /**
         * @brief OpticalPowerLowAlarmMaskTx5
         */
        /**
         * @brief OpticalPowerLowAlarmMaskTx6
         * @details media lane <i> Advertisement: 01h:160.1
         */
        /**
         * @brief OpticalPowerLowAlarmMaskTx7
         */
        /**
         * @brief OpticalPowerLowAlarmMaskTx8
         * @details OpticalPowerLowAlarmMaskTx<i> Mask for OpticalPowerLowAlarmFlagTx<i>,
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t OpticalPowerLowAlarmMaskTx1 : 1;  /* r219.0 */
            uint8_t OpticalPowerLowAlarmMaskTx2 : 1;  /* r219.1 */
            uint8_t OpticalPowerLowAlarmMaskTx3 : 1;  /* r219.2 */
            uint8_t OpticalPowerLowAlarmMaskTx4 : 1;  /* r219.3 */
            uint8_t OpticalPowerLowAlarmMaskTx5 : 1;  /* r219.4 */
            uint8_t OpticalPowerLowAlarmMaskTx6 : 1;  /* r219.5 */
            uint8_t OpticalPowerLowAlarmMaskTx7 : 1;  /* r219.6 */
            uint8_t OpticalPowerLowAlarmMaskTx8 : 1;  /* r219.7 */
        };
        uint8_t OpticalPowerLowAlarmMaskTx;
    };
        /**
         * @brief OpticalPowerHighWarningMaskTx1
         */
        /**
         * @brief OpticalPowerHighWarningMaskTx2
         */
        /**
         * @brief OpticalPowerHighWarningMaskTx3
         */
        /**
         * @brief OpticalPowerHighWarningMaskTx4
         */
        /**
         * @brief OpticalPowerHighWarningMaskTx5
         */
        /**
         * @brief OpticalPowerHighWarningMaskTx6
         */
        /**
         * @brief OpticalPowerHighWarningMaskTx7
         */
        /**
         * @brief OpticalPowerHighWarningMaskTx8
         * @details OpticalPowerHighWarningMaskTx<i> Mask for OpticalPowerHighWarningFlagTx<i>, media lane <i> 
         * Advertisement:01h:160.1
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t OpticalPowerHighWarningMaskTx1 : 1;  /* r220.0 */
            uint8_t OpticalPowerHighWarningMaskTx2 : 1;  /* r220.1 */
            uint8_t OpticalPowerHighWarningMaskTx3 : 1;  /* r220.2 */
            uint8_t OpticalPowerHighWarningMaskTx4 : 1;  /* r220.3 */
            uint8_t OpticalPowerHighWarningMaskTx5 : 1;  /* r220.4 */
            uint8_t OpticalPowerHighWarningMaskTx6 : 1;  /* r220.5 */
            uint8_t OpticalPowerHighWarningMaskTx7 : 1;  /* r220.6 */
            uint8_t OpticalPowerHighWarningMaskTx8 : 1;  /* r220.7 */
        };
        uint8_t OpticalPowerHighWarningMaskTx;
    };
        /**
         * @brief OpticalPowerLowWarningMaskTx1
         */
        /**
         * @brief OpticalPowerLowWarningMaskTx2
         */
        /**
         * @brief OpticalPowerLowWarningMaskTx3
         */
        /**
         * @brief OpticalPowerLowWarningMaskTx4
         */
        /**
         * @brief OpticalPowerLowWarningMaskTx5
         */
        /**
         * @brief OpticalPowerLowWarningMaskTx6
         */
        /**
         * @brief OpticalPowerLowWarningMaskTx7
         */
        /**
         * @brief OpticalPowerLowWarningMaskTx8
         * @details OpticalPowerLowWarningMaskTx<i> Mask for OpticalPowerLowWarningFlagTx<i>, media lane <i> 
         * Advertisement:01h:160.1
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t OpticalPowerLowWarningMaskTx1 : 1;  /* r221.0 */
            uint8_t OpticalPowerLowWarningMaskTx2 : 1;  /* r221.1 */
            uint8_t OpticalPowerLowWarningMaskTx3 : 1;  /* r221.2 */
            uint8_t OpticalPowerLowWarningMaskTx4 : 1;  /* r221.3 */
            uint8_t OpticalPowerLowWarningMaskTx5 : 1;  /* r221.4 */
            uint8_t OpticalPowerLowWarningMaskTx6 : 1;  /* r221.5 */
            uint8_t OpticalPowerLowWarningMaskTx7 : 1;  /* r221.6 */
            uint8_t OpticalPowerLowWarningMaskTx8 : 1;  /* r221.7 */
        };
        uint8_t OpticalPowerLowWarningMaskTx;
    };
        /**
         * @brief LaserBiasHighAlarmMaskTx1
         */
        /**
         * @brief LaserBiasHighAlarmMaskTx2
         */
        /**
         * @brief LaserBiasHighAlarmMaskTx3
         */
        /**
         * @brief LaserBiasHighAlarmMaskTx4
         */
        /**
         * @brief LaserBiasHighAlarmMaskTx5
         */
        /**
         * @brief LaserBiasHighAlarmMaskTx6
         */
        /**
         * @brief LaserBiasHighAlarmMaskTx7
         */
        /**
         * @brief LaserBiasHighAlarmMaskTx8
         * @details LaserBiasHighAlarmMaskTx<i> Mask for LaserBiasHighAlarmFlagTx<i>, media lane <i> Advertisement: 
         * 01h:160.0
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t LaserBiasHighAlarmMaskTx1 : 1;  /* r222.0 */
            uint8_t LaserBiasHighAlarmMaskTx2 : 1;  /* r222.1 */
            uint8_t LaserBiasHighAlarmMaskTx3 : 1;  /* r222.2 */
            uint8_t LaserBiasHighAlarmMaskTx4 : 1;  /* r222.3 */
            uint8_t LaserBiasHighAlarmMaskTx5 : 1;  /* r222.4 */
            uint8_t LaserBiasHighAlarmMaskTx6 : 1;  /* r222.5 */
            uint8_t LaserBiasHighAlarmMaskTx7 : 1;  /* r222.6 */
            uint8_t LaserBiasHighAlarmMaskTx8 : 1;  /* r222.7 */
        };
        uint8_t LaserBiasHighAlarmMaskTx;
    };
        /**
         * @brief LaserBiasLowAlarmMaskTx1
         */
        /**
         * @brief LaserBiasLowAlarmMaskTx2
         */
        /**
         * @brief LaserBiasLowAlarmMaskTx3
         */
        /**
         * @brief LaserBiasLowAlarmMaskTx4
         */
        /**
         * @brief LaserBiasLowAlarmMaskTx5
         */
        /**
         * @brief LaserBiasLowAlarmMaskTx6
         */
        /**
         * @brief LaserBiasLowAlarmMaskTx7
         */
        /**
         * @brief LaserBiasLowAlarmMaskTx8
         * @details LaserBiasLowAlarmMaskTx<i> Mask for LaserBiasLowAlarmFlagTx<i>, media lane <i> Advertisement: 
         * 01h:160.0
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t LaserBiasLowAlarmMaskTx1 : 1;  /* r223.0 */
            uint8_t LaserBiasLowAlarmMaskTx2 : 1;  /* r223.1 */
            uint8_t LaserBiasLowAlarmMaskTx3 : 1;  /* r223.2 */
            uint8_t LaserBiasLowAlarmMaskTx4 : 1;  /* r223.3 */
            uint8_t LaserBiasLowAlarmMaskTx5 : 1;  /* r223.4 */
            uint8_t LaserBiasLowAlarmMaskTx6 : 1;  /* r223.5 */
            uint8_t LaserBiasLowAlarmMaskTx7 : 1;  /* r223.6 */
            uint8_t LaserBiasLowAlarmMaskTx8 : 1;  /* r223.7 */
        };
        uint8_t LaserBiasLowAlarmMaskTx;
    };
        /**
         * @brief LaserBiasHighWarningMaskTx1
         */
        /**
         * @brief LaserBiasHighWarningMaskTx2
         */
        /**
         * @brief LaserBiasHighWarningMaskTx3
         */
        /**
         * @brief LaserBiasHighWarningMaskTx4
         */
        /**
         * @brief LaserBiasHighWarningMaskTx5
         */
        /**
         * @brief LaserBiasHighWarningMaskTx6
         */
        /**
         * @brief LaserBiasHighWarningMaskTx7
         */
        /**
         * @brief LaserBiasHighWarningMaskTx8
         * @details LaserBiasHighWarningMaskTx<i> Mask for LaserBiasHighWarningFlagTx<i>, media lane <i> Advertisement: 
         * 01h:160.0
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t LaserBiasHighWarningMaskTx1 : 1;  /* r224.0 */
            uint8_t LaserBiasHighWarningMaskTx2 : 1;  /* r224.1 */
            uint8_t LaserBiasHighWarningMaskTx3 : 1;  /* r224.2 */
            uint8_t LaserBiasHighWarningMaskTx4 : 1;  /* r224.3 */
            uint8_t LaserBiasHighWarningMaskTx5 : 1;  /* r224.4 */
            uint8_t LaserBiasHighWarningMaskTx6 : 1;  /* r224.5 */
            uint8_t LaserBiasHighWarningMaskTx7 : 1;  /* r224.6 */
            uint8_t LaserBiasHighWarningMaskTx8 : 1;  /* r224.7 */
        };
        uint8_t LaserBiasHighWarningMaskTx;
    };
        /**
         * @brief LaserBiasLowWarningMaskTx1
         */
        /**
         * @brief LaserBiasLowWarningMaskTx2
         */
        /**
         * @brief LaserBiasLowWarningMaskTx3
         */
        /**
         * @brief LaserBiasLowWarningMaskTx4
         */
        /**
         * @brief LaserBiasLowWarningMaskTx5
         */
        /**
         * @brief LaserBiasLowWarningMaskTx6
         */
        /**
         * @brief LaserBiasLowWarningMaskTx7
         */
        /**
         * @brief LaserBiasLowWarningMaskTx8
         * @details LaserBiasLowWarningMaskTx<i> Mask for LaserBiasLowWarningFlagTx<i>, media lane <i> Advertisement: 
         * 01h:160.0
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t LaserBiasLowWarningMaskTx1 : 1;  /* r225.0 */
            uint8_t LaserBiasLowWarningMaskTx2 : 1;  /* r225.1 */
            uint8_t LaserBiasLowWarningMaskTx3 : 1;  /* r225.2 */
            uint8_t LaserBiasLowWarningMaskTx4 : 1;  /* r225.3 */
            uint8_t LaserBiasLowWarningMaskTx5 : 1;  /* r225.4 */
            uint8_t LaserBiasLowWarningMaskTx6 : 1;  /* r225.5 */
            uint8_t LaserBiasLowWarningMaskTx7 : 1;  /* r225.6 */
            uint8_t LaserBiasLowWarningMaskTx8 : 1;  /* r225.7 */
        };
        uint8_t LaserBiasLowWarningMaskTx;
    };
        /**
         * @brief LOSMaskRx1
         */
        /**
         * @brief LOSMaskRx2
         */
        /**
         * @brief LOSMaskRx3
         */
        /**
         * @brief LOSMaskRx4
         */
        /**
         * @brief LOSMaskRx5
         * @details Advertisement: 01h:158.1
         */
        /**
         * @brief LOSMaskRx6
         */
        /**
         * @brief LOSMaskRx7
         */
        /**
         * @brief LOSMaskRx8
         * @details LOSMaskRx<i> Mask for LOSFlagRx<i>, media lane <i>
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t LOSMaskRx1 : 1;  /* r226.0 */
            uint8_t LOSMaskRx2 : 1;  /* r226.1 */
            uint8_t LOSMaskRx3 : 1;  /* r226.2 */
            uint8_t LOSMaskRx4 : 1;  /* r226.3 */
            uint8_t LOSMaskRx5 : 1;  /* r226.4 */
            uint8_t LOSMaskRx6 : 1;  /* r226.5 */
            uint8_t LOSMaskRx7 : 1;  /* r226.6 */
            uint8_t LOSMaskRx8 : 1;  /* r226.7 */
        };
        uint8_t LOSMaskRx;
    };
        /**
         * @brief CDRLOLMaskRx1
         */
        /**
         * @brief CDRLOLMaskRx2
         */
        /**
         * @brief CDRLOLMaskRx3
         */
        /**
         * @brief CDRLOLMaskRx4
         */
        /**
         * @brief CDRLOLMaskRx5
         */
        /**
         * @brief CDRLOLMaskRx6
         */
        /**
         * @brief CDRLOLMaskRx7
         */
        /**
         * @brief CDRLOLMaskRx8
         * @details CDRLOLMaskRx<i> Mask for CDRLOLFlagRx<i>, media lane <i> Advertisement: 01h:158.2
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t CDRLOLMaskRx1 : 1;  /* r227.0 */
            uint8_t CDRLOLMaskRx2 : 1;  /* r227.1 */
            uint8_t CDRLOLMaskRx3 : 1;  /* r227.2 */
            uint8_t CDRLOLMaskRx4 : 1;  /* r227.3 */
            uint8_t CDRLOLMaskRx5 : 1;  /* r227.4 */
            uint8_t CDRLOLMaskRx6 : 1;  /* r227.5 */
            uint8_t CDRLOLMaskRx7 : 1;  /* r227.6 */
            uint8_t CDRLOLMaskRx8 : 1;  /* r227.7 */
        };
        uint8_t CDRLOLMaskRx;
    };
        /**
         * @brief OpticalPowerHighAlarmMaskRx1
         */
        /**
         * @brief OpticalPowerHighAlarmMaskRx2
         */
        /**
         * @brief OpticalPowerHighAlarmMaskRx3
         */
        /**
         * @brief OpticalPowerHighAlarmMaskRx4
         */
        /**
         * @brief OpticalPowerHighAlarmMaskRx5
         */
        /**
         * @brief OpticalPowerHighAlarmMaskRx6
         */
        /**
         * @brief OpticalPowerHighAlarmMaskRx7
         */
        /**
         * @brief OpticalPowerHighAlarmMaskRx8
         * @details OpticalPowerHighAlarmMaskRx<i> Mask for OpticalPowerHighAlarmFlagRx<i>, media lane <i> 
         * Advertisement:01h:160.2
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t OpticalPowerHighAlarmMaskRx1 : 1;  /* r228.0 */
            uint8_t OpticalPowerHighAlarmMaskRx2 : 1;  /* r228.1 */
            uint8_t OpticalPowerHighAlarmMaskRx3 : 1;  /* r228.2 */
            uint8_t OpticalPowerHighAlarmMaskRx4 : 1;  /* r228.3 */
            uint8_t OpticalPowerHighAlarmMaskRx5 : 1;  /* r228.4 */
            uint8_t OpticalPowerHighAlarmMaskRx6 : 1;  /* r228.5 */
            uint8_t OpticalPowerHighAlarmMaskRx7 : 1;  /* r228.6 */
            uint8_t OpticalPowerHighAlarmMaskRx8 : 1;  /* r228.7 */
        };
        uint8_t OpticalPowerHighAlarmMaskRx;
    };
        /**
         * @brief OpticalPowerLowAlarmMaskRx1
         */
        /**
         * @brief OpticalPowerLowAlarmMaskRx2
         */
        /**
         * @brief OpticalPowerLowAlarmMaskRx3
         */
        /**
         * @brief OpticalPowerLowAlarmMaskRx4
         */
        /**
         * @brief OpticalPowerLowAlarmMaskRx5
         */
        /**
         * @brief OpticalPowerLowAlarmMaskRx6
         */
        /**
         * @brief OpticalPowerLowAlarmMaskRx7
         */
        /**
         * @brief OpticalPowerLowAlarmMaskRx8
         * @details OpticalPowerLowAlarmMaskRx<i> Mask for OpticalPowerLowAlarmFlagRx<i>, media lane <i> Advertisement: 
         * 01h:160.2
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t OpticalPowerLowAlarmMaskRx1 : 1;  /* r229.0 */
            uint8_t OpticalPowerLowAlarmMaskRx2 : 1;  /* r229.1 */
            uint8_t OpticalPowerLowAlarmMaskRx3 : 1;  /* r229.2 */
            uint8_t OpticalPowerLowAlarmMaskRx4 : 1;  /* r229.3 */
            uint8_t OpticalPowerLowAlarmMaskRx5 : 1;  /* r229.4 */
            uint8_t OpticalPowerLowAlarmMaskRx6 : 1;  /* r229.5 */
            uint8_t OpticalPowerLowAlarmMaskRx7 : 1;  /* r229.6 */
            uint8_t OpticalPowerLowAlarmMaskRx8 : 1;  /* r229.7 */
        };
        uint8_t OpticalPowerLowAlarmMaskRx;
    };
        /**
         * @brief OpticalPowerHighWarningMaskRx1
         */
        /**
         * @brief OpticalPowerHighWarningMaskRx2
         */
        /**
         * @brief OpticalPowerHighWarningMaskRx3
         */
        /**
         * @brief OpticalPowerHighWarningMaskRx4
         */
        /**
         * @brief OpticalPowerHighWarningMaskRx5
         */
        /**
         * @brief OpticalPowerHighWarningMaskRx6
         */
        /**
         * @brief OpticalPowerHighWarningMaskRx7
         */
        /**
         * @brief OpticalPowerHighWarningMaskRx8
         * @details OpticalPowerHighWarningMaskRx<i> Mask for OpticalPowerHighWarningFlagRx<i>, media lane <i> 
         * Advertisement:01h:160.2
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t OpticalPowerHighWarningMaskRx1 : 1;  /* r230.0 */
            uint8_t OpticalPowerHighWarningMaskRx2 : 1;  /* r230.1 */
            uint8_t OpticalPowerHighWarningMaskRx3 : 1;  /* r230.2 */
            uint8_t OpticalPowerHighWarningMaskRx4 : 1;  /* r230.3 */
            uint8_t OpticalPowerHighWarningMaskRx5 : 1;  /* r230.4 */
            uint8_t OpticalPowerHighWarningMaskRx6 : 1;  /* r230.5 */
            uint8_t OpticalPowerHighWarningMaskRx7 : 1;  /* r230.6 */
            uint8_t OpticalPowerHighWarningMaskRx8 : 1;  /* r230.7 */
        };
        uint8_t OpticalPowerHighWarningMaskRx;
    };
        /**
         * @brief OpticalPowerLowWarningMaskRx1
         */
        /**
         * @brief OpticalPowerLowWarningMaskRx2
         */
        /**
         * @brief OpticalPowerLowWarningMaskRx3
         */
        /**
         * @brief OpticalPowerLowWarningMaskRx4
         */
        /**
         * @brief OpticalPowerLowWarningMaskRx5
         */
        /**
         * @brief OpticalPowerLowWarningMaskRx6
         */
        /**
         * @brief OpticalPowerLowWarningMaskRx7
         */
        /**
         * @brief OpticalPowerLowWarningMaskRx8
         * @details OpticalPowerLowWarningMaskRx<i> Mask for OpticalPowerLowWarningFlagRx<i>, media lane <i> 
         * Advertisement:01h:160.2
         * @access RW Adv.
         */
    union {
        struct {
            uint8_t OpticalPowerLowWarningMaskRx1 : 1;  /* r231.0 */
            uint8_t OpticalPowerLowWarningMaskRx2 : 1;  /* r231.1 */
            uint8_t OpticalPowerLowWarningMaskRx3 : 1;  /* r231.2 */
            uint8_t OpticalPowerLowWarningMaskRx4 : 1;  /* r231.3 */
            uint8_t OpticalPowerLowWarningMaskRx5 : 1;  /* r231.4 */
            uint8_t OpticalPowerLowWarningMaskRx6 : 1;  /* r231.5 */
            uint8_t OpticalPowerLowWarningMaskRx7 : 1;  /* r231.6 */
            uint8_t OpticalPowerLowWarningMaskRx8 : 1;  /* r231.7 */
        };
        uint8_t OpticalPowerLowWarningMaskRx;
    };
        /**
         * @brief OutputStatusChangedMaskRx1
         */
        /**
         * @brief OutputStatusChangedMaskRx2
         */
        /**
         * @brief OutputStatusChangedMaskRx3
         */
        /**
         * @brief OutputStatusChangedMaskRx4
         */
        /**
         * @brief OutputStatusChangedMaskRx5
         */
        /**
         * @brief OutputStatusChangedMaskRx6
         */
        /**
         * @brief OutputStatusChangedMaskRx7
         */
        /**
         * @brief OutputStatusChangedMaskRx8
         * @details OutputStatusChangedMaskRx<i> Mask for OutputStatusChangedFlagRx<i>, media lane <i>
         * @access RW Rqd.
         */
    union {
        struct {
            uint8_t OutputStatusChangedMaskRx1 : 1;  /* r232.0 */
            uint8_t OutputStatusChangedMaskRx2 : 1;  /* r232.1 */
            uint8_t OutputStatusChangedMaskRx3 : 1;  /* r232.2 */
            uint8_t OutputStatusChangedMaskRx4 : 1;  /* r232.3 */
            uint8_t OutputStatusChangedMaskRx5 : 1;  /* r232.4 */
            uint8_t OutputStatusChangedMaskRx6 : 1;  /* r232.5 */
            uint8_t OutputStatusChangedMaskRx7 : 1;  /* r232.6 */
            uint8_t OutputStatusChangedMaskRx8 : 1;  /* r232.7 */
        };
        uint8_t OutputStatusChangedMaskRx;
    };
    uint8_t reserved_233[7];  /**< r233.. */
    /**
     * @brief CustomInfo
     * @details Custom information
     */
    uint8_t CustomInfo[16];  /* r240 */

} cmis_page_10h_t;

#if __STDC_VERSION__ >= 202311L
static_assert(sizeof(cmis_page_10h_t) == 128, "cmis_page_10h_t must be exactly 128 bytes");
#elif __STDC_VERSION__ >= 201112L
_Static_assert(sizeof(cmis_page_10h_t) == 128, "cmis_page_10h_t must be exactly 128 bytes");
#elif defined(__GNUC__) || defined(__clang__)
_Static_assert(sizeof(cmis_page_10h_t) == 128, "cmis_page_10h_t must be exactly 128 bytes");
#else
/* verify manually: sizeof(cmis_page_10h_t) must be 128 */
#endif

#endif  // __CMIS_PAGE_10H_H