/* Auto-generated by CMIS2C - CMIS Page 04h Register Map */
#ifndef __CMIS_PAGE_04H_H
#define __CMIS_PAGE_04H_H

#include <stdint.h>

/** @brief CMIS Page 04h Register Map (Bytes 128-255) */
typedef struct __attribute__((packed)) {

        /**
         * @brief GridSupported3p125GHz
         * @details Bool: Indicates whether the module supports channel-based tuning on 3.125 GHz grid defined as: 
         * Frequency(THz) = 193.1 + n × 0.003125 0b: 3.125 GHz Grid not supported 1b: 3.125 GHz Grid supported
         * @access RO Rqd.
         */
        /**
         * @brief GridSupported6p25GHz
         * @details Bool: Indicates whether the module supports channel-based tuning on the 6.25 GHz grid defined as: 
         * Frequency(THz) = 193.1 + n × 0.00625 0b: 6.25 GHz Grid not supported 1b: 6.25 GHz Grid supported
         * @access RO Rqd.
         */
        /**
         * @brief GridSupported12p5GHz
         * @details Bool: Indicates whether the module supports channel-based tuning on the 12.5 GHz grid defined as: 
         * Frequency(THz) = 193.1 + n × 0.0125 0b: 12.5 GHz Grid not supported 1b: 12.5 GHz Grid supported
         * @access RO Rqd.
         */
        /**
         * @brief GridSupported25GHz
         * @details Bool: Indicates whether the module supports channel-based tuning on the 25 GHz grid defined as: 
         * Frequency(THz) = 193.1 + n × 0.025 0b: 25 GHz Grid not supported 1b: 25 GHz Grid supported
         * @access RO Rqd.
         */
        /**
         * @brief GridSupported50GHz
         * @details Bool: Indicates whether the module supports channel-based tuning on the 50 GHz grid defined as: 
         * Frequency(THz) = 193.1 + n × 0.05 0b: 50 GHz Grid not supported 1b: 50 GHz Grid supported
         * @access RO Rqd.
         */
        /**
         * @brief GridSupported100GHz
         * @details Bool: Indicates whether the module supports channel-based tuning on the 100 GHz grid defined as: 
         * Frequency(THz) = 193.1 + n × 0.1 0b: 100 GHz Grid not supported 1b: 100 GHz Grid supported
         * @access RO Rqd.
         */
        /**
         * @brief GridSupported33GHz
         * @details Bool: Indicates whether the module supports channel-based tuning on the 33 GHz grid defined as: 
         * Frequency(THz) = 193.1 + n × 0.1/3 0b: 33 GHz Grid not supported 1b: 33 GHz Grid supported
         * @access RO Rqd.
         */
        /**
         * @brief GridSupported75GHz
         * @details Bool: Indicates whether the module supports channel-based tuning on the 75 GHz grid defined as: 
         * Frequency(THz) = 193.1 + n × 0.025 where n must be an integer multiple of 3. 0b: 75 GHz Grid not supported 
         * 1b:75 GHz Grid supported n is the 16-bit signed channel number that is referred to in the highest/lowest 
         * supportedchannel numbers in Page 04h
         * @access RO Rqd.
         */
    union {
        struct {
            uint8_t GridSupported3p125GHz : 1;  /* r128.0 */
            uint8_t GridSupported6p25GHz : 1;  /* r128.1 */
            uint8_t GridSupported12p5GHz : 1;  /* r128.2 */
            uint8_t GridSupported25GHz : 1;  /* r128.3 */
            uint8_t GridSupported50GHz : 1;  /* r128.4 */
            uint8_t GridSupported100GHz : 1;  /* r128.5 */
            uint8_t GridSupported33GHz : 1;  /* r128.6 */
            uint8_t GridSupported75GHz : 1;  /* r128.7 */
        };
        uint8_t r128;
    };
        /**
         * @brief GridSupported150GHz
         * @details Bool: Indicates whether the module supports channel-based tuning on the 150 GHz grid defined as: 
         * Frequency(THz) = 193.1 + (n+3) × 0.025 where n must be an integer multiple of 6. 0b: 150 GHz Grid not 
         * supported1b: 150 GHz Grid supported
         */
        /**
         * @brief FineTuningSupported
         * @details Bool: Indicates whether the module supports fine-tuning of laser frequency in the vicinity of an 
         * on-gridchannel. 0b: module does not support fine-tuning 1b: module supports fine-tuning
         * @access RO Rqd.
         */
    union {
        struct {
            uint8_t _pad_129_0 : 6;
            uint8_t GridSupported150GHz : 1;  /* r129.6 */
            uint8_t FineTuningSupported : 1;  /* r129.7 */
        };
        uint8_t r129;
    };
    /**
     * @brief GridLowChannel3p125GHz
     * @details S16 Lowest supported n for 3.125 GHz spacing
     * @access RO Rqd.
     */
    uint16_t GridLowChannel3p125GHz;  /* r130 */
    /**
     * @brief GridHighChannel3p125GHz
     * @details S16 Highest supported n for 3.125 GHz spacing
     * @access RO Rqd.
     */
    uint16_t GridHighChannel3p125GHz;  /* r132 */
    /**
     * @brief GridLowChannel6p25GHz
     * @details S16 Lowest supported n for 6.25 GHz spacing
     * @access RO Rqd.
     */
    uint16_t GridLowChannel6p25GHz;  /* r134 */
    /**
     * @brief GridHighChannel6p25GHz
     * @details S16 Highest supported n for 6.25 GHz spacing
     * @access RO Rqd.
     */
    uint16_t GridHighChannel6p25GHz;  /* r136 */
    /**
     * @brief GridLowChannel12p5GHz
     * @details S16 Lowest supported n for 12.5 GHz spacing
     * @access RO Rqd.
     */
    uint16_t GridLowChannel12p5GHz;  /* r138 */
    /**
     * @brief GridHighChannel12p5GHz
     * @details S16 Highest supported n for 12.5 GHz spacing
     * @access RO Rqd.
     */
    uint16_t GridHighChannel12p5GHz;  /* r140 */
    /**
     * @brief GridLowChannel25GHz
     * @details S16 Lowest supported n for 25 GHz spacing
     * @access RO Rqd.
     */
    uint16_t GridLowChannel25GHz;  /* r142 */
    /**
     * @brief GridHighChannel25GHz
     * @details S16 Highest supported n for 25 GHz spacing
     * @access RO Rqd.
     */
    uint16_t GridHighChannel25GHz;  /* r144 */
    /**
     * @brief GridLowChannel50GHz
     * @details S16 Lowest supported n for 50 GHz spacing
     * @access RO Rqd.
     */
    uint16_t GridLowChannel50GHz;  /* r146 */
    /**
     * @brief GridHighChannel50GHz
     * @details S16 Highest supported n for 50 GHz spacing
     * @access RO Rqd.
     */
    uint16_t GridHighChannel50GHz;  /* r148 */
    /**
     * @brief GridLowChannel100GHz
     * @details S16 Lowest supported n for 100 GHz spacing
     * @access RO Rqd.
     */
    uint16_t GridLowChannel100GHz;  /* r150 */
    /**
     * @brief GridHighChannel100GHz
     * @details S16 Highest supported n for 100 GHz spacing
     * @access RO Rqd.
     */
    uint16_t GridHighChannel100GHz;  /* r152 */
    /**
     * @brief GridLowChannel33GHz
     * @details S16 Lowest supported n for 33 GHz spacing
     * @access RO Rqd.
     */
    uint16_t GridLowChannel33GHz;  /* r154 */
    /**
     * @brief GridHighChannel33GHz
     * @details S16 Highest supported n for 33 GHz spacing
     * @access RO Rqd.
     */
    uint16_t GridHighChannel33GHz;  /* r156 */
    /**
     * @brief GridLowChannel75GHz
     * @details S16 Lowest supported n for 75 GHz spacing
     * @access RO Rqd.
     */
    uint16_t GridLowChannel75GHz;  /* r158 */
    /**
     * @brief GridHighChannel75GHz
     * @details S16 Highest supported n for 75 GHz spacing
     * @access RO Rqd.
     */
    uint16_t GridHighChannel75GHz;  /* r160 */
    /**
     * @brief GridLowChannel150GHz
     * @details S16 Lowest supported n for 150 GHz spacing
     * @access RO Rqd.
     */
    uint16_t GridLowChannel150GHz;  /* r162 */
    /**
     * @brief GridHighChannel150GHz
     * @details S16 Highest supported n for 150 GHz spacing
     * @access RO Rqd.
     */
    uint16_t GridHighChannel150GHz;  /* r164 */
    uint8_t reserved_166[24];  /**< r166.. */
    /**
     * @brief FineTuningResolution
     * @details U16 Fine-tuning resolution, increments of 0.001 GHz
     * @access RO Rqd.
     */
    uint16_t FineTuningResolution;  /* r190 */
    /**
     * @brief FineTuningLowOffset
     * @details S16 lowest fine-tuning offset with resolution of 0.001 GHz
     * @access RO Rqd.
     */
    uint16_t FineTuningLowOffset;  /* r192 */
    /**
     * @brief FineTuningHighOffset
     * @details S16 highest fine-tuning offset in increments of 0.001 GHz
     * @access RO Rqd.
     */
    uint16_t FineTuningHighOffset;  /* r194 */
        /**
         * @brief ProgOutputPowerPerLaneSuPported
         * @details 0b: Programmable output power per lane not supported 1b: Programmable output power per lane 
         * supported
         * @access RO Rqd.
         */
    union {
        struct {
            uint8_t _pad_196_0 : 7;
            uint8_t ProgOutputPowerPerLaneSuPported : 1;  /* r196.7 */
        };
        uint8_t ProgOutputPowerPerLaneSuPported_196;
    };
    uint8_t reserved_197;  /**< r197 Reserved */
    /**
     * @brief ProgOutputPowerMin
     * @details S16 Minimum Programmable Output Power in increments of 0.01 dBm
     * @access RO Rqd.
     */
    uint16_t ProgOutputPowerMin;  /* r198 */
    /**
     * @brief ProgOutputPowerMax
     * @details S16 Maximum Programmable Output Power in increments of 0.01 dBm
     * @access RO Rqd.
     */
    uint16_t ProgOutputPowerMax;  /* r200 */
    uint8_t reserved_202[53];  /**< r202.. */
    /**
     * @brief PageChecksum
     * @details Page Checksum over bytes 128-254 (see section 8.1.4.3)
     * @access RO Rqd.
     */
    uint8_t PageChecksum;  /* r255 */

} cmis_page_04h_t;

#if __STDC_VERSION__ >= 202311L
static_assert(sizeof(cmis_page_04h_t) == 128, "cmis_page_04h_t must be exactly 128 bytes");
#elif __STDC_VERSION__ >= 201112L
_Static_assert(sizeof(cmis_page_04h_t) == 128, "cmis_page_04h_t must be exactly 128 bytes");
#elif defined(__GNUC__) || defined(__clang__)
_Static_assert(sizeof(cmis_page_04h_t) == 128, "cmis_page_04h_t must be exactly 128 bytes");
#else
/* verify manually: sizeof(cmis_page_04h_t) must be 128 */
#endif

#endif  // __CMIS_PAGE_04H_H