"""CLI Entry Point."""

import click
import os
from .parser import (extract_cmis_data, extract_page00h_data, extract_page01h_data,
                     extract_page02h_data, extract_page04h_data, extract_page10h_data,
                     extract_page11h_data, extract_page12h_data, extract_page13h_data,                      extract_page14h_data, extract_page2fh_data, extract_page9fh_data)
from .generator import (generate_c_header, generate_page00h_header, generate_page01h_header,
                        generate_page02h_header, generate_page04h_header, generate_page10h_header,
                        generate_page11h_header, generate_page12h_header, generate_page13h_header,
                        generate_page14h_header, generate_page2fh_header, generate_page9fh_header)

PAGES = [
    ("Low memory", extract_cmis_data, generate_c_header, "cmis_low_memory.h"),
    ("Page 00h", extract_page00h_data, generate_page00h_header, "cmis_page_00h.h"),
    ("Page 01h", extract_page01h_data, generate_page01h_header, "cmis_page_01h.h"),
    ("Page 02h", extract_page02h_data, generate_page02h_header, "cmis_page_02h.h"),
    ("Page 04h", extract_page04h_data, generate_page04h_header, "cmis_page_04h.h"),
    ("Page 10h", extract_page10h_data, generate_page10h_header, "cmis_page_10h.h"),
    ("Page 11h", extract_page11h_data, generate_page11h_header, "cmis_page_11h.h"),
    ("Page 12h", extract_page12h_data, generate_page12h_header, "cmis_page_12h.h"),
    ("Page 13h", extract_page13h_data, generate_page13h_header, "cmis_page_13h.h"),
    ("Page 14h", extract_page14h_data, generate_page14h_header, "cmis_page_14h.h"),
    ("Page 2Fh", extract_page2fh_data, generate_page2fh_header, "cmis_page_2fh.h"),
    ("Page 9Fh", extract_page9fh_data, generate_page9fh_header, "cmis_page_9fh.h"),
]

CMIS_UMBRELLA_H = "/* Auto-generated by CMIS2C - CMIS umbrella header */\n"
CMIS_UMBRELLA_H += "#ifndef __CMIS_H\n#define __CMIS_H\n\n"
for _, _, _, fn in PAGES:
    CMIS_UMBRELLA_H += f'#include "{fn}"\n'
CMIS_UMBRELLA_H += "\n#endif  // __CMIS_H\n"

@click.group()
def cli():
    """CMIS2C - Generate C header files from CMIS PDF."""
    pass

@cli.command()
@click.argument('pdf_path')
@click.option('-o', '--output-dir', default='.', help='Output directory for generated headers')
def generate(pdf_path, output_dir):
    """Parse CMIS PDF and generate C headers."""
    if not os.path.exists(pdf_path):
        click.echo(f"Error: File '{pdf_path}' not found.")
        return

    os.makedirs(output_dir, exist_ok=True)
    click.echo(f"Parsing {pdf_path}...")

    try:
        for label, extract_fn, gen_fn, filename in PAGES:
            regs = extract_fn(pdf_path)
            click.echo(f"{label}: {len(regs)} register definitions.")
            path = os.path.join(output_dir, filename)
            if gen_fn(regs, path):
                click.echo(f"  -> {path}")
            else:
                click.echo(f"  Failed to generate {filename}")

        umbrella_path = os.path.join(output_dir, "cmis.h")
        with open(umbrella_path, "w", encoding="utf-8") as f:
            f.write(CMIS_UMBRELLA_H)
        click.echo(f"  -> {umbrella_path}")

    except Exception as e:
        click.echo(f"Error during processing: {e}", err=True)

def main():
    cli()
